### ISSUE TITLE
Use dep

### ISSUE THREAD

**Issue by dhui** [golang-migrate/migrate#1]
Hold off on using `dep` until it supports build tags. We don't want to pull in unnecessary dependencies. e.g. if you're only using migrate for postgres, there's no reason why you should have a dependency on cassandra driver

https://github.com/golang/dep/issues/291

**Comment by Its-Alex** [comment]
But for now all dependencies is pulled no ? So with or without dep is the same for dependencies no ?

**Comment by dhui** [comment]
Currently, there's a whitelist of db dependencies specified in the Makefile (see the `build-cli` target and the `DATABASE` variable)

**Comment by Its-Alex** [comment]
The executable weights less than 10 mb with all dependencies, moreover when using `make deps` all dependencies are pulled.

People who wants to build with only one dependency can always do it, so there are no real change to include dep now.

**Comment by dhui** [comment]
migrate now uses dep as of commit https://github.com/golang-migrate/migrate/commit/3d7b06e24c7f4c3ed706730447bfae19c4df8f50 and build https://travis-ci.org/golang-migrate/migrate/jobs/386409073
