### ISSUE TITLE
Migration not run inside other schema using extensions using search_path

### ISSUE THREAD

**Issue by johndiego** [golang-migrate/migrate#1003]
**Migration not run inside other schema with extensions**

**Steps to Reproduce**

**Migrations**
 **000001_create_test.up.sql**
  ```CREATE EXTENSION IF NOT EXISTS citext;
  CREATE TABLE IF NOT EXISTS users(
     user_id      serial PRIMARY KEY,
     username   	CITEXT DEFAULT gen_random_uuid(),
     password     VARCHAR (50) NOT NULL
  );```
  **000001_create_test.down.sql**
 ``` DROP TABLE IF EXISTS users;```
 
**command**  migrate -database ${POSTGRESQL_URL} -path db/migrations up

error: migration failed: type "citext" does not exist (column 16) in line 4:
CREATE TABLE IF NOT EXISTS users(
   user_id      serial PRIMARY KEY,
   username     CITEXT DEFAULT gen_random_uuid(),
   password     VARCHAR (50) NOT NULL
); (details: pq: type "citext" does not exist)

**Comment by johndiego** [comment]
![image](https://github.com/golang-migrate/migrate/assets/18476845/4d9d8b6a-e5c0-429d-b9b9-50c6f5db8237)


![image](https://github.com/golang-migrate/migrate/assets/18476845/93ea47da-625a-4699-96b4-c806e470af76)

![image](https://github.com/golang-migrate/migrate/assets/18476845/98b3240f-4379-440f-861c-92da1748c1b9)

**Comment by HenryChauFV** [comment]
Could you using x-migrations-table replace search_path another in script create table, need to include <schema>.<table>

details on this: https://github.com/golang-migrate/migrate/tree/master/database/postgres

**Comment by johndiego** [comment]
thanks @HenryChauFV
