### ISSUE TITLE
Problem with cli

### ISSUE THREAD

**Issue by ali-mhz** [golang-migrate/migrate#101]
**Describe the Bug**
when i run this
`$ migrate -source file://migrations -database mysql://root:123456@tcp(localhost:3306)/mydb?x-migrations-table migrations up`
it shows this error
`syntax error near unexpected token `('`

**Migrate Version**
dev

**Loaded Source Drivers**
Source drivers: file

**Loaded Database Drivers**
Database drivers: mysql, stub

**Comment by dhui** [comment]
It's probably a syntax error in your migration.

Have you tried running the migration using the mysql client cli?

**Comment by ali-mhz** [comment]
I generated the script using mysql workbench and i tested it and it has no error, this happens also when i use DOWN command and i even don't have parentheses in my down script:
`DROP TABLE `pezeshkiinja`.`users`;`

**Comment by ali-mhz** [comment]
@dhui I tested my connection in the code and it can connect and run query:
`db, err := sql.Open("mysql", "root:123456@tcp(localhost:3306)/mydb")`

**Comment by dhui** [comment]
Try quoting the connection string. I'm guessing that the `:` character being interpreted by your shell.
