### ISSUE TITLE
v3 module breaks vendoring

### ISSUE THREAD

**Issue by buckhx** [golang-migrate/migrate#104]
**Describe the Bug**
Adding the v3 module breaks systems relying on vendoring b/c github.com/golang-migrate/migrate/v3 is not a code path.

Seeing as how modules are still experimental in go1.11, imports using the standard vendor pattern should still be supported.

This commit changes all the import paths to v3
https://github.com/golang-migrate/migrate/commit/16dea48c822e304da392f13c7a87a03752b665be

**Comment by dhui** [comment]
Closing in favor of https://github.com/golang-migrate/migrate/issues/103

**Comment by dhui** [comment]
Actually, this may be a separate issue than #103 
Sorry about the quick close.

How are you pinning your dependencies? Any release before v3.5.2 *should* not required an import change. Obviously, if you're using the latest and greatest (e.g. master branch), you'll need to update your imports.

Maybe reverting the change (releasing v3.5.3 and using v4 for module support) will fix this issue as Go 1.11 modules require an import path change w/ the current migrate version numbers...

**Comment by dhui** [comment]
Closing due to lack of a response. This is probably a duplicate or related.

`v3.5.3` (and `v3.5.4` if you're using docker) no longer use Go modules. `v4` has been release with Go module support.
