### ISSUE TITLE
golangci-lint: remove deprecated linter & fix lint

### ISSUE THREAD

**Issue by Shion1305** [golang-migrate/migrate#1104]
### Describe the Bug

When you run `golangci-lint` on this repository now, you'll get following errors.
![image](https://github.com/golang-migrate/migrate/assets/20254962/c795bde6-8c57-4fe0-9557-f3d40218bbb3)

Here is the problem...
- This repository uses `interfacer` linter, which is now deprecated.
- `errcheck` fails on these code...
https://github.com/golang-migrate/migrate/blob/aa2dad421f4dc7c9948a0dc2512a30efe47767d2/internal/cli/main.go#L278
https://github.com/golang-migrate/migrate/blob/aa2dad421f4dc7c9948a0dc2512a30efe47767d2/internal/cli/main.go#L309

### **Steps to Reproduce**

Just run the latest version of `golangci-lint`.
You can also reproduce by rerunning CI again.

**Comment by dhui** [comment]
Not sure why github didn't auto-resolve this issue. It's fixed by https://github.com/golang-migrate/migrate/pull/1105
