### ISSUE TITLE
can't find package github.com/golang-migrate/migrate/v3/database

### ISSUE THREAD

**Issue by kostyaVyrodov** [golang-migrate/migrate#111]
**Describe the Bug**
An error during getting github.com/golang-migrate/migrate

**Steps to Reproduce**
Migrate shouldn't be installed 
or
Delete the migrate:
1. ```rm -rf $GOPATH/src/github.com/golang-migrate/migrate```
2. ```go get github.com/golang-migrate/migrate```
3. See error: can't find package github.com/golang-migrate/migrate/v3/database

**Expected Behavior**
go get installs tge migrate successfully

**Go Version**
go version go1.10.2 darwin/amd64

**Stacktrace**
```
package github.com/golang-migrate/migrate/v3/database: cannot find package "github.com/golang-migrate/migrate/v3/database" in any of:
        /usr/local/Cellar/go/1.10.2/libexec/src/github.com/golang-migrate/migrate/v3/database (from $GOROOT)
        /Users/kvyrodov/go/src/github.com/golang-migrate/migrate/v3/database (from $GOPATH)
package github.com/golang-migrate/migrate/v3/source: cannot find package "github.com/golang-migrate/migrate/v3/source" in any of:
        /usr/local/Cellar/go/1.10.2/libexec/src/github.com/golang-migrate/migrate/v3/source (from $GOROOT)
        /Users/kvyrodov/go/src/github.com/golang-migrate/migrate/v3/source (from $GOPATH)
```

**Comment by alexey-belous** [comment]
Have the same issue

**Comment by dhui** [comment]
Probably related to https://github.com/golang-migrate/migrate/issues/103
For a short-term fix, try using a newer version of Go (1.10.3 or 1.11.x).

**Comment by kostyaVyrodov** [comment]
@dhui ,
> For a short-term fix, try using a newer version of Go (1.10.3 or 1.11.x).

It won't help. Because there is no v3 package in the master branch of the migrate repo

**Comment by dhui** [comment]
Using a newer version of Go should help as they're module aware

**Comment by davidraleigh** [comment]
Problem still exists for `golang:1.11-alpine` so newer version of go didn't help

**Comment by kostyaVyrodov** [comment]
I am not sure but it seems like the source folder should be inside 'v3' folder...?

![image](https://user-images.githubusercontent.com/15310397/46716322-35720800-cc6c-11e8-8246-989b6de6fec4.png)

**Comment by nutmix** [comment]
I have been trying to find a work around for this issue.  I removed my migrate directory, and manually cloned various old versions, including v1 branch, and v3.0.0 tag. All give his same error (github.com/golang-migrate/migrate/v3/database).  Does anyone know of a version or tag which is not broken?

**Comment by nutmix** [comment]
In an attempt to find a workaround, I checked out the v3.5.0 branch. However, I cant build or install this, it says:  

$ cd ~/go/src/github.com/golang-migrate/migrate
$ go build -i migrate.go
./migrate.go:60:6: undefined: Logger

GOPATH and GOBIN are correctly set and exported.

go version go1.10.2 darwin/amd64

**Comment by davidraleigh** [comment]
This fixed the problems for me, @dhui . I really appreciate your working on it Dale!
