### ISSUE TITLE
Cannot find a way to run migrations against Cloud SQL instance from Cloud run

### ISSUE THREAD

**Issue by lewisd1996** [golang-migrate/migrate#1113]
**Describe the Bug**
I understand this is just as much a GCP question as much as it is a go-migrate, but I'm desperate. Been struggling with this for days, it's most likely a lack of understanding on my part.

**Steps to Reproduce**
Here is my function that connects to the Cloud SQL database successfully. I also attempt to run migrations, however it fails:

```
import (
	"context"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"os/signal"
	"time"

	"cloud.google.com/go/cloudsqlconn"
	firebase "firebase.google.com/go"
	"google.golang.org/api/option"

	"github.com/golang-migrate/migrate/v4"

	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	"github.com/jackc/pgx/v5/pgxpool"
)

func connectToDb() (*pgxpool.Pool, error) {
	appConfig := utils.GetConfig()
	l := utils.GetLogger()

	// Configure the driver to connect to the database
	dsn := fmt.Sprintf("user=%s password=%s dbname=%s sslmode=disable", appConfig.DatabaseUser, appConfig.DatabasePassword, appConfig.DatabaseName)
	config, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		l.Err(err).Msg("Failed to parse config")
		return nil, err
	}

	// Create a new dialer with any options
	d, err := cloudsqlconn.NewDialer(context.Background())
	if err != nil {
		l.Err(err).Msg("Failed to create dialer")
		return nil, err
	}

	// Tell the driver to use the Cloud SQL Go Connector to create connections
	config.ConnConfig.DialFunc = func(ctx context.Context, _ string, instance string) (net.Conn, error) {
		return d.Dial(ctx, appConfig.DbInstanceConnectionName)
	}

	// Interact with the driver directly as you normally would
	pool, err := pgxpool.NewWithConfig(context.Background(), config)
	if err != nil {
		l.Err(err).Msg("Failed to connect to database")
		return nil, err
	}
	l.Info().Msgf("Connected to database")

	// Run migrations
	l.Info().Msgf("Running migrations...")
        
        // ERROR HERE
	m, err := migrate.New(
		"file:///app/db/postgres/migration",
		fmt.Sprintf("user=%s password=%s database=%s host=%s",
			appConfig.DatabaseUser,
			appConfig.DatabasePassword,
			appConfig.DatabaseName,
			"/cloudsql/"+appConfig.DbInstanceConnectionName,
		),
	)
	if err != nil {
		l.Err(err).Msg("Failed to create migration")
		return nil, err
	}

	err = m.Up()
	if err != nil && err != migrate.ErrNoChange {
		l.Err(err).Msg("Failed to run migrations")
		return nil, err
	}

	l.Info().Msg("Migrations complete")

	return pool, nil
}
```

The connection string I am giving to `migrate.New()` never works. 

Do you have any examples of how I can connect the two?

**Migrate Version**
v4.17.1

**Loaded Source Drivers**
e.g. s3, github, go-bindata, gcs, file
Obtained by running: `migrate -help`

**Loaded Database Drivers**
e.g postgres, postgresql, pgx

**Go Version**
go1.22.0 darwin/arm64

**Additional context**
My logs say:
2024-07-07T17:05:32Z Failed to create migrationerror="no scheme"

**Comment by heyimcarlos** [comment]
I'm getting this same error, it seems like the path to the migrations dir is incorrect.

**Comment by ehrktia** [comment]
i am starting the same journey as your self.
Trying to migrate schema using golang-migrate with cloudSQL in GCP for postgres.
Would like to know more details from your experience.

Can i ask the following
- have you tried running migrations from your local machine by connecting to cloudSQL ( in GCP) can u share your thoughts on this
- the connection url in postgres doc for golang migrate states https://github.com/golang-migrate/migrate/blob/master/database/postgres/README.md#database-urls the valid URL format is
`postgres://user:password@host:port/dbname?query`
i understand to connect with cloud sql we are required to provide instance/connection name i.e - `project:region:instance-name` in cloud sql connector.
Have you tried using the  format  described in golang-migrate document ?
- finally my thoughts on error, `no scheme` i understand it is looking for `postgers://` in the connection string

**Comment by ehrktia** [comment]
For any one looking into using golang-migrate/migrate with cloud SQL in GCP with private ip /with in VPC.

- Follow the url format as mentioned in the documentation https://github.com/golang-migrate/migrate/blob/master/database/postgres/README.md#database-urls `postgres://user:password@host:port/dbname`
`host` is the private ip for the instance
`user` try the postgres user
`password` postgres user password
`port` should be standard port 5432 or the configured port
I can confirm this works in GCP cloud SQL
@lewisd1996 amd @heyimcarlos  when you both have few mins can you check if this works in your end.

**Comment by lewisd1996** [comment]
Update from my end, I now have it working. 

Firstly, apologies for assuming this was an issue with golang-migrate, the issue was actually that my connection to Cloud SQL was broken. 

I was not pinging the database, I presumed with there were no errors, it meant the connection was successful. This is wrong and I urge everyone to `.ping()` their database before attempting to run migrations, just to confirm you are indeed connected.

The fix was to give my applications service account the `sql/admin` permission. It had `sql/client`, but for some reason it only works as an admin.

Here is my function that is responsible for running the migrations, in case anyone else needs help:

```
func RunMigrations(pool *pgxpool.Pool) error {
	l := utils.GetLogger()
	appConfig := utils.GetConfig()

	l.Info().Msgf("Running migrations...")
	db := stdlib.OpenDBFromPool(pool)

	driver, err := pgxv5driver.WithInstance(db, &pgxv5driver.Config{})

	if err != nil {
		l.Err(err).Msg("Failed to create driver")
		return err
	}

	m, err := migrate.NewWithDatabaseInstance(
		"file:///app/db/postgres/migration",
		appConfig.DatabaseName,
		driver,
	)

	if err != nil {
		l.Err(err).Msg("Failed to create migration")
		return err
	}

	err = m.Up()
	if err != nil && err != migrate.ErrNoChange {
		l.Err(err).Msg("Failed to run migrations")
		return err
	}

	latestVersion, dirty, err := m.Version()
	if err != nil {
		l.Err(err).Msg("Failed to get migration version")
		return err
	}
	l.Info().Uint("version", latestVersion).Msg("Migrations ran successfully")

	return nil
}
```

**Comment by heyimcarlos** [comment]
> For any one looking into using golang-migrate/migrate with cloud SQL in GCP with private ip /with in VPC.
> 
> * Follow the url format as mentioned in the documentation https://github.com/golang-migrate/migrate/blob/master/database/postgres/README.md#database-urls `postgres://user:password@host:port/dbname`
>   `host` is the private ip for the instance
>   `user` try the postgres user
>   `password` postgres user password
>   `port` should be standard port 5432 or the configured port
> * location of migration files is "file://app/db/postgres/migration" with two forward slashes not three
>   I can confirm this works in GCP cloud SQL
>   @lewisd1996 amd @heyimcarlos  when you both have few mins can you check if this works in your end.

I'm sorry for not getting back to you sooner. I wasn't trying to connect to a remote database; I used Golang-migrate to migrate to a local test database for each integration test running on my application. The setup wasn't optimal, so I opted for pgtestdb (which is optimized for my use case).
