### ISSUE TITLE
Spanner:  Arguments for spanner client creation

### ISSUE THREAD

**Issue by wmetaw** [golang-migrate/migrate#117]
**Is your feature request related to a problem? Please describe.**
Authentication options for connecting to spanner

**Describe the solution you'd like**
When connecting to Spanner from GAE / SE (go111 runtime), GAE / FE and local environment, we use authentication token to authenticate.
But we can not set ClientOption with Open function

I'd like to specify ClientOption for the arguments on the next line.
https://github.com/golang-migrate/migrate/blob/master/database/spanner/spanner.go#L93

Do you have any good ideas?

**Describe alternatives you've considered**

**Additional context**
Sample code to set ClientOption
https://gist.github.com/wmetaw/1a4501531e76aeac6ae96b8e76a81e4d#file-sample-go-L39-L40

**Comment by dhui** [comment]
You can't use env vars if you use the URI styled connection string to connect the the DB.
To use env vars, you'll need parse the env vars and connect to spanner yourself. Then pass that connection (a db instance) to [WithInstance()](https://godoc.org/github.com/golang-migrate/migrate/database/spanner#WithInstance)

**Comment by wmetaw** [comment]
@dhui thanks for the response, I tried to use [WithInstance()](https://godoc.org/github.com/golang-migrate/migrate/database/spanner#WithInstance) ,But We cannot Create [DB](https://github.com/golang-migrate/migrate/blob/master/database/spanner/spanner.go#L53-L56) . so Here’s an idea as follows:
- change private field to public
- add OpenDB method to spanner.go

```go
// example
func OpenDB(admin *sdb.DatabaseAdminClient, data *spanner.Client) *DB {
	return &DB{
		admin: admin,
		data:  data,
	}
}
```

**Comment by dhui** [comment]
I don't understand how `OpenDB()` is any different from creating your own instance of the db and passing it into `WithInstance()`. If you can call `OpenDB()`, then you can call `WithInstance()`
e.g. `spanner.WithInstance(&spanner.DB{admin: admin, data: data})`

**Comment by wmetaw** [comment]
Yes, I can call `WithInstance()`. But I can not create`&spanner.DB{admin: admin, data: data}` from External packages.

I wrote  sample code. Please check it out. 
https://github.com/wmetaw/migrate-sample/blob/master/main.go#L32-L41

<img width="770" alt="ss" src="https://user-images.githubusercontent.com/6606301/47608787-688b0880-da6e-11e8-8bc0-bff16e5a0862.png">

**Comment by wmetaw** [comment]
@dhui 
Thank you for your help
