### ISSUE TITLE
Failed parsing go migration files from CLI

### ISSUE THREAD

**Issue by emilianosantucci** [golang-migrate/migrate#1177]
**Describe the Bug**
Failed to use _.go_ files as migration files with CLI

**Steps to Reproduce**
1. Create (or use) a clean PostgreSQL db (ex. `mydb`)
2. Create this project structure:
  ```
  migrations/
  ├── 1_create_users_table.up.go
  ├── 1_create_users_table.down.go
  ├── 2_add_last_login_column.up.go
  └── 2_add_last_login_column.down.go
  ```
  Each file contains go code like below:
  ```go
  package migrations
  
  import (
          "database/sql"
  )
  
  func Up(db *sql.DB) error {
          _, err := db.Exec(`
                  ALTER TABLE users
                  ADD COLUMN last_login TIMESTAMP WITH TIME ZONE;
          `)
          return err
  }
  ```
3. Execute the migrate CLI:
  ```sh
    migrate -database "postgres://user:password@host:port/mydb" -path file://./migrations up
  ```

**Expected Behavior**
Migrate interprets migration files and execute them appropriately

**Migrate Version**
v4.18.1

**Loaded Source Drivers**
file

**Loaded Database Drivers**
postgres

**Go Version**
go version go1.23.1 darwin/arm64

**Stacktrace**
```sh
error: migration failed: syntax error at or near "package" (column 1) in line 1: package migrations



import (

	"database/sql"

)



func Up(db *sql.DB) error {

	_, err := db.Exec(`

                select 1;

        `)

	return err

}

 (details: pq: syntax error at or near "package")
```
**Additional context**
I don't know if really is it a bug, a wrong use of the CLI or my mistake.
I have not found any official documentation on using go, instead of sql, for migration files.

My goal is using `mapper` integrated with GORM and Uber FX to automate db migrations process. The usage of SQL files is not a suitable options for my project 'cause I can't use GORM AutoMigrate (+ custom logic) to handle db versioning.

**Comment by joschi** [comment]
[Migrations](https://github.com/golang-migrate/migrate/blob/v4.18.1/MIGRATIONS.md) typically have to contain valid SQL.

I am not aware that Go code would be used by any driver currently available in this project.

Where did you read that migrations can consist of Go code?

**Comment by emilianosantucci** [comment]
I don't exactly remember where but, after surfing a bit more, I asked it to Google Gemini and it reply with a solution to do that with `golang-migrate`.
Next, I use the CLI with `create` command and option `ext` hinted me I can do so.

Anyway, imho, could be a great solution to better organize migration files but if I'm in wrong, please close the issue and thank you for the reply.

**Comment by joschi** [comment]
> I asked it to Google Gemini

Well, hallucinations aren't exactly unexpected when asking questions to an LLM. 🙃

**Comment by emilianosantucci** [comment]
@joschi thank you for your time.

I hope #15 go forward to I can come back to this well done tool 😊.
