### ISSUE TITLE
error "source: URL cannot be empty" when try to migrate force

### ISSUE THREAD

**Issue by codehell** [golang-migrate/migrate#120]
Sorry about my English.

I get error "source: URL cannot be empty"

Having a dirty version in postgres database:
version: 20181026081224
dirty: true

Using migrate CLI, I run commands:

 - migrate force 20181026081224
 
- migrate force 20181026081224 -database postgres://localhost:5432/expenses

 - migrate force 20181026081224 -source postgres://localhost:5432/expenses

 - migrate force 20181026081224 -source file://dbo/migrations -database postgres://localhost:5432/expenses

 - migrate force 20181026081224 postgres://localhost:5432/expenses

**Expected Behavior**
dirty value becomes false

**Migrate Version**
4.0.2

**Loaded Source Drivers**
 godoc-vfs, gcs, file, s3, github, go-bindata

**Loaded Database Drivers**
Database drivers: stub, cockroach, cockroachdb, postgresql, mysql, postgres, redshift, spanner, cassandra, clickhouse, crdb-postgres

**Go Version**
go version go1.11.1 linux/amd64

**Comment by dhui** [comment]
Do all of the example commands give you the same error?

This particular command seems like it should work: `migrate force 20181026081224 -source file://dbo/migrations -database postgres://localhost:5432/expenses`

Also, try using `-path`. It's a friendly wrapper around `-source file://`. If that's not the case, then there's a bug that should be fixed

**Comment by codehell** [comment]
Yes, I have the same result in all of the example commands.
I tried with `-path` but had the same error:

> error: source: URL cannot be empty

**Comment by dhui** [comment]
Ahhh, I think I see the problem now. Your options need to precede the command. e.g. `-source`/`-path` need to be specified before `force`

See the [docs](https://github.com/golang-migrate/migrate/tree/master/cli#usage)

**Comment by codehell** [comment]
Exactly
`migrate -path dbo/migrations -database postgres://localhost:5432/expenses force 20181026081224
`
works as expected. I go wrong because "create" command also works after options.
Thank you.
