### ISSUE TITLE
Migrate.Steps returns weird errors, but migrations are successful

### ISSUE THREAD

**Issue by Hixon10** [golang-migrate/migrate#122]
**Describe the Bug**
I use migrations in Golang project. I get `os.ErrNotExist` and `ErrShortLimit` errors, but migrations are successful. There errors occurs. when there is no new migration, or if number of applied migrations is less, then limit.

**Steps to Reproduce**
```go
import (
    "database/sql"
    _ "github.com/lib/pq"
    "github.com/golang-migrate/migrate/v4"
    "github.com/golang-migrate/migrate/v4/database/postgres"
    _ "github.com/golang-migrate/migrate/v4/source/file"
)

func main() {
    db, err := sql.Open("postgres", "postgres://localhost:5432/database?sslmode=enable")
    driver, err := postgres.WithInstance(db, &postgres.Config{})
    m, err := migrate.NewWithDatabaseInstance(
        "file:///migrations",
        "postgres", driver)
    err = m.Steps(2)
	if err != nil {
		log.Panic(err)
	}
}
```

**Expected Behavior**
Why we need these errors? If migrations are successful, maybe we should get `nil` instead of error?

**Migrate Version**
v3.5.4

**Loaded Source Drivers**
file

**Loaded Database Drivers**
postgresql

**Go Version**
go1.11 windows/amd64

**Additional context**
Bug occurs there: `vendor/github.com/golang-migrate/migrate/migrate.go:505`:
```go
// reached end, and didn't apply any migrations
if limit > 0 && count == 0 {
	ret <- os.ErrNotExist
	return
}

// applied less migrations than limit?
if count < limit {
	ret <- ErrShortLimit{suint(limit - count)}
	return
}
```

**Comment by dhui** [comment]
This not a bug and is by design. If you use the `Steps()` method, you are expected to know the number of migrations to be applied. An error occurs if the the number of applied migrations differs from the intended number. If you don't know how many migrations you want to run, use `Up()` or `Down()` instead.

**Comment by Hixon10** [comment]
@dhui thank you.

**Comment by mikesun** [comment]
I'd like to use `m.Steps(1)` within a loop so I can do mimic the behavior of `m.Up()` but perform custom actions at each up step for specific versions. Not being able to receive an `ErrNoChange` if I call `m.Steps(1)` when the DB is already at the latest migration version keeps me from being able to do this. Is there a way I can implement such behavior?

**Comment by dhui** [comment]
@mikesun `ErrNoChange` is used when migrate detects that there's no change. Unfortunately, if you want to use `Steps()` directly, you'll either need to duplicate this logic or refactor `readUp()` and `readDown()` so that `Steps()` returns `ErrNoChange` when there's no migration to run.
