### ISSUE TITLE
Cannot get v4 package

### ISSUE THREAD

**Issue by mejmo** [golang-migrate/migrate#134]
I am getting an error while importing, is it a GoLand issue? How to fix it?

```
github.com/golang-migrate/migrate (download)
go: warning: "github.com/golang-migrate/migrate/v4/..." matched no packages
```

**Comment by dhui** [comment]
What version of Go are you using and are modules enabled?

**Comment by freezlite** [comment]
I got same with version 4.1.0

**Comment by dhui** [comment]
To be more explicit, what's in your `go.mod` file?

**Comment by janekolszak** [comment]
Yeah, same here:
- I don't have `go.mod` 
- I'm using `glide`
- Go 1.11.2

Maybe it's not possible to use `migrate` without using experimental golang modules?

**Comment by janekolszak** [comment]
I just read that migration v4 only supports go modules. You could have waited, it's still experimental :)

**Comment by dhui** [comment]
You'll need to use v3 if you're not using modules.

> I just read that migration v4 only supports go modules. You could have waited, it's still experimental :)

I don't know what else to say besides read the release notes before making a snarky complaint...

**Comment by dhui** [comment]
I've updated the README to consolidate info about the [major migrate versions](https://github.com/golang-migrate/migrate#supported-major-versions)
