### ISSUE TITLE
add context feature to include/exclude specific steps from migrations run 

### ISSUE THREAD

**Issue by ugizashinje** [golang-migrate/migrate#136]
Hi,

i want to able to filter out some migrations depending on environment. If i have C (create) I (insert) and A (alter) migrations in same source, in QA env I would run CIA (no pun intended), but in production env i would run only CA migrations.
Something similar to https://www.liquibase.org/documentation/contexts.html.

I've looked into code, and it would be best if we could filter out migrations by tags and Migrate.identifier. If file is named 1231.create-table.test.up.sql it would be skipped if tag test is provided. What would be best way to approach here? To extend struct migrate.Migrate to have tags filed ?

There is alternative(workaround) to checkout folder with migrations in local and then delete files with tag in their name and then execute whole list, rather i would use command option. I would know it is safe and i could execute against remote repository (git, s3 ...)

**Comment by dhui** [comment]
I'd strongly recommend against the workflow you mentioned since testing a migration for the first time in production is extremely dangerous. It'll also be very hard to ensure that there's no dependency between the migrations. Migrations are run in a serialized and consistent order to maximize reproducibility and what you're proposing opposes this.

Dangerous features will not be added to `migrate`.

**Comment by dhui** [comment]
It sounds like you want something like test fixtures in QA. In that case, I'd use a separate migration source containing just the test data and run that after your schema migrations are run.
e.g. using your example, run "C" and "A" in both QA and prod. Keep "I" separate and run that only in QA

Another option is to use a sanitized production snapshot for QA testing.

**Comment by ugizashinje** [comment]
Dale thank you for quick response !
I don't believe we understood each other, for sure i don't want to test migration first time in production. There should be no dependency except order of migration execution. Migrations should work even if database is populated, ie production database.  I just want to skip migrations that insert test data in production environment. 
Thank you for proposals, but first one that splits migrations in two folders requires me to manually change I scripts after every alternation that can be tedious task, plus alternations that work only on empty database can fail on populated one, for sure i want to test them. Second, there are lots of reasons why i would not use prod snapshot for QA, but one is quite enough, i dont have access (and never will) to it. Please take a look https://www.liquibase.org/documentation/contexts.html , i've used liquidbase for deployment in some pretty big banks, security should not be an issue.
We have few golang services and i would like to keep tech stack small, go migrate looks good but I would really like to see context added.

**Comment by dhui** [comment]
I don't know of a valid usecase for migration contexts/metadata. If anyone has a valid usecase, I'm all ears. Selectively applying migrations by filtering based on the metadata is not a valid usecase. As mentioned earlier, `migrate` will not provide a loaded foot-gun.

**Comment by ugizashinje** [comment]
At first I wanted to write use case, but then I realized one have provided is good enough. How can it be that skipping insert statements is so dangerous ? Can you explain situation where it may lead to hazard ? I would rather say doing migrations exclusively on empty database is dangerous because applying them to populated can result in failure. Altering table column with no data from varchar to int will pass if table empty, but will fail If that specific column contains something like e1221d. If you are doing only create and alters your migrations are not tested. 
Migrations should create testbed but this testbed should be skipped in production env.

**Comment by dhui** [comment]
The contents of the migrations are opaque to `migrate` [by design](https://github.com/golang-migrate/migrate/blob/master/MIGRATIONS.md#migration-content-format).

**Comment by ugizashinje** [comment]
Thanks, good to know this will not be implemented.
