### ISSUE TITLE
Support creating indexes concurrently in postgresql 

### ISSUE THREAD

**Issue by dankinder** [golang-migrate/migrate#137]
**Is your feature request related to a problem? Please describe.**
The postgres driver runs migrations in a transaction. This would typically be considered a good thing but you can't [create indexes concurrently ](https://www.postgresql.org/docs/9.1/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY) in a transaction. I.e. `CREATE INDEX CONCURRENTLY sales_quantity_index ON sales_table (quantity);` fails.

**Describe the solution you'd like**
Short of removing transactions from the driver completely, we would need some way to disable them for a particular migration, or for that project.

**Describe alternatives you've considered**
Options that come to mind:
- Add some symbol you can put in your migration file to indicate this file should be run with no transaction
- Add a flag to the tool or the driver to tell it not to use a transaction

I may even have time to contribute a feature like this but want to make sure it's a feature we want first.

**Comment by dhui** [comment]
You should be able to create indices concurrently.

> The postgres driver runs migrations in a transaction

This is not true. A transaction is used by the driver only when setting the applied schema version number. Any other transaction is in your migration file/source.

**Comment by dankinder** [comment]
Ah, sorry I was actually misinformed and we were using and older version of migrate (v1), it seems like since then this was changed and should work now. Sorry about that.
