### ISSUE TITLE
v4 regression? Getting "no database name" with MySQL 8

### ISSUE THREAD

**Issue by fsouza** [golang-migrate/migrate#139]
**Describe the Bug**

Whenever trying to use v4 and MySQL 8, I get the "error: no database name". The error doesn't happen if I use the binary obtained by running ``go get -tags mysql github.com/golang-migrate/migrate/cmd/migrate`` or if I downgrade to MySQL 5.

**Steps to Reproduce**

Programmatically:

```
$ mkdir /tmp/debug
$ cd /tmp/debug
$ go mod init github.com/fsouza/debug
$ cat > debug.go
package main

import (
	"os"

	"github.com/golang-migrate/migrate/v4"
	_ "github.com/golang-migrate/migrate/v4/database/mysql"
	_ "github.com/golang-migrate/migrate/v4/source/file"
)

func main() {
	const connString = "mysql://root:@tcp(127.0.0.1:3306)/whatever"

	_, err := migrate.New("file://"+os.Args[1], connString)
	if err != nil {
		panic(err)
	}
}
^-D
$ go build
$ ./debug <path to migrations>
panic: no database name

goroutine 1 [running]:
main.main()
	/tmp/debug/debug.go:16 +0xc4
```

**Expected Behavior**

Migrations should run.

**Migrate Version**

```
$ cat go.mod
module github.com/fsouza/debug

go 1.12

require github.com/golang-migrate/migrate/v4 v4.1.0
```

**Loaded Source Drivers**

file (see debug.go above)

**Loaded Database Drivers**

mysql (see debug.go above)

**Go Version**

```
$ go version
go version devel +99e4ddd053 Tue Dec 18 00:13:58 2018 +0000 darwin/amd64
```

No difference with Go 1.11.4.

**Comment by dhui** [comment]
My guess is that there's an issue w/ your [DSN](https://github.com/go-sql-driver/mysql#dsn-data-source-name). e.g. use `root@` instead if `root:@`.

Have you tried connecting using the mysql driver directly w/o `migrate`?

**Comment by dhui** [comment]
@fsouza Thanks for investigating and opening a PR to fix!
