### ISSUE TITLE
Cli README is inconsistent/outdated

### ISSUE THREAD

**Issue by tingtingr** [golang-migrate/migrate#154]
**Describe the Bug**
I was using migrate for my work project and it took me a while to understand that the instructions in READ is not correct. 

At line32
`$ go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate`
should be 
`$ go get -tags 'postgres' -u github.com/golang-migrate/migrate/v4`

and at
line 42
`$ go build -tags 'postgres' -ldflags="-X main.Version=$(git describe --tags)" -o $GOPATH/bin/migrate github.com/golang-migrate/migrate/cmd/migrate`

should be
`$ go build -tags 'postgres' -ldflags="-X main.Version=$(git describe --tags)" -o $GOPATH/bin/migrate github.com/golang-migrate//migrate/v4
`

**Steps to Reproduce**
1. run your library install
2. run your build
3. See error 
```
can't load package: package github.com/golang-migrate/migrate/cmd/migrate: cannot find package "github.com/golang-migrate/migrate/cmd/migrate" in any of:
[13:57:06]		.././src/github.com/golang-migrate/migrate/cmd/migrate (from $GOROOT)
[13:57:06]		.././src/github.com/golang-migrate/migrate/cmd/migrate (from $GOPATH)
```

**Expected Behavior**
Should run with no problem.

**Migrate Version**
v4.0.2, dev
Obtained by running: `migrate -version`

**Loaded Source Drivers**
Source drivers: file
Obtained by running: `migrate -help`

**Loaded Database Drivers**
Database drivers: mysql, stub
Obtained by running: `migrate -help`

**Go Version**
go version go1.11.4 darwin/amd64
Obtained by running: `go version`

**Stacktrace**
```
can't load package: package github.com/golang-migrate/migrate/cmd/migrate: cannot find package "github.com/golang-migrate/migrate/cmd/migrate" in any of:
		.././src/github.com/golang-migrate/migrate/cmd/migrate (from $GOROOT)
		.././src/github.com/golang-migrate/migrate/cmd/migrate (from $GOPATH)
```

**Additional context**

Problems could be fixed by changing the path
 `github.com/golang-migrate/migrate/cmd/migrate` 
to 
`github.com/golang-migrate/migrate/v4`

**Comment by dhui** [comment]
Are you using `migrate` as a CLI or Go library?

**Comment by tingtingr** [comment]
as CLI

**Comment by dhui** [comment]
The steps to build the `migrate` CLI are different than the setup steps for using `migrate` as a library.

I've verified that the steps to build the CLI are correct:
```shell
$ docker run -it --rm --entrypoint sh golang:1.11-alpine3.8
/go # apk add git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/6) Installing nghttp2-libs (1.32.0-r0)
(2/6) Installing libssh2 (1.8.0-r3)
(3/6) Installing libcurl (7.61.1-r1)
(4/6) Installing expat (2.2.5-r0)
(5/6) Installing pcre2 (10.31-r0)
(6/6) Installing git (2.18.1-r0)
Executing busybox-1.28.4-r2.trigger
OK: 19 MiB in 20 packages
/go # go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
/go # migrate -version
dev
/go # migrate
Usage: migrate OPTIONS COMMAND [arg...]
       migrate [ -version | -help ]

Options:
  -source          Location of the migrations (driver://url)
  -path            Shorthand for -source=file://path 
  -database        Run migrations against this database (driver://url)
  -prefetch N      Number of migrations to load in advance before executing (default 10)
  -lock-timeout N  Allow N seconds to acquire database lock (default 15)
  -verbose         Print verbose logging
  -version         Print version
  -help            Print usage

Commands:
  create [-ext E] [-dir D] [-seq] [-digits N] [-format] NAME
			   Create a set of timestamped up/down migrations titled NAME, in directory D with extension E.
			   Use -seq option to generate sequential up/down migrations with N digits.
			   Use -format option to specify a Go time format string.
  goto V       Migrate to version V
  up [N]       Apply all or N up migrations
  down [N]     Apply all or N down migrations
  drop         Drop everyting inside database
  force V      Set version V but don't run migration (ignores dirty state)
  version      Print current migration version

Source drivers: file
Database drivers: postgresql, stub, postgres
/go #
```

To use migrate as a library, I suggest you use a package manager (Go modules for Go 1.11.x and dep for Go 1.10.x). Since you're using Go 1.11.4, you should use [Go modules](https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more) (addition [docs](https://github.com/golang/go/wiki/Modules)). So `go mod tidy` or `go get -u github.com/golang-migrate/migrate/v4` should work.

You're also free to forgo package management and just use `go get` directly.

**Comment by dhui** [comment]
Closing due to lack of response
