### ISSUE TITLE
Pending migrations

### ISSUE THREAD

**Issue by blankenshipz** [golang-migrate/migrate#161]
Is there an easy way to know if there are migrations that have not yet been run against a database?

**Comment by dhui** [comment]
Using the CLI, `migrate version` will tell you which migration your DB is using.

**Comment by blankenshipz** [comment]
@dhui What i'd like is to know how that version compares with the version from the migrations in sources. 

e.g if I want to start a web server that's dependent on version 3 which exists locally but the database is still on version 2 it'd be nice to be able to do something like this:

```
# (exit non-zero with pending migraitons)
migrate --no-pending-migrations && start-my-web-service
```
