### ISSUE TITLE
Drop() does not work after https://github.com/golang-migrate/migrate/pull/150

### ISSUE THREAD

**Issue by herpiko** [golang-migrate/migrate#164]
**Describe the Bug**

I'm using migrate as lib. Drop() after initializing migrate instance does not work anymore.

**Steps to Reproduce**

```
	m, err := migrate.New(
		migrationPath,
		url)
	if err != nil {
		log.Fatal(err)
	}
	err = m.Drop()
	if err != nil && err.Error() != "no change" {
		log.Fatal(err)
	}
	err = m.Up()
	if err != nil && err.Error() != "no change" {
		log.Fatal(err)
	}

```

**Expected Behavior**

Before 4.2.3, Drop() was always work.

**Migrate Version**
e.g. v4.2.3

Obtained by running my unit test program that using migrate as lib.

**Loaded Source Drivers**
N/A

**Loaded Database Drivers**
postgres

**Go Version**
go version go1.11.1 linux/amd64

**Stacktrace**
```
MIGRATION_PATH=`pwd`/migrations/test go test
db_test.go:69: Migrating postgres://db:db@0.0.0.0:65432/testdb?sslmode=disable from file:///home/path/to/src/migrations/test
db_test.go:78: can't acquire lock
exit status 1
FAIL	xxx/yyy/zzz	0.169s
Makefile:15: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by dhui** [comment]
Can you provide the full test code?

Are you running `migrate` in a goroutine? Based on the error message, It looks like you're hitting the case where local lock is being hit. e.g. `database.ErrLocked` is returned if multiple goroutines are locking migrate. It doesn't seem like an issue where grabbing the Postgres advisory lock is failing.

**Comment by herpiko** [comment]
> Are you running migrate in a goroutine?

No.

@dhui Okay I'll provide the reproducible code ASAP.

**Comment by lukaspj** [comment]
I'm experiencing this issue, seeing:
```
tearing down existing database because messages.database.fresh is true
can't acquire lock
failed to tear down database
```

I'm running on a clean Postgresql instance running inside Kubernetes via Minikube, deployed from Helm.
The code I wrote, it's not a Minimal Working Example, but I wanted to keep everything:
https://gist.github.com/lukaspj/eee69764cca2b58bb58fc368e4658a00

**Comment by lukaspj** [comment]
It seems to happen in postgres.go line 328
```go
if err := p.ensureVersionTable(); err != nil {
```

Maybe some lock is not released previously or it might happen inside ensureVersionTable entirely.

**Comment by lukaspj** [comment]
My guess would be that the Lock is acquired in migrate.go:
https://github.com/golang-migrate/migrate/blob/f6d624c72965b470335efa45323ac929ba831e8f/migrate.go#L305

In the subsequent call to Drop, the database is still locked so when we call ensureVersionTable and it tries to lock the database it dies:
https://github.com/golang-migrate/migrate/blob/f6d624c72965b470335efa45323ac929ba831e8f/database/postgres/postgres.go#L328
