### ISSUE TITLE
Change Go-Bindata Reference?

### ISSUE THREAD

**Issue by pwelch** [golang-migrate/migrate#170]
**Describe the Bug**

README references an unmaintained version of [go-bindata](https://github.com/jteeuwen/go-bindata)

Consider changing to a version of go-bindata that is more maintained?

It looks like the forked version (https://github.com/kevinburke/go-bindata) is actively maintained and included in Homebrew. The maintainer mentions in [this thread](https://github.com/gofrs/help-requests/issues/7) they will be taking bug fixes.

**Comment by dhui** [comment]
> Consider changing to a version of go-bindata that is more maintained?

See: https://github.com/golang-migrate/migrate/pull/152#issuecomment-45388134
