### ISSUE TITLE
Support basics of seeding

### ISSUE THREAD

**Issue by metalmatze** [golang-migrate/migrate#177]
**Is your feature request related to a problem? Please describe.**
I am using migrate to set up the database with tables, but next I want to seed the database with some example data.

**Describe the solution you'd like**
As migrate already interfaces with all sources and databases, I would like to reuse the CLI and tool to just run another SQL file that creates some example data.

**Describe alternatives you've considered**
Run a completely separate tool. Maybe do a fork or side project CLI to this one, that only takes care of reading files that should be used to seed the database.

**Additional context**
After creating the initial database I want to simply populate the database with some more data.

**Comment by dhui** [comment]
You can seed data using a DB dump tool (e.g. `mysqldump`, `pg_dump`) etc.
Obviously, you'll need to provide the correct options to the DB dump tools and you may need to hand-edit some of the queries in the dump.

That being said, I'd suggest against seeding data if you're using the same migrations across your environments. e.g. Does the seed data belong in production?
I'd also suggest against maintaining separate migrations for each environment. I'd keep your environments as similar as possible so it's easier to manage and debug/reproduce issues.

**Comment by metalmatze** [comment]
Yup, probably it's the easiest to just use the database dump tool. I was just thinking, if we couldn't leverage some of the same underlying capabilities that _migrate_ already offers.

My idea was to have another folder next to the migrations (that are the same in my environments) with a few files that contain different seeds. Then the developer can simply choose which seed to run against the database. Something like `migrate seed -source file://database/seeds/development.sql -database postgres://...`.
But I agree that this is probably just wrapping tools that are already out there.

Feel free to close, if you don't have any more comments.
Thanks for brainstorming this quickly with me.

**Comment by dhui** [comment]
> My idea was to have another folder next to the migrations (that are the same in my environments) with a few files that contain different seeds.

You'll probably hit issues w/ this approach. As the schema changes over time, so will your seed data.
