### ISSUE TITLE
Gitlab source

### ISSUE THREAD

**Issue by bpatyi** [golang-migrate/migrate#181]
I'm working on a new Gitlab source, but after I build and run the command I get an error message.

`error: source driver: unknown driver gitlab (forgotten import?)`

How can I build the binary file so it contains the source?

**Comment by dhui** [comment]
It's hard to say w/o seeing your code, but my guesses are:
1. Missing internal build file: e.g. `internal/cli/build_gitlab.go`
1. Missing build tag in the `Makefile` or `go build` command

Also, please open a PR for this change 😉

**Comment by bpatyi** [comment]
I uploaded the code, but I couldn't try it. You can see it here: `https://github.com/hellowearemito/migrate/commit/5f1546e0ac62e4832d8e42ebd52f6c5a40563142`

I think I run the build command incorrectly. There is only one item in list of source (file), if I run the `go build ./...` command in `cmd/migrate/` path and I run the binary file.

**Comment by dhui** [comment]
> I think I run the build command incorrectly. There is only one item in list of source (file), if I run the go build ./... command in cmd/migrate/ path and I run the binary file.

Sounds like you're missing the build tag: `gitlab`
