### ISSUE TITLE
OrientDB support

### ISSUE THREAD

**Issue by lpil** [golang-migrate/migrate#19]
Hello! It'd be great to be able to use this tool with OrientDB https://orientdb.com

**Comment by dhui** [comment]
I'm not familiar w/ OrientDB, so I'm not the right person to write the migrate DB driver for it. But if anyone wants to give it a shot (driver should have tests with decent code coverage), I'd be happy to merge the changes in.

**Comment by lpil** [comment]
It has a fairly straightforward REST API I'd recommend using.

Depending on whether my project determines that we need such a tool I may have a go :)
