### ISSUE TITLE
Unable to make simple example working

### ISSUE THREAD

**Issue by leucos** [golang-migrate/migrate#190]
**Describe the Bug**

Code from README and documentation doesn't seem to work to create a simple migration.

**Steps to Reproduce**

Create `main.go`:

```
package main

import (
	"github.com/golang-migrate/migrate/v4"
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	_ "github.com/lib/pq"
)

func main() {
	m, err := migrate.New(
		"file://migrations",
		"postgres://user:pass@localhost:5432/database?sslmode=disable")
	if err != nil {
		panic(err)
	}
	if err := m.Up(); err != nil {
		panic(err)
	}
}
```

Create a migration directory (`mkdir migrations`) and add migrations inside:

`migrations/2019031301.up.sql`:
```
BEGIN;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS users (
        id uuid PRIMARY KEY,
        email varchar(255) NOT NULL,
        username varchar(255) NOT NULL
);
COMMIT;
```

`migrations/2019031301.down.sql`:
```
BEGIN;
DROP TABLE IF EXISTS users;
DROP EXTENSION IF EXISTS "uuid-ossp";
COMMIT;
```

Then run:

```
$ go run test.go
panic: first /home/user/project/migrations: file does not exist

goroutine 1 [running]:
main.main()
        /home/user/project/main.go:19 +0xa4
exit status 2
```

However, `schema_migrations` table is created in the database but is empty.
 
**Expected Behavior**

Migrations should happen.

**Migrate Version**

v4.2.5
```
go.mod:	github.com/golang-migrate/migrate/v4 v4.2.5
go.sum:github.com/golang-migrate/migrate/v4 v4.2.5 h1:L41P/diej/v1ip3MPpbNPrUu2MHQmvho4DKchKAPkEQ=
go.sum:github.com/golang-migrate/migrate/v4 v4.2.5/go.mod h1:zt+104di20bTWX9M3cCcERBkS/6mncciH5sAjcn6kBU=
```

**Loaded Source Drivers**

`file` only

**Loaded Database Drivers**

`postgres` only

**Go Version**

go version go1.12 linux/amd64

**Stacktrace**

N/A

**Additional context**

Beginner :D

**Comment by kmuratov** [comment]
It looks like I found the mistake.

You should change migration filenames, for example like this:
2019031301_init.up.sql
2019031301_init.down.sql

https://github.com/golang-migrate/migrate/blob/master/MIGRATIONS.md
> The ordering and direction of the migration files is determined by the filenames used for them. migrate expects the filenames of migrations to have the format:
> 
> {version}\_{title}.up.{extension}
> {version}\_{title}.down.{extension}

**Comment by dhui** [comment]
@kmuratov's comment looks correct

Please re-open if that's not the case
