### ISSUE TITLE
Apache Cassandra Error "gocql: unable to create session: unable to discover protocol version: dial tcp" with " connection refused"

### ISSUE THREAD

**Issue by Adron** [golang-migrate/migrate#192]
**Bug Description**

I have a basic migrations setup, where I have a bash file that executes the migrations passing in the following parameters against a docker container that has an Apache Cassandra node running on it. When executing against this particular node, I get the following error message.

``` bash
error: gocql: unable to create session: unable to discover protocol version: dial tcp 172.17.0.2:9042: connect: connection refused
```

The repo is located here that has the migrations/code in it: https://github.com/Adron/consist_migrations

The migrate command and switches I'm executing include the following.

``` bash
migrate \
 -source file://cassandra/ \
 -database cassandra://172.17.0.2:9042/consist?sslmode=disable down
```

**Steps to Reproduce**
1. My migrations are just a basic table creation in a pre-existing keyspace in Cassandra and database in PostgreSQL.
2. The command is:
``` bash
migrate \
 -source file://cassandra/ \
 -database cassandra://172.17.0.2:9042/consist?sslmode=disable down
```

**Expected Behavior**

I would expect the connection to be made and the migration to execute.

**Migrate Version**

Currently I have:

adron@budgiewudgie:~$ migrate -version
4.2.5-9-g14f26d8

But am about to clone the main repo and build it again, and work from it to try and resolve the issue myself.

**Loaded Source Drivers**
Source drivers: s3, github, go-bindata, godoc-vfs, gcs, file

**Loaded Database Drivers**
Database drivers: stub, cassandra, mongodb, mysql, postgres, spanner, redshift, clickhouse, cockroach, cockroachdb, crdb-postgres, postgresql

**Go Version**
adron@budgiewudgie:~$ go version
go version go1.11.5 linux/amd64

**Stacktrace**
Unfortunately N/A - is it available via the build command somehow, with a switch or such?

**Additional context**
I've tried this against a local Apache Cassandra node and also the containerized node using Docker to rule out networking disparities there. Both nodes are setup without auth to just work against.

**Comment by dhui** [comment]
Are you able to connect to Cassandra using gocql? e.g. write a test program to try to connect to your Cassandra cluster

**Comment by nekinie** [comment]
For future travelers, I was seeing the same issue until I wrapped everything in quotes.
```
migrate -source="file://migrations/" -database="cassandra://127.0.0.1:9042/platform?username=cassandra&password=cassandra" up
```

**Comment by KaitakuShiba** [comment]
If using Docker and want to access another container within app container, need to raise it by the container name because can't communicate on localhost. work for me,
```
$ migrate -database 'postgres://DB_USER:DB_PASS@CONTAINER_NAME:DB_PORT/DB_NAME?sslmode=disable' -path db/migrations up
```
