### ISSUE TITLE
Enhancement: Automatically split up multiple statements

### ISSUE THREAD

**Issue by mcandre** [golang-migrate/migrate#197]
I would like for golang-migrate to automatically split up any SQL statements within a migration script file, and send them one by one, so that the user does not have to enable multi statement options in their database client connections.

**Comment by dhui** [comment]
What's to be gained by splitting up SQL statements and instead of enabling the multi-statement option?

**Comment by mcandre** [comment]
Good question. I am by no means a SQL expert, but I wonder if multi-statement does contribute to some amount of SQL injection security risk?

**Comment by dhui** [comment]
Multi-statement support is easier to add to DB drivers with [multistmt](https://godoc.org/github.com/golang-migrate/migrate/database/multistmt).

**Comment by kiendt22-fsoft** [comment]
@dhui how can I intergrate multistmt to golang module?
