### ISSUE TITLE
Migrating got some error: can't acquire lock

### ISSUE THREAD

**Issue by darmawan01** [golang-migrate/migrate#199]
Hy everyone,
i need help.

i am trying to migrate my database but getting some error ` can't acquire lock`.

i am using, OS: mac os mojave.
thanks for your help.

```
base_test.go:79: Migrating postgres://db:db@localhost:65432/testdb?sslmode=disable from file:///Users/clouds/CitraOffice/cdl/oa/judel/migrations/test
base_test.go:88: can't acquire lock
exit status 1
```

**Comment by dhui** [comment]
Were you able to figure out the issue? Were the locking issues occuring at the DB level or at the Go level?

**Comment by darmawan01** [comment]
i am so sorry my fault, i am forgot to create down migrations.
