### ISSUE TITLE
Support templating in migration files

### ISSUE THREAD

**Issue by jbrisbin** [golang-migrate/migrate#20]
It would be better for us to not have to jump through hoops to get content of migration files templated so we can do things like per-tenant schemas etc... Go has a perfectly usable string templating library available OOTB and it would better for our workflow if the content of migrations could be string templates that use variables defined in the source url so we could host migration files in a GitHub repo and have external variables be replaced in the content before sending it to the driver. Currently files have to be string-replaced using some external tool which limits how we can use the migrate utility.

I'm not a Go guru but if pointed in the right direction I could probably hack a PR together that implements this generically for all sources.

**Comment by dhui** [comment]
Migration files should be written for the specific DB, so supporting templating in a migration file will not be supported.
See: https://github.com/golang-migrate/migrate/blob/master/MIGRATIONS.md#migration-content-format

However, if you insist on templating your migrations, I believe that Go migrations, if implemented, might help. e.g. use Go migrations to perform template substitution.
See issue: https://github.com/golang-migrate/migrate/issues/15
That being said, the whole point of tracking migrations is for consistency (e.g. reproducibility and rollback) and using templates undermines that.

**Comment by Bessonov** [comment]
See https://github.com/golang-migrate/migrate/pull/793
