### ISSUE TITLE
Migration Filename version can support yyyy_mm_dd_HHmmss?

### ISSUE THREAD

**Issue by YangChinFu** [golang-migrate/migrate#209]
Hi everyone 
I want to ask the migration filename version can support yyyy_mm_dd_HHmmss or yyyymmdd_HHmmss?

like
2019_04_22_085540_create_users_table.up.sql or 
20190422_085540_create_users_table.up.sql ?

**Comment by dhui** [comment]
You can customize the timestamp format. See `migrate create -h`

**Comment by dhui** [comment]
Also, you can find the supported migration filename format here: https://github.com/golang-migrate/migrate/blob/master/source/parse.go
