### ISSUE TITLE
Can't use key-value connection params in Go

### ISSUE THREAD

**Issue by Jake-Mok-Nelson** [golang-migrate/migrate#210]
**Describe the Bug**
Only supports URLs for golang but lib-pq supports both URLs and key=value parameters for the connection string.

Results in error: `invalid character " " in host name`

**Steps to Reproduce**
1. Run migrate with a "-database" value of "postgres://dbhost=127.0.0.1 dbname=localdb dbuser=username password=somepassword" up`
2. Get's a result of `2019/04/23 11:11:14 error: database: parse postgres://dbhost=127.0.0.1 dbname=localdb dbuser=username password=somepassword: invalid character " " in host name.`

**Expected Behavior**
Should consume the parameters in the connection string the same way lib-pq does in Go (Golang).

**Migrate Version**
v4.2.5

**Loaded Source Drivers**
Source drivers: file, s3, github, go-bindata, godoc-vfs, gcs

**Loaded Database Drivers**
Database drivers: mysql, postgresql, redshift, clickhouse, cockroachdb, crdb-postgres, postgres, spanner, stub, cassandra, cockroach, mongodb

**Go Version**
go1.11.2 darwin/amd64

**Additional context**
I can imagine that this may have been an actual design decision to simplify the tool rather than an issue, just thought I'd check if this was an oversight because it would be helpful if it supported both types of connection strings.

**Comment by dhui** [comment]
If you use the `migrate` as a library, you can create your own DB driver instance using `WithInstance()` and create the `*sql.DB` however you like. e.g. use a different [DSNs](https://en.wikipedia.org/wiki/Data_source_name) format

The CLI is designed to only support URL-formatted DSNs for simplicity and consistency. e.g. we need to support many DB drivers
