### ISSUE TITLE
Postgresql unix domain socket connection string?

### ISSUE THREAD

**Issue by dgellow** [golang-migrate/migrate#211]
**Describe the Bug**

Hi there. I'm trying to use migrate with a Postgres database listening to a unix domain socket. In the [documentation](https://github.com/golang-migrate/migrate/tree/master/database/postgres) of the postgres driver I found (emphasis is mine):

> The host to connect to. **Values that start with / are for unix domain sockets**.

Unfortunately I cannot make it work. I tried a bunch of variations of the connection string without success. Could you provide an example of a working syntax when using unix domain socket?

**Migrate Version**

Latest, built from master.

**Loaded Source Drivers**

Source drivers: file

**Loaded Database Drivers**

Database drivers: postgres, postgresql, stub

**Go Version**

go version go1.11.5 linux/amd64

**Comment by dhui** [comment]
What are some of the connection strings you've tried?
*Make sure you redact/replace any secrets*

Also, what's the error you're getting?

The migrate postgres db driver filters and passes the connection string to lib/pq. There could be a bug in how we filter the connection string params. https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters
Are you able to connect to your directly DB using lib/pq?

**Comment by WhileLoop** [comment]
There is a known issue in lib/pg. https://github.com/lib/pq/issues/796 ```postgres:///dbname?host=/var/run/postgresql/``` worked for me.
