### ISSUE TITLE
How to speed up spanner migrations

### ISSUE THREAD

**Issue by adamcohen** [golang-migrate/migrate#216]
**Describe the Bug**
I'm using the golang migrate library with `file` with `spanner` and have about 17 individual migration files.  I've noticed that each file takes anywhere from 7 seconds to 45 seconds to execute, so when I run all the migrations against a new database instance, it takes from 3.5 minutes to 5 minutes to execute them all.  If I condense them all into a single migration, it only takes 10 seconds for a complete migration.

Is there any way to speed up the migration process, other than combining all the migrations into a single file?

**Steps to Reproduce**
1. What do my migrations look like?
I have 17 migrations, the first one creates 8 tables, I have a few that add indexes, but the majority of the migrations simply add or drop table columns.

2. I ran migrate with the following options
```go
import (
	"fmt"
	"os"
	"time"

	"github.com/jinzhu/gorm"
	"github.com/mattes/migrate"
	_ "github.com/mattes/migrate/database/spanner"
	_ "github.com/mattes/migrate/source/file"

	log "github.com/sirupsen/logrus"
)

func migrateSpanner() {
  pathToMigrations := "db/migrations"

  fmt.Println(params.SpannerDatabaseAddress)
  m, err := migrate.New(
    fmt.Sprintf("file://%s", pathToMigrations),
    fmt.Sprintf("spanner://%s", params.SpannerDatabaseAddress),
  )
  if err != nil {
    log.Fatalf("Error encountered while creating new migration instance: '%v'", err)
    return
  }
  defer m.Close()

  startTime := time.Now()
  log.Infof("Starting migration at %v", startTime)
  if err = m.Up(); err != nil && err != migrate.ErrNoChange {
    if err == os.ErrNotExist {
      version, _, versionErr := m.Version()

      if versionErr != nil {
        log.Errorf("Received os.ErrNotExist error while running migrations: %v", err)
        log.Fatalf("Also encountered an error while trying to get the current database version from " +
          "the SchemaMigrations table: '%v'", versionErr)
      }

      log.Fatalf("Unable to find a local database migration with a filename matching the "+
        "remote database schema migration version: '%d'. Please make sure a local file with "+
        "this version exists in the '%s' directory.", version, pathToMigrations)
    } else {
      log.Fatalf("Error encountered while running migrations: '%v'", err)
    }
  }

  endTime := time.Now()
  log.Infof("Migration completed at %v. Elapsed time: %v", endTime, endTime.Sub(startTime))
}
```

**Expected Behavior**
Would be great if the migrations could execute faster

**Migrate Version**
`f2e5e31837ffec1092a0d9c0cb02fdb5a53065bf`

**Loaded Source Drivers**
`file`

**Loaded Database Drivers**
`spanner`

**Go Version**
go1.11.4 darwin/amd64

**Comment by dhui** [comment]
@adamcohen 
Thanks for reporting the issue.

Were you able to figure out a solution on your own?
I don't see anything obvious in `migrate` that would slow migrations down. e.g. `Spanner.Lock()` is a no-op and `Spanner.Run()` just runs the migration after splitting it into multiple statements.
I'm not familiar with Spanner schema migrations and didn't find anything helpful in [their docs](https://cloud.google.com/spanner/docs/schema-updates) about batching migrations. Was the DB under load when you were applying the migrations?

**Comment by adamcohen** [comment]
Thanks for the response @dhui. The only solution I was able to find is to periodically squash all the migrations into a single file. The DB wasn't under any load while applying the migrations.
