### ISSUE TITLE
source: URL cannot be empoty

### ISSUE THREAD

**Issue by rca0** [golang-migrate/migrate#217]
**Describe the Bug**
When i execute migrate command, i got error

**Steps to Reproduce**
1. I'm using migrate version v4.3.1
2. i got this error when i execute migrate command 
3. See error

![image](https://user-images.githubusercontent.com/38728338/57574097-00e44b80-7409-11e9-998a-8f3a0a058868.png)

**Expected Behavior**
Execute migration correctly.

**Migrate Version**
v3.4.1

**Loaded Source Drivers**
file

**Loaded Database Drivers**
postgresql 

**Go Version**
go1.11 linux/amd64

**Comment by rca0** [comment]
i solved the problem passing in this order:

`migrate -source file://migrations/ -database $DATABASE_URL?ssmode=disable force 9 up`

**Comment by dhui** [comment]
When using the migrate CLI, the options need to be specified before the command. See `migrate -h`
