### ISSUE TITLE
How to apply all migrations ignoring the version

### ISSUE THREAD

**Issue by Niondir** [golang-migrate/migrate#218]
**Is your feature request related to a problem? Please describe.**
I have a lot of migrations that are repeatable. It's a set of files that only contain functions with `create or replace function`. How to run them all every time, ignoring the version.

Do I have to load the files my self and run them with `m.Run(...)` or can I somehow utilize the file loader from this package?

**Comment by dhui** [comment]
`migrate` handles the bookkeeping for you. e.g. it tracks the last attempted migration version and whether or not it was successfully applied.

Assuming you've successfully created an instance of [Migrate](https://godoc.org/github.com/golang-migrate/migrate#Migrate), you can run [Up()](https://godoc.org/github.com/golang-migrate/migrate#Migrate.Up).

You can also use the [CLI](https://github.com/golang-migrate/migrate#cli-usage) to test and run migrations. I'd only use the CLI for development and emergency ops work (assuming you know what you're doing).
