### ISSUE TITLE
Viewing current state of DB in code

### ISSUE THREAD

**Issue by prats226** [golang-migrate/migrate#221]
**Is your feature request related to a problem? Please describe.**
If you look from schema perspective, migrations are essentially events which update schema over time and you get a view of current state of schema by adding all the migrations till now. However, it's very difficult to visualize current schema unless you have it in code at one place, like one file where all your schema declarations are.

One way is to maintain another file with along with migration where current schema structure is but it will be duplication of code and not a single source of truth. Also there might be inconstancies between two. Hence if there a file like this, it should be autogenerated from migrations.

The way django handles it is having entities in code as source of truth and based on change in them, generate migrations which is opposite approach.

**Describe the solution you'd like**
We can have a cli tool to generate one schema file from all migrations till now. So this file will be autogenerated hence no inconsistancies. There are similar design patterns I have seen with versioning tools like dep where you have one file where you list down dependencies etc and lock file is autogenerated which have complete state documented.

**Describe alternatives you've considered**
Currently we maintain migrations and another file with complete schema but you have to manage it in process like strict code reviews to avoid inconsistancie which is not foolproof

**Comment by dhui** [comment]
Not sure what you mean

**Comment by prats226** [comment]
> Not sure what you mean

Updated description

**Comment by dhui** [comment]
I still don't understand the problem you'd like solved. You can view the current schema in the DB directly.

There's no way for `migrate` to maintain it's version/view the "current schema" since migrations are treated as a blob. For more info, see: https://github.com/golang-migrate/migrate/blob/master/MIGRATIONS.md

`migrate` is not like Django since there's no ORM, so there are no models that can be used to automatically create schema migrations.

**Comment by asterikx** [comment]
> I still don't understand the problem you'd like solved. You can view the current schema in the DB directly.

Not all devs are allowed to access DBs. Still, they need to write application code against DBs. The problem to be solved: visualize the database schema that would result from running all migrations.

What this is asking for is generating models/schemas from applying migrations up to a specific point in time. I understand that there is no direct way for `migrate` to do this, and it might as well be out of scope. Still, I think it would be hugely useful and I'm not aware of any tool that does this.
