### ISSUE TITLE
migrate drop on mysql with foreign key constraints

### ISSUE THREAD

**Issue by ferdypruis** [golang-migrate/migrate#223]
**Describe the Bug**
When running "migrate drop" on a Mysql/MariaDB database that has a foreign key constraint between two tables, the action will fail if the table referenced by the constraint is dropped first..

While MySQL/MariaDB accepts `CASCADE` as an option to `DROP TABLE`, it is not actually implemented and does nothing.

**Steps to Reproduce**
1. Have a MySQL/MariaDB database with two tables, having the alphabetically last one depend on the former.
```sql
CREATE TABLE `a`  (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
);

CREATE TABLE `b`  (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  CONSTRAINT `b_id_a_id` FOREIGN KEY (`id`) REFERENCES `a` (`id`)
);
```
2. Run `migration drop` on this database
3. See error;
> Cannot delete or update a parent row: a foreign key constraint fails in line 0: DROP TABLE IF EXISTS `a` CASCADE

**Expected Behavior**
I would expect both tables to be dropped as would happen if `CASCADE` was actually implemented.

**Migrate Version**
4.2.5

**Loaded Source Drivers**
gcs, file, s3, github, go-bindata, godoc-vfs

**Loaded Database Drivers**
cockroach, cockroachdb, postgresql, spanner, stub, cassandra, clickhouse, mysql, postgres, redshift, crdb-postgres, mongodb

**Go Version**
go version go1.12 linux/amd64

**Additional context**
[MySQL docs on DROP TABLE](https://dev.mysql.com/doc/refman/8.0/en/drop-table.html);
> The RESTRICT and CASCADE keywords do nothing. They are permitted to make porting easier from other database systems.

[MariaDB docs on DROP TABLE](https://mariadb.com/kb/en/library/drop-table/);
>RESTRICT and CASCADE are allowed to make porting from other database systems easier. In MariaDB, they do nothing.

In MySQL/MariaDB, instead of using `CASCADE`, the checking for constraints can be (temporarily) disabled by changing the system variable `foreign_key_checks`; 
 https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_foreign_key_checks

This issue is fixable by executing a `SET FOREIGN_KEY_CHECKS = 0` before attempting to drop tables, though that would introduce a new bug allowing to delete tables which are referenced by views. This would be fixed if views would also be deleted, which currently are not, but should.

**Comment by ferdypruis** [comment]
Proposed fix;
https://github.com/ferdypruis/migrate/commit/00f551fff23fcc457849567402d8427de0a64516

Disables foreign key checks before attempting to drop all tables, and enable them when finished.

Flaws; 
- If enables FOREIGN_KEY_CHECKS even if they were already disabled. The old state should be stored in a variable and used to revert back to instead.
- Tables references by views can now be deleted, breaking those views. The proper fix would be to also drop views.

**Comment by dhui** [comment]
Thanks for reporting the issue!

> Dropping an index required by a foreign key constraint is not permitted, even with foreign_key_checks=0. The foreign key constraint must be removed before dropping the index. 

Not sure if the an index would be dropped as well with `SET FOREIGN_KEY_CHECKS = 0`.  e.g. I'm not sure if that statement in the docs only applies to `DROP INDEX`.

It's probably more complicated to figure out the relationship between tables and delete them in the proper order, so this big hammer solution seems like the best for now...

Feel free to open a PR!

**Comment by ferdypruis** [comment]
If a table contains a constraint and index, they will be dropped along with the table.
A table referenced by a constraint can not be dropped, unless `foreign_key_checks` is disabled. The referencing constraint will be dropped with it's table.

Disabling `foreign_key_checks` can break the integrity of a database, but this is not a problem because we are dropping everything.

**Comment by ferdypruis** [comment]
> Feel free to open a PR!
https://github.com/golang-migrate/migrate/pull/224
