### ISSUE TITLE
Concern in resolving migrations source folder when using the code as a package

### ISSUE THREAD

**Issue by qw4n7y** [golang-migrate/migrate#228]
*Objective*: my code is a module with internal migrations. I wanna to run migrations when using such module

*Problem*: when using filesystem as a migrations source i found no way to set neither relative or absolute path to migrations source folder

*Desired solution*: to have an ability to set migrations folder path as a relative to the file which runs migrations

*Quick workaround*: use Github source but thats not perfect

**Comment by dhui** [comment]
Have you tried using [go-bindata](https://github.com/golang-migrate/migrate/tree/master/source/go_bindata)?

Keep in mind that the go-bindata `migrate` uses is [outdated](https://github.com/golang-migrate/migrate/pull/152#issuecomment-45388134) but there's [work](https://github.com/golang-migrate/migrate/pull/144) to updated it.
