### ISSUE TITLE
unable to import 

### ISSUE THREAD

**Issue by jdaggula** [golang-migrate/migrate#233]
**Describe the Bug**
Not able to import using dep
**Steps to Reproduce**
1. dep ensure -add github.com/golang-migrate/migrate

**Expected Behavior**

**Migrate Version**
e.g. v3.4.0
Obtained by running: `migrate -version`

**Loaded Source Drivers**
e.g. s3, github, go-bindata, gcs, file
Obtained by running: `migrate -help`

**Loaded Database Drivers**
e.g. spanner, stub, clickhouse, cockroachdb, crdb-postgres, postgres, postgresql, redshift, cassandra, cockroach, mysql
Obtained by running: `migrate -help`

**Go Version**
e.g. go version go1.11 linux/amd64
Obtained by running: `go version`

**Stacktrace**
Please provide if available
[INFO]  Lock Diff Info:
[INFO]  
[INFO]  No versions of github.com/golang-migrate/migrate met constraints:
        v4.3.1: "github.com/golang-migrate/migrate" imports "github.com/golang-migrate/migrate/v4/database", which contains malformed code: unknown error for "github.com/golang-migrate/migrate/v4/database", if you get this error see https://github.com/golang/dep/issues/351
        v4.3.0: "github.com/golang-migrate/migrate" imports "github.com/golang-migrate/migrate/v4/database", which contains malformed code: unknown error for "github.com/golang-migrate/migrate/v4/database", if you get this error see https://github.com/golang/dep/issues/351
        v4.2.5: "github.com/golang-migrate/migrate" imports "github.com/golang-migrate/migrate/v4/database", which contains malformed code: unknown error for "github.com/golang-migrate/migrate/v4/database", if you get this error see https://github.com/golang/dep/issues/351
        v4.2.4: "github.com/golang-migrate/migrate" imports "github.com/golang-migrate/migrate/v4/database", which contains malformed code: unknown error for "github.com/golang-migrate/migrate/v4/database", if you get this error see https://github.com/golang/dep/issues/351
        v4.2.3: "github.com/golang-migrate/migrate" imports "github.com/golang-migrate/migrate/v4/database", which contains malformed code: unknown error for "github.com/golang-migrate/migrate/v4/database", if you get this error see https://github.com/golang/dep/issues/351
        master: "github.com/golang-migrate/migrate" imports "github.com/golang-migrate/migrate/v4/database", which contains malformed code: unknown error for "github.com/golang-migrate/migrate/v4/database", if you get this error see https://github.com/golang/dep/issues/351
[INFO]  ========================
[INFO]     Resolution Options   
[INFO]  ========================
[INFO]  0) Exit
[INFO]  1) Custom override
[INFO]  failed to handle solve conflicts: No versions of github.com/golang-migrate/migrate met constraints:
        v4.3.1: "github.com/golang-migrate/migrate" imports "github.com/golang-migrate/migrate/v4/database", which contains malformed code: unknown error for "github.com/golang-migrate/migrate/v4/database", if you get this error see https://github.com/golang/dep/issues/351
        v4.3.0: "github.com/golang-migrate/migrate" imports "github.com/golang-migrate/migrate/v4/database", which contains malformed code: unknown error for "github.com/golang-migrate/migrate/v4/database", if you get this error see https://github.com/golang/dep/issues/351
        v4.2.5: "github.com/golang-migrate/migrate" imports "github.com/golang-migrate/migrate/v4/database", which contains malformed code: unknown error for "github.com/golang-migrate/migrate/v4/database", if you get this error see https://github.com/golang/dep/issues/351
        v4.2.4: "github.com/golang-migrate/migrate" imports "github.com/golang-migrate/migrate/v4/database", which contains malformed code: unknown error for "github.com/golang-migrate/migrate/v4/database", if you get this error see https://github.com/golang/dep/issues/351
        v4.2.3: "github.com/golang-migrate/migrate" imports "github.com/golang-migrate/migrate/v4/database", which contains malformed code: unknown error for "github.com/golang-migrate/migrate/v4/database", if you get this error see https://github.com/golang/dep/issues/351
        master: "github.com/golang-migrate/migrate" imports "github.com/golang-migrate/migrate/v4/database", which contains malformed code: unknown error for "github.com/golang-migrate/migrate/v4/database", if you get this error see https://github.com/golang/dep/issues/351

**Additional context**

**Comment by dhui** [comment]
See: https://github.com/golang-migrate/migrate/issues/123 and related issues
