### ISSUE TITLE
migrate create with seq does not handle dot dir prefix

### ISSUE THREAD

**Issue by Oneymus** [golang-migrate/migrate#238]
**Describe the Bug**
When using the `create` subcommand with the `seq` flag, the command fails if `dir` begins with a `.`.

**Steps to Reproduce**
1. Create first migration:
```bash
mkdir test
migrate create -ext sql -dir ./test -seq first
```

2. Create second migration:
```bash
migrate create -ext sql -dir ./test -seq second
```

3. See error:
```
error: strconv.Atoi: parsing "test/000001": invalid syntax
```

**Expected Behavior**
`migrate create -seq` should create a second migration with the proper sequence number when `dir` begins with a `.`.

**Migrate Version**
`v4.4.0`

**Loaded Source Drivers**
```
Source drivers: gitlab, go-bindata, godoc-vfs, gcs, file, s3, github
```

**Loaded Database Drivers**
```
Database drivers: cassandra, crdb-postgres, postgres, stub, clickhouse, cockroach, cockroachdb, mongodb, mysql, postgresql, redshift, spanner, sqlserver
```

**Go Version**
```
go version go1.12.5 darwin/amd64
```

**Stacktrace**
Pretty sure it's this line: https://github.com/golang-migrate/migrate/blob/master/internal/cli/commands.go#L31

**Additional context**
`migrate create -seq` works just fine when `dir` does *not* begin with `.`.

**Comment by Oneymus** [comment]
Sorry for the default bug report. GitHub refreshed something on me because of its many new feature popups. Fixing!

**Comment by dhui** [comment]
Thanks for reporting the issue!

My guess is that `filepath.Glob()` returns the matches w/o the dot prefix. We should normalize both the `dir` arg and the matched filepaths before trimming the dir prefix to parse/determine the next migration sequence number.

**Comment by dhui** [comment]
This should be fixed in master now and will go out with the next release

**Comment by toqueteos** [comment]
Unfortunately the fix seems to not be compatible with Windows paths.

```
$ go version
go1.12.7 windows/amd64
$ migrate -version
4.5.0
$ rm -rf backend/migrations/
$ migrate create -seq -dir ./backend/migrations -ext sql create_accounts_table
$ migrate create -seq -dir ./backend/migrations -ext sql create_bots_table
error: strconv.Atoi: parsing "backend\\migrations\\000001": invalid syntax
```

**Comment by dhui** [comment]
Unfortunately, I don't have access to a windows machine, so won't be able to reproduce or fix the issue for windows. My guess is that the glob match needs to be cleaned before `strings.TrimPrefix()` [is called](https://github.com/golang-migrate/migrate/blob/v4.5.0/internal/cli/commands.go#L24).

Does using windows path separators work?
e.g.
```golang
$ migrate create -seq -dir .\\backend\\migrations -ext sql create_accounts_table
$ migrate create -seq -dir .\\backend\\migrations -ext sql create_bots_table
```

**Comment by toqueteos** [comment]
Nope, it doesn't work (with and without escaping backslashes):

```
$ migrate create -seq -dir .\\backend\\migrations -ext sql create_accounts_table
$ migrate create -seq -dir .\\backend\\migrations -ext sql create_bots_table
error: strconv.Atoi: parsing "backend\\migrations\\000001": invalid syntax

...

$ migrate create -seq -dir .\backend\migrations -ext sql create_accounts_table
$ migrate create -seq -dir .\backend\migrations -ext sql create_bots_table
error: strconv.Atoi: parsing "backend\\migrations\\000001": invalid syntax
```

I'll take a look and see if I can get it to work with Windows paths.

**Comment by dvaldivia** [comment]
This is still happening
