### ISSUE TITLE
postgresql function gen_random_uuid() does not exist

### ISSUE THREAD

**Issue by LieAlbertTriAdrian** [golang-migrate/migrate#248]
**Describe the Bug**

**Steps to Reproduce**
1. My migrations look like '...'
2. I ran migrate with the following options '....'
3. See error

**Expected Behavior**

**Migrate Version**
e.g. v3.4.0
Obtained by running: `migrate -version`

**Loaded Source Drivers**
e.g. s3, github, go-bindata, gcs, file
Obtained by running: `migrate -help`

**Loaded Database Drivers**
e.g. spanner, stub, clickhouse, cockroachdb, crdb-postgres, postgres, postgresql, redshift, cassandra, cockroach, mysql
Obtained by running: `migrate -help`

**Go Version**
e.g. go version go1.11 linux/amd64
Obtained by running: `go version`

**Stacktrace**
Please provide if available

**Additional context**

**Comment by dhui** [comment]
There are no references to `gen_random_uuid` in the `migrate` code base.

It looks like you're using a pgcrypto function and need it installed before you migrations use it.
