### ISSUE TITLE
Add `new` command for creating revisions

### ISSUE THREAD

**Issue by QuantumGhost** [golang-migrate/migrate#25]
Migrate does not provide `new` command for creating revisions right now, so developers have to create revisions manually, which is tedious and error prone.

I think that creating a new revision should be as simple as:
`migrate new -title "create-user-table" -source file://.migrations/versions -database postgres://localhost:5432`.

The command above creates two file in `./migrations/versions` named `$TIMESTAMP_$TITLE.up.sql` and `$TIMESTAMP_$TITLE.down.sql`, then users can write migration scripts in those files.

This could simplify process  for creating revisions and avoid nasty issues created by manually creating revision files.

**Comment by dhui** [comment]
I believe you're looking for the `create` command which is documented [here](https://github.com/golang-migrate/migrate/tree/master/cli) as well as in the `migrate` binary
