### ISSUE TITLE
Confusing documentation - How to install library...

### ISSUE THREAD

**Issue by ohenrik** [golang-migrate/migrate#251]
**Describe the Bug**
I am new to go and though dep ensure was the way to go. However it seems like the migrate package is not compatible with go dep.

So now for the real question. How do i install this? What command do i use? Could you please update the documentation so it is a bit friendlier to new gophers?

**Steps to Reproduce**
1. Be a noob
2. Try to get example 1 under "Use in your Go project" to work...

**Expected Behavior**
1. type `dep ensure` or `go get` 
2. My go program builds like a charm...

**Migrate Version**
v4??
Obtained by running: `migrate -version`

**Comment by ohenrik** [comment]
I got this working now. Firstly i had to run `go get` alone, however this caused the dependency lib/pg to be downloaded and stored in a global directory, which caused another bug:

`panic: sql: Register called twice for driver postgres`

Solved this by manually deleting the one installed by dep ensure.

**Comment by dhui** [comment]
`migrate` doesn't support `dep` for dependency management. We use Go modules.

**Comment by eleijonmarck** [comment]
@dhui could you give an example of how to install the binary using go modules?

I try to install via:
```
go get -u github.com/golang-migrate/migrate/v4
```

```
package github.com/golang-migrate/migrate/v4: cannot find package "github.com/golang-migrate/migrate/v4" in any of:
```

**Comment by dhui** [comment]
@eleijonmarck Are you trying to install the CLI or library?
For the CLI, see: https://github.com/golang-migrate/migrate/pull/257#pullrequestreview-270564997
If you're using migrate as a library, `go mod tidy` should work if you're using the correct import path.
