### ISSUE TITLE
'create' command action for using in Go project 

### ISSUE THREAD

**Issue by stobita** [golang-migrate/migrate#256]
**Is your feature request related to a problem? Please describe.**
We would like to create new migration file when we use this package in Golang project.

**Describe the solution you'd like**
Publishing `create` command action.

**Describe alternatives you've considered**
We think what to do is moving `create` action logic to public funtion on top level of package.

https://github.com/golang-migrate/migrate/blob/14a3bcdaa82ed4983bbe5ae6a0fb56843356420d/internal/cli/main.go#L117

**Additional context**

**Comment by dhui** [comment]
Could you describe your usecase in more detail?
e.g. Is there functionality that's missing in the current `create` command?
Programmatically creating migrations seems odd to me and scripting CLI usage is sufficient for most workflows.

**Comment by stobita** [comment]
When I create a CLI tool, I think that wrapping this library will simplify the development operation.

> Programmatically creating migrations seems odd to me and scripting CLI usage is sufficient for most workflows.

I wanted it because it was able to do with another library [another library](https://github.com/pressly/goose).
But I am also agree to what you say so I will close this issue if it does not fit with this project's policy.

**Comment by dhui** [comment]
Your current usecase isn't compelling enough to add Go programmatic support for the CLI actions/commands.
There's an [existing issue](https://github.com/golang-migrate/migrate/issues/242) around adding programmatic support for the CLI, so I'm closing this issue in favor of the existing one.
