### ISSUE TITLE
go mod tidy fails due to downstream Sirupsen/sirupsen issue

### ISSUE THREAD

**Issue by a-h** [golang-migrate/migrate#261]
**Describe the Bug**

When I run `go mod tidy` I get an error.

With `go version go1.12.7 darwin/amd64` I get an error message which doesn't describe the problem:

```
$ go mod tidy
go: finding github.com/docker/docker/api/types/image latest
go: finding github.com/docker/docker/api/types latest
go: finding github.com/docker/docker/api latest
go: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"
go: error loading module requirements
```

But as per https://github.com/golang/go/issues/33401 with `go version devel +2754118 Sun Aug 11 05:38:06 2019 +0000 darwin/amd64` I get a better error message which explains that the issue is probably the `dktest` import.

```
go: github.com/a-h/migrate-repro imports
        github.com/golang-migrate/migrate/v4/database/mysql tested by
        github.com/golang-migrate/migrate/v4/database/mysql.test imports
        github.com/dhui/dktest imports
        github.com/docker/docker/pkg/jsonmessage imports
        github.com/docker/docker/pkg/term imports
        github.com/docker/docker/pkg/term/windows imports
        github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod:
        module declares its path as: github.com/Sirupsen/logrus
                but was required as: github.com/sirupsen/logrus
```

Perhaps `dktest` should be updated to use a later version of Docker?

**Steps to Reproduce**

1. Check out https://github.com/a-h/migrate-repro outside of the GOPATH
2. Run `go mod tidy`
3. See error

**Expected Behavior**

I expected it to work without error.

**Migrate Version**

v4

**Loaded Source Drivers**
N/A

**Loaded Database Drivers**
mysql

**Go Version**

As above.

**Comment by dhui** [comment]
I'm unable to reproduce the issue using your repo (Thanks for creating it btw!)
```shell
$ git clone https://github.com/a-h/migrate-repro.git
Cloning into 'migrate-repro'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
$ cd migrate-repro/
$ ls
go.mod  go.sum  main.go
$ export GO111MODULE=on
$ go mod tidy
go: finding github.com/golang-migrate/migrate/v4 v4.5.0
go: finding github.com/welldigital/pharmacy v0.0.0-20190809084949-d52fe35d019d
go: github.com/welldigital/pharmacy@v0.0.0-20190809084949-d52fe35d019d: git fetch -f https://github.com/welldigital/pharmacy refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in  /go/pkg/mod/cache/vcs/35119d0c167aae40b460b33aab802fc553a0a5c411cf1cdd23dcd6f2ba05baab: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
go: error loading module requirements
$ 
```

I'm guessing that the github.com/welldigital/pharmacy repo is a private repo.

Also, I don't think the issue lies with dktest: https://github.com/dhui/dktest/blob/v0.3.1/go.mod#L19

**Comment by a-h** [comment]
Thanks for investigating, and sorry for wasting your time, it looks like I left a package in the go.mod while trying to create a minimal reproduction of the issue, when I remove that package it works fine. 🤦‍♂
