### ISSUE TITLE
MongoDB driver old/imported incorrectly, "connstring" package no longer exists

### ISSUE THREAD

**Issue by zikaeroh** [golang-migrate/migrate#263]
I encountered this message while testing things on `gotip` this morning:

```
	github.com/golang-migrate/migrate/v4/cmd/migrate imports
	github.com/golang-migrate/migrate/v4/internal/cli imports
	github.com/golang-migrate/migrate/v4/database/mongodb imports
	github.com/mongodb/mongo-go-driver/x/network/connstring: module github.com/mongodb/mongo-go-driver@latest (v1.1.0) found, but does not contain package github.com/mongodb/mongo-go-driver/x/network/connstring
```

migrate uses the `github.com/mongodb/mongo-go-driver/x/network/connstring` package, however, the driver's repo states that the `/x/` directory is unstable and can change. It has changed, and the `connstring` package has been moved to `/x/mongo/driver/connstring` as of this morning's release, `v1.1.0`. migrate's `go.mod` asks for `v0.3.0`, but since the latest is `v1.1.0`, MVS is likely to select it if someone updates their dependencies or pulls in something that uses v1.1.0, and will then hit this breakage.

Additionally, this library isn't supposed to be imported via its github URL at all; it should be imported as the vanity path `go.mongodb.org/mongo-driver/...`, as per the README and its own internal imports. (This has apparently been true for a while, so I'm surprised I've had v1.0.4 in my `go.mod` for a good while without issue; probably because the migrate mongo driver never got built.)

Forgive me for deleting the template, but I didn't think it was worth it when this isn't strictly a bug in migrate itself. I don't use this driver, but its changes will still affect me.

**Comment by dhui** [comment]
Are you importing the mongo db driver? If so, what version do you have pinned?

My understanding of MVS is that it'll only select the the latest from the same major version number.

Related issue: https://github.com/golang-migrate/migrate/issues/237

**Comment by zikaeroh** [comment]
I do not import it directly, however, I often use `go get -d -t -u ./...` to update everything, including indirect dependencies (as inadvisable as that may be). I currently have v1.0.4 in my `go.mod`. It's very likely that I would have had issues already if I were actually using the mongo driver, but since it was indirect (and never actually compiled in), I never actually had an issue until the package stopped existing. The github.com vs go.monogodb.org difference may also play in this.

v0 and v1 versions are always seen as compatible under MVS. Only in v2+ do things become incompatible and require semantic versioned imports. If you have v0.3.0 and do an update, Go will bring you to v1.1.0.

I'm happy to contribute a PR which updates the mongo driver, if only to fix upgrade/build issues (since I don't actually use it). I tried my hand at doing the update/path replacement, but did encounter some changes in the driver that require a bit more care than a 5 minute string replacement. 😄 

For reference, my project is here: https://github.com/hortbot/hortbot

I use migrate as both a library and a CLI tool (using gobin).

**Comment by dhui** [comment]
If you could update the mongodb driver to the latest version, that'd be very much appreciated! The existing test coverage should help with updating the driver.
