### ISSUE TITLE
postgres: ensureVersionTable() is a little more brittle with BDR than mattes/migrate

### ISSUE THREAD

**Issue by ansel1** [golang-migrate/migrate#266]
**Describe the Bug**
postgres BDR will not allow any DDL statement unless the entire cluster is up and healthy.  This includes CREATE TABLE IF NOT EXISTS statements.  So if executing the migrate tool against a BDR database where some nodes are not up, the migrate tool will always fail in ensureVersionTable().

In mattes/migrate, ensureVersionTable() succeeds even when the BDR cluster is unhealthy, because it used to run two queries: 1. a read query to see if the schema_migrations table exists (not a DDL statement, will succeed even if the BDR cluster is unhealthy), then 2. CREATE TABLE only when needed.

It would be odd to run migrate against a database in this state, because if there were any migrations to run, the migrations themselves would likely also fail.  But in our system, our microservices run migrate every time their containers boot up.  In unhealthy BDR clusters, typically, there are no pending migrations to run (because we are not typically in the middle of a system upgrade at the same time as dealing with a cluster outage), so with mattes/migrate, our `migrate` call is a no-op, and the service proceeds to boot up.

I was wondering if the maintainers would be amenable to PR which adds the `SELECT COUNT(1) FROM information_schema.tables WHERE table_name = $1 AND table_schema = (SELECT current_schema()) LIMIT 1` query back into ensureVersionTable(), and avoids the "CREATE TABLE" statement when unnecessary.

**Migrate Version**
v4.5.0

**Comment by dhui** [comment]
The postgres driver only supports the standard postgres implementation. Feel free to fork the postgres driver and create a postgres-bdr that handles postgres-bdr specific needs.

**Comment by testtest959** [comment]
+1 I have a database where one service only queries the database version and doesn't have permissions to do `CREATE` queries. As a result, that user cannot tell if the schema it is operating on has done a migration before, and if it has, what the current version is

**Comment by dhui** [comment]
Well, I'm a year and a half wiser and am open to a simple check before running `CREATE TABLE`. Feel free to open a PR!
