### ISSUE TITLE
Error parsing query params in DSN

### ISSUE THREAD

**Issue by mitchellh** [golang-migrate/migrate#272]
**Describe the Bug**
Certain query parameters in the DSN are not being parsed, example: 

    "mysql://root:root@tcp(localhost:3306)/dev?x-migrations-table=foo"

Causes an error:

    error: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-migrations-table=foo' at line 1

**Steps to Reproduce**

1. Create any migrations
2. Use the MySQL driver with a `x-migrations-table` query param set
3. See error

**Expected Behavior**
Should work!

**Migrate Version**
`dev` -- running from latest master, but I tried every version back to 4.1 and still error.

Weirdly the version I built locally works just fine but I'm not sure what commit it was built from. If I rebuild from my local `master`, it no longer works.

**Loaded Source Drivers**
```
Source drivers: file
```

**Loaded Database Drivers**
```
Database drivers: mysql, stub
```

**Go Version**
Currently 1.12.9 but it wasn't when I built the one that works.

**Comment by mitchellh** [comment]
Further details:

Docker image tag `v4.5.0` works, but `v4.6.0` doesn't.

**Comment by dhui** [comment]
Thanks for reporting!

I believe this is an issue with connection params not being filtered out before being passed to the driver.
https://github.com/golang-migrate/migrate/blob/v4.6.0/database/mysql/mysql.go#L178
https://github.com/go-sql-driver/mysql/blob/v1.4.1/connection.go#L53

I may not have time to fix the issue and write the proper tests for a few days. In the meanwhile, if you're encountering this issue, you'll need to use the right combination of Go version and migrate version... 😒 

However, I can review a PR more quickly though! Was thinking about extracting `x-*` params into its own `map[string]string`.

**Comment by dhui** [comment]
I found a couple hrs to fix the issue and add tests. I should have a new release out in ~24 hrs.

**Comment by dhui** [comment]
Addressed in: [v4.6.1](https://github.com/golang-migrate/migrate/releases/tag/v4.6.1)

**Comment by mitchellh** [comment]
Thank you! I'll test it out soon.
