### ISSUE TITLE
Cannot connect to postgresql via unix socket

### ISSUE THREAD

**Issue by wttw** [golang-migrate/migrate#275]
It isn't possible to use the migrate CLI tool to connect to a postgresql database using a unix socket.

(This means that the common dev setup where the user doesn't have a password and uses peer authentication doesn't work.)

**Steps to Reproduce**

```
$ migrate -database postgres://steve@/dist -path db up
error: pq: password authentication failed for user "steve"

$ migrate -database postgres://steve@/var/run/postgresql:5432/dist -path db up
error: pq: password authentication failed for user "steve"

$ migrate -database postgres://steve@%2fvar%2frun%2fpostgresql:5432/dist -path db up
error: parse postgres://steve@%2fvar%2frun%2fpostgresql:5432/dist: invalid URL escape "%2f"

$ migrate -database "postgresql:dbname=dist host=/var/run/postgresql" -path db up
error: pq: unrecognized configuration parameter "postgresql:dbname"
```

**Expected Behavior**
The app connects to postgresql.

Compare with

```
$ psql postgres://steve@%2fvar%2frun%2fpostgresql:5432/dist
psql (11.5 (Ubuntu 11.5-1.pgdg19.04+1))
Type "help" for help.

dist=# 

$ psql "host=/var/run/postgresql dbname=dist"
psql (11.5 (Ubuntu 11.5-1.pgdg19.04+1))
Type "help" for help.

dist=# 
```

**Migrate Version**
"dev"

git describe says v4.6.0, e5b4be77716e02d32cdaf98a2982cfd6c0dd680c

**Loaded Database Drivers**
postgres, postgresql, stub

**Go Version**
go1.12.7 linux/amd64

**Additional context**

This is caused by known issues with github.com/lib/pq and net/url interacting with a design choice in migrate.

lib/pq [doesn't seem to be able to handle unix sockets using the uri connect syntax](https://github.com/lib/pq/issues/645), as net/url doesn't handle URL escaped slashes in the hostname.

The workaround for the bug in lib/pq is to use the keyword/value style of connection string instead of the uri. But that can't be used here, as migrate only supports uri-style net/url parseable connection strings.

**Comment by wttw** [comment]
This is a usable workaround:

```
$ migrate -database 'postgres://steve@/dist?host=/var/run/postgresql' -path db up
```

**Comment by dhui** [comment]
Looks like this is an issue with `pq`: https://github.com/lib/pq/issues/796
We're doing minimal parsing of the URL before sending it to `pq`.

https://play.golang.org/p/HV6gDmSrBJL
In case the playground disappears, the code and output is below:
```go
package main

import (
	"fmt"

	"github.com/lib/pq"
)

func main() {
	urls := []string{
		"postgres://steve@/dist",
		"postgres://steve@/var/run/postgresql:5432/dist",
		"postgres://steve@%2fvar%2frun%2fpostgresql:5432/dist",
		"postgresql:dbname=dist host=/var/run/postgresql",
		"postgres://steve@/dist?host=/var/run/postgresql",
	}

	for _, url := range urls {
		if connStr, err := pq.ParseURL(url); err == nil {
			fmt.Println(url, "=>", connStr)
		} else {
			fmt.Println("Error parsing URL:", err)
		}
	}
}
```

Output:
```
postgres://steve@/dist => dbname=dist user=steve
postgres://steve@/var/run/postgresql:5432/dist => dbname=var/run/postgresql:5432/dist user=steve
Error parsing URL: parse postgres://steve@%2fvar%2frun%2fpostgresql:5432/dist: invalid URL escape "%2f"
postgresql:dbname=dist host=/var/run/postgresql => 
postgres://steve@/dist?host=/var/run/postgresql => dbname=dist host=/var/run/postgresql user=steve
```
