### ISSUE TITLE
Can you please release patch version after remove debug output

### ISSUE THREAD

**Issue by lkebin** [golang-migrate/migrate#280]
When I upgrade to v4.6.1, migrate up will have unexpected output content.

https://github.com/golang-migrate/migrate/blob/0064ee83cffe697c868421e41d873eb068fb7d17/database/mysql/mysql.go#L194-L200

I found this out already removed in this commit, but why not release a patch version for that ?
https://github.com/golang-migrate/migrate/commit/0601111d8849134f00b47c58372ca50d358ed3bd

**Comment by L-P** [comment]
Please note that this leaks passwords to stdout and thus deserves a quick release.

**Comment by dhui** [comment]
Fixed in [v4.6.2](https://github.com/golang-migrate/migrate/releases/tag/v4.6.2)
