### ISSUE TITLE
Document how to use rakyll/statik with golang-migrate/migrate

### ISSUE THREAD

**Issue by fharding1** [golang-migrate/migrate#286]
Hello! There are many more ways to use the go-bindata driver than with just go-bindata, so it might be good to document an example of that, such as using statik. Here's an example:

```go
	statikFS, err := fs.New()
	if err != nil {
		return nil, fmt.Errorf("unable to access statik data: %w", err)
	}

	var assetNames []string
	fs.Walk(statikFS, "/", func(path string, info os.FileInfo, err error) error {
		if !info.IsDir() {
			assetNames = append(assetNames, info.Name())
		}

		return nil
	})

	s := bindata.Resource(assetNames,
		func(name string) ([]byte, error) {
			return fs.ReadFile(statikFS, filepath.Join("/", name))
		})
```

**Comment by dhui** [comment]
Seems like statik implements the `http.FileSystem` interface.
There's stalled work to integrate `http.FileSystem` support for as a migration source:
* https://github.com/golang-migrate/migrate/pull/144
* https://github.com/golang-migrate/migrate/pull/163

**Comment by dhui** [comment]
Closing this since it doesn't make sense to document or reference every implementation of `http.FileSystem`
