### ISSUE TITLE
migrate up erroring out with sslmode query

### ISSUE THREAD

**Issue by aronhoyer** [golang-migrate/migrate#290]
**Describe the Bug**
When trying to run a migration, I get an error that "no matches are found".

**Steps to Reproduce**
1. One up and down SQL file
2. `migrate -database postgres://localhost/database?sslmode=disable -path db/migrations up`
3.  See error

**Expected Behavior**
Migration to be successful.

**Migrate Version**
v4.6.2

**Loaded Source Drivers**
file, s3, github, github-ee, gitlab, go-bindata, godoc-vfs, gcs

**Loaded Database Drivers**
crdb-postgres, postgres, redshift, spanner, clickhouse, cockroachdb, mongodb, mysql, postgresql, sqlserver, stub, cassandra, cockroach

**Go Version**
go1.13 darwin/amd64

**Stacktrace**
`zsh: no matches found: postgres://localhost/database?sslmode=disable`

**Comment by jmramos02** [comment]
Currently experiencing this too. actually, adding any paramters after the database name returns the error too. also on postgres.

**Comment by jmramos02** [comment]
okay, i kinda figure it out. the issue is not with the migration library. Something to do with ZSH. `https://github.com/robbyrussell/oh-my-zsh/issues/31`

What i did was to enclose the URL with double quotes

`migrate -source file://migrations -database "postgres://localhost/database?sslmode=disable" up 2`

Hope this helps!

**Comment by aronhoyer** [comment]
that helped! thanks 😄

**Comment by dhui** [comment]
Looks like the issue has been resolved

**Comment by keepchen** [comment]
- **Base usage for mysql**

```shell
migrate -source file://migrations -database "mysql://user:password@tcp(localhost:3306)/example" up
```

- **Base usage for postgres**

```shell
migrate -source file://migrations -database postgres://user:password@localhost:5432/example up
```
