### ISSUE TITLE
Syntax check

### ISSUE THREAD

**Issue by mcandre** [golang-migrate/migrate#291]
Please provide a command line flag for performing a syntax check of all migration scripts, without executing the statements, in order to catch corrupting migrations before they break the database.

**Comment by mcandre** [comment]
As a workaround, I am running a Go based SQL validator against my `migrations/` directory.

https://github.com/mcandre/prql

**Comment by dhui** [comment]
This isn't a goal of the project. There are also multiple issues with doing this:
1. Migrations are treated as opaque blobs. Parsing the migrations goes against this
2. IDK if all DBs support validating a query. e.g. `ANALYZE`/`EXPLAIN`
    * If the DB isn't validating the query, you're just linting the migration, not actually validating it.

Also, you should be testing your migrations while developing them, so IDK how much value there is in adding a validator in migrate. You're probably better off running the linter in your editor.
