### ISSUE TITLE
Doesn't work on Windows as `schemeFromUrl` Incorrectly Uses `net/url` to check Scheme

### ISSUE THREAD

**Issue by seenickcode** [golang-migrate/migrate#292]
This library doesn't work on Windows, as `schemeFromUrl` Incorrectly Uses `net/url` to check Scheme. 

Example:

`schemeFromUrl("file://C:\Users\myuser\Documents\myproject\migrations")` throws an error of `invalid port`, because this is not a valid URL. 

Solution:

Use `path/filepath` instead.

**Comment by dhui** [comment]
We can't use `path/filepath` since sources and dbs are specified in URI format. How are you getting this error? It may help if you escape the `:` character. See: https://github.com/golang-migrate/migrate#database-urls which also applies to source urls.

**Comment by raynjamin** [comment]
@seenickcode I just started using the package and found myself thinking the same thing. After some pain, I came up with the following: 

```
p, err := filepath.Abs("..")
	p = filepath.ToSlash(p)
	p = path.Join(p, "migrations")

	m, err := migrate.NewWithDatabaseInstance(
		fmt.Sprintf("file://%s", p),
		"postgres", driver)
```

`filepath.ToSlash(p)` converts the `C:\` to `C:/`, then you just preface it with the file scheme (with two forward slashes) and it seems to work.

**Comment by dhui** [comment]
Closing since @raynjamin's snippet seems to fix the issue for everyone.

Any fix to the file source driver would be appreciated. Don't forget to add tests!

**Comment by Bearbite** [comment]
Here is my solution based on @raynjamin's comment for Windows OP:

DB_MIGRATION_DIR_PATH is the relative path from the project's root. It contains a path like this: dist\migrations

```go
p, err := filepath.Abs(os.Getenv("DB_MIGRATION_DIR_PATH"))
p = filepath.ToSlash(p)
...
m, err := migrate.NewWithDatabaseInstance(fmt.Sprintf("file://%s", p), "postgres", driver)
```
