### ISSUE TITLE
cannot find package "github.com/golang-migrate/migrate/v4/cmd/migrate"

### ISSUE THREAD

**Issue by tiagomelo** [golang-migrate/migrate#296]
I have a `Makefile` that I'm using to run migrations. I'm not being able to correctly download the package.

**Steps to Reproduce**
1. `go install -tags mysql github.com/golang-migrate/migrate/v4/cmd/migrate`
2. error: 
```
go install -tags mysql github.com/golang-migrate/migrate/v4/cmd/migrate
can't load package: package github.com/golang-migrate/migrate/v4/cmd/migrate: cannot find package "github.com/golang-migrate/migrate/v4/cmd/migrate" in any of:
	/usr/local/go/src/github.com/golang-migrate/migrate/v4/cmd/migrate (from $GOROOT)
	/go/src/github.com/golang-migrate/migrate/v4/cmd/migrate (from $GOPATH)
```

**Expected Behavior**
Be able to download the package and use `migrate` CLI.
**Migrate Version**
N/A

**Loaded Source Drivers**
N/A

**Loaded Database Drivers**
N/A

**Go Version**
go version go1.13.1 linux/amd64
**Stacktrace**
```
mysql_migration | can't load package: package github.com/golang-migrate/migrate/v4/cmd/migrate: cannot find package "github.com/golang-migrate/migrate/v4/cmd/migrate" in any of:
mysql_migration | 	/usr/local/go/src/github.com/golang-migrate/migrate/v4/cmd/migrate (from $GOROOT)
mysql_migration | 	/go/src/github.com/golang-migrate/migrate/v4/cmd/migrate (from $GOPATH)
```

**Additional context**

**Comment by dhui** [comment]
Closing in favor of: https://github.com/golang-migrate/migrate/pull/257

To isolate environment differences, are you able to reproduce the issue in a docker container?
Please respond in the linked PR.
