### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by JamesPSheldon** [golang-migrate/migrate#303]
**Describe the Bug**
When trying to `go get -u github.com/golang-migrate/migrate/v4/cmd/migrate/` the download fails due to a broken dependency.

**Steps to Reproduce**
Run `go get -u github.com/golang-migrate/migrate/v4/cmd/migrate/`

**Go Version**
go version go1.13 darwin/amd64

**Stacktrace**

go get -u github.com/golang-migrate/migrate/v4/cmd/migrate/
                                                                                                             
go: finding github.com/golang-migrate/migrate/v4 v4.7.0
go: downloading github.com/golang-migrate/migrate/v4 v4.7.0
go: extracting github.com/golang-migrate/migrate/v4 v4.7.0
go: downloading github.com/kshvakov/clickhouse v1.3.5
go: downloading github.com/aws/aws-sdk-go v1.17.7
go: downloading github.com/nakagami/firebirdsql v0.0.0-20190310045651-3c02a58cfed8
go: downloading go.mongodb.org/mongo-driver v1.1.0
go: downloading google.golang.org/genproto v0.0.0-20190425155659-357c62f0e4bb
go: extracting github.com/kshvakov/clickhouse v1.3.5
go: extracting github.com/nakagami/firebirdsql v0.0.0-20190310045651-3c02a58cfed8
go: downloading github.com/golang/protobuf v1.3.1
go: downloading github.com/gocql/gocql v0.0.0-20190301043612-f6df8288f9b4
go: downloading github.com/cockroachdb/cockroach-go v0.0.0-20181001143604-e0a95dfd547c
go: extracting github.com/cockroachdb/cockroach-go v0.0.0-20181001143604-e0a95dfd547c
go: extracting github.com/gocql/gocql v0.0.0-20190301043612-f6df8288f9b4
go: downloading github.com/xanzy/go-gitlab v0.15.0
go: extracting github.com/golang/protobuf v1.3.1
go: downloading github.com/shopspring/decimal v0.0.0-20180709203117-cd690d0c9e24
go: extracting github.com/xanzy/go-gitlab v0.15.0
go: downloading google.golang.org/grpc v1.20.1
go: extracting github.com/shopspring/decimal v0.0.0-20180709203117-cd690d0c9e24
go: downloading go.opencensus.io v0.21.0
go: extracting google.golang.org/genproto v0.0.0-20190425155659-357c62f0e4bb
go: extracting go.mongodb.org/mongo-driver v1.1.0
go: extracting google.golang.org/grpc v1.20.1
go: extracting go.opencensus.io v0.21.0
go: downloading golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: extracting golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: downloading google.golang.org/api v0.4.0
go: downloading github.com/jackc/pgx v3.2.0+incompatible
go: downloading gitlab.com/nyarla/go-crypt v0.0.0-20160106005555-d9a5dc2b789b
go: downloading github.com/mattn/go-sqlite3 v1.10.0
go: extracting gitlab.com/nyarla/go-crypt v0.0.0-20160106005555-d9a5dc2b789b
go: downloading github.com/golang/snappy v0.0.1
go: extracting github.com/jackc/pgx v3.2.0+incompatible
go: downloading github.com/kardianos/osext v0.0.0-20190222173326-2bc1f35cddc0
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading google.golang.org/appengine v1.5.0
go: extracting github.com/hashicorp/golang-lru v0.5.1
go: extracting gopkg.in/inf.v0 v0.9.1
go: extracting github.com/kardianos/osext v0.0.0-20190222173326-2bc1f35cddc0
go: extracting github.com/golang/snappy v0.0.1
go: downloading github.com/cznic/mathutil v0.0.0-20180504122225-ca4c9f2c1369
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: extracting github.com/mattn/go-sqlite3 v1.10.0
go: extracting google.golang.org/appengine v1.5.0
go: extracting github.com/cznic/mathutil v0.0.0-20180504122225-ca4c9f2c1369
go: extracting github.com/googleapis/gax-go/v2 v2.0.4
go: extracting github.com/pkg/errors v0.8.1
go: extracting github.com/google/go-github v17.0.0+incompatible
go: downloading github.com/hailocab/go-hostpool v0.0.0-20160125115350-e80d13ce29ed
go: downloading golang.org/x/tools v0.0.0-20190425222832-ad9eeb80039a
go: extracting github.com/hailocab/go-hostpool v0.0.0-20160125115350-e80d13ce29ed
go: downloading golang.org/x/text v0.3.2
go: extracting github.com/aws/aws-sdk-go v1.17.7
go: extracting golang.org/x/tools v0.0.0-20190425222832-ad9eeb80039a
go: downloading golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: downloading github.com/go-stack/stack v1.8.0
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: extracting google.golang.org/api v0.4.0
go: extracting github.com/go-stack/stack v1.8.0
go: extracting github.com/hashicorp/go-multierror v1.0.0
go: extracting golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: downloading github.com/cznic/ql v1.2.0
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: extracting github.com/xdg/stringprep v1.0.0
go: extracting github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: extracting github.com/cznic/ql v1.2.0
go: downloading github.com/hashicorp/errwrap v1.0.0
go: extracting github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/cznic/golex v0.0.0-20170803123110-4ab7c5e190e4
go: extracting github.com/cznic/golex v0.0.0-20170803123110-4ab7c5e190e4
go: downloading github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: extracting golang.org/x/text v0.3.2
go: extracting github.com/jmespath/go-jmespath v0.0.0-20180206201540-c2b33e8439af
go: downloading github.com/cznic/strutil v0.0.0-20171016134553-529a34b1c186
go: extracting github.com/cznic/strutil v0.0.0-20171016134553-529a34b1c186
go: downloading github.com/cznic/lldb v1.1.0
go: extracting github.com/cznic/lldb v1.1.0
go: downloading github.com/cznic/internal v0.0.0-20180608152220-f44710a21d00
go: extracting github.com/cznic/internal v0.0.0-20180608152220-f44710a21d00
go: downloading github.com/cznic/sortutil v0.0.0-20150617083342-4c7342852e65
go: extracting github.com/cznic/sortutil v0.0.0-20150617083342-4c7342852e65
go: downloading github.com/edsrzf/mmap-go v0.0.0-20170320065105-0bce6a688712
go: downloading github.com/cznic/fileutil v0.0.0-20180108211300-6a051e75936f
go: downloading github.com/cznic/zappy v0.0.0-20160723133515-2533cb5b45cc
go: extracting github.com/edsrzf/mmap-go v0.0.0-20170320065105-0bce6a688712
go: extracting github.com/cznic/fileutil v0.0.0-20180108211300-6a051e75936f
go: extracting github.com/cznic/zappy v0.0.0-20160723133515-2533cb5b45cc
go: downloading github.com/cznic/b v0.0.0-20180115125044-35e9bbe41f07
go: extracting github.com/cznic/b v0.0.0-20180115125044-35e9bbe41f07
go: finding golang.org/x/oauth2 latest
go: finding google.golang.org/appengine v1.6.5
go: finding github.com/cznic/internal latest
go: finding golang.org/x/sync latest
go: finding github.com/pkg/errors v0.8.1
go: finding go.mongodb.org/mongo-driver v1.1.3
go: finding github.com/hailocab/go-hostpool latest
go: finding golang.org/x/tools latest
go: finding cloud.google.com/go v0.48.0
go: finding google.golang.org/api v0.14.0
go: finding golang.org/x/text v0.3.2
go: finding golang.org/x/net latest
go: finding github.com/golang/snappy v0.0.1
go: finding github.com/cznic/sortutil latest
go: finding github.com/google/go-querystring v1.0.0
go: finding github.com/jackc/pgx v3.6.0+incompatible
go: finding go.opencensus.io v0.22.2
go: finding github.com/cznic/ql v1.2.0
go: finding github.com/go-sql-driver/mysql v1.4.1
go: finding github.com/cznic/mathutil latest
go: finding github.com/shopspring/decimal latest
go: finding github.com/google/go-github v17.0.0+incompatible
go: finding google.golang.org/grpc v1.25.1
go: finding google.golang.org/genproto latest
go: finding golang.org/x/sys latest
go: finding github.com/edsrzf/mmap-go v1.0.0
go: finding github.com/jmespath/go-jmespath latest
go: finding github.com/cznic/fileutil latest
go: finding github.com/cznic/b latest
go: finding github.com/googleapis/gax-go/v2 v2.0.5
go: finding github.com/hashicorp/golang-lru v0.5.3
go: finding github.com/denisenkom/go-mssqldb latest
go: finding golang.org/x/crypto latest
go: finding github.com/go-stack/stack v1.8.0
go: finding github.com/nakagami/firebirdsql latest
go: finding github.com/google/go-cmp v0.3.1
go: finding github.com/kshvakov/clickhouse v1.3.12
go: finding github.com/cznic/strutil latest
go: finding gopkg.in/inf.v0 v0.9.1
go: finding github.com/xanzy/go-gitlab v0.22.1
go: finding github.com/hashicorp/errwrap v1.0.0
go: finding github.com/aws/aws-sdk-go v1.25.37
go: finding github.com/cznic/zappy latest
go: finding github.com/cznic/golex latest
go: finding github.com/xdg/stringprep v1.0.0
go: finding github.com/cockroachdb/cockroach-go latest
go: finding github.com/golang/protobuf v1.3.2
go: finding github.com/mattn/go-sqlite3 v2.0.0+incompatible
go: finding github.com/gocql/gocql latest
go: finding gitlab.com/nyarla/go-crypt latest
go: finding github.com/xdg/scram latest
go: finding github.com/hashicorp/go-multierror v1.0.0
go: finding github.com/kardianos/osext latest
go: finding github.com/cznic/lldb v1.1.0
go get: github.com/kshvakov/clickhouse@v1.3.5 updating to
	github.com/kshvakov/clickhouse@v1.3.12: parsing go.mod:
	module declares its path as: github.com/ClickHouse/clickhouse-go
	        but was required as: github.com/kshvakov/clickhouse

**Comment by JamesPSheldon** [comment]
Fixing go.mod to change
  github.com/kshvakov/clickhouse v1.3.5
To
  github.com/ClickHouse/clickhouse-go v1.3.12
Should resolve this

**Comment by dhui** [comment]
Looks like this was the issue: https://github.com/ClickHouse/clickhouse-go/pull/227

**Comment by dhui** [comment]
Fixed by https://github.com/golang-migrate/migrate/pull/305
