### ISSUE TITLE
Add migrate command to the path in the Docker image

### ISSUE THREAD

**Issue by mrosales** [golang-migrate/migrate#304]
**Is your feature request related to a problem? Please describe.**
When using the docker image, either for interactive purposes or for something like a CI runtime, it is often helpful to override the entrypoint and just run the container using with a shell entrypoint. It would be nice to have the `migrate` binary linked on the path so it can be executed with `migrate` rather than `/migrate`.

**Describe the solution you'd like**
In order to avoid breaking backwards compatibility the cleanest solution is probably just to link the `/migrate` binary to `/usr/bin` in case anyone depends on the file being saved at the current location. 

Are there any objections to this or was there a reason to avoid placing the binary on the path to begin with?

**Comment by dhui** [comment]
> Are there any objections to this or was there a reason to avoid placing the binary on the path to begin with?

No objections. I believe`/migrate` was used for simplicity. Also, I wouldn't count on a shell being available in the docker image. In the future, we might use a scratch docker image.

Feel free to open a PR w/ your suggested change!

**Comment by dhui** [comment]
Fixed in [v4.10.0](https://github.com/golang-migrate/migrate/releases/tag/v4.10.0)
