### ISSUE TITLE
How I can run a specific down file?

### ISSUE THREAD

**Issue by tomiok** [golang-migrate/migrate#306]

**Comment by dhui** [comment]
Need more context.

In general, you shouldn't run an individual down file. If you want to backtrack to a certain state, find the current state and run down migrations to the desired state (you'll need to count the number of down migrations to run to).

If you really want to shoot yourself in the foot (**STRONGLY NOT RECOMMENDED**), you can force to the migration you want to run the down migration for and run the down migration.

I advise you to **test all of this in a dev environment before running on real production data.**

**Comment by dhui** [comment]
Closing due to lack of a response
