### ISSUE TITLE
http.FileSystem source

### ISSUE THREAD

**Issue by wayneashleyberry** [golang-migrate/migrate#307]
There are 3 open pull requests adding an http.FileSystem migration source, any chance we could prioritise one of them and all put our efforts in the same place?

- https://github.com/golang-migrate/migrate/pull/293
- https://github.com/golang-migrate/migrate/pull/163
- https://github.com/golang-migrate/migrate/pull/144

I'd really like to help get one of these merged, if at all possible. I want to start using this library with [`pkger`](https://github.com/markbates/pkger), so if there's anything I can do to help please let me know.

**Comment by ScottyFillups** [comment]
I've seen issues and PRs discussing http.FileSystem that are more than **half a year old**:

* https://github.com/golang-migrate/migrate/issues/116
* https://github.com/golang-migrate/migrate/pull/144
* https://github.com/golang-migrate/migrate/pull/171

I really hope the community agrees upon a PR and gets something merged, but I don't think anything is going to happen unless maintainers start communicating.

I'd really like to see support for `http.FileSystem`; please let me know if there's any way I can help :smile:

**Comment by fschade** [comment]
+1, if help needed...

**Comment by ScottyFillups** [comment]
@dhui can you please share your thoughts on this situation?

Out of the three open PRs, which implementation do you like the best? If we polished it up, would you be okay with merging it?

**Comment by Ambyjkl** [comment]
+1

**Comment by dhui** [comment]
### Current status of PRs

#144 needs to be refactored
#163 has the best design but its tests need to be updated to not use temp directories
#293 should adopt a similar design pattern to #163

I'm happy to merge any of those PRs if the issues are addressed. #163 and #293 seem the closest

**Comment by dhui** [comment]
https://github.com/golang-migrate/migrate/pull/293 has been merged to master. Will cut a new release after it's been in master for a bit

**Comment by dhui** [comment]
Now available in [v4.8.0](https://github.com/golang-migrate/migrate/releases/tag/v4.8.0)

**Comment by wayneashleyberry** [comment]
Fantastic, thanks for keeping us in the loop @dhui 🙌
