### ISSUE TITLE
Command line should allow specifying a MigrationsTable

### ISSUE THREAD

**Issue by jum** [golang-migrate/migrate#315]
**Is your feature request related to a problem? Please describe.**

I do use multiple schema_migrations tables for separate subsystems. For example one for the app at hand, and another for the sessions/accounts framework. To be able to develop them separately I use two directories with migrations.

**Describe the solution you'd like**

It would be nice if the command line utility had an option to specify the schema_migrations table name.

**Describe alternatives you've considered**

I already use this feature from my code but sometimes it is useful to be able to perform the migrations by hand.

**Additional context**

**Comment by dhui** [comment]
What DB driver are you using?
Most DB drivers support the `x-migrations-table` option (see the docs)

**Comment by jum** [comment]
I am using mysql. I could not find any option here:

https://github.com/golang-migrate/migrate/tree/master/cmd/migrate

**Comment by dhui** [comment]
See https://github.com/golang-migrate/migrate/tree/master/database/mysql

**Comment by jum** [comment]
Ah! Thanks for the hint, I missed this.
