### ISSUE TITLE
Dirty Database version 1 issue prevents migrations from running

### ISSUE THREAD

**Issue by pkaramol** [golang-migrate/migrate#317]
**Describe the Bug**
Migrations do not run due to the following error message

> Dirty database version 1. Fix and force version.

**Steps to Reproduce**
I have created my `up` and `down` `sql` migration scripts that begin something like this

```sql
CREATE database mydb;

USE mydb;

CREATE TABLE IF NOT EXISTS "mytable" (
  "id" int PRIMARY KEY,
  "day" date NOT NULL,
  "somefield" varchar NOT NULL
);
```
Here is the function that runs the migrations:

```go

func RunMigrations() {
	m, err := migrate.New(
		"file://db/migrations",
		"postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}
	if err := m.Up(); err != nil {
		log.Fatal(err)
	}
}
```

**Expected Behavior**
Migrations should have been run with success

**Migrate Version**
`4.7.1`

**Loaded Source Drivers**
`file`

**Loaded Database Drivers**
`postgres`

**Go Version**
`go version go1.13.1 darwin/amd64`

**Stacktrace**
```
Dirty database version 1. Fix and force version.
```

**Comment by nickmurr** [comment]
Hey, did you fix this issue? Having the same problem

**Comment by drnic** [comment]
@nickmurr try `drop table schema_migrations;` and the table will be recreated on next "first time" `up`

**Comment by masoud-moghini** [comment]
> @nickmurr try `drop table schema_migrations;` and the table will be recreated on next "first time" `up`

that was the best workaround (and perhaps solution) across all answers throughout the web

**Comment by DecodeWorms** [comment]
@drnic i wish i can give you 100 upvotes, thanks anyway.
