### ISSUE TITLE
Add Neo4j Support

### ISSUE THREAD

**Issue by mvid** [golang-migrate/migrate#321]
**Is your feature request related to a problem? Please describe.**
This has been a long standing todo from the original migrate implementation

**Describe the solution you'd like**
Support for the Neo4j graph database

**Describe alternatives you've considered**
I have implemented this solution

**Additional context**
My accompanying pull request is here: #320

**Comment by dhui** [comment]
Once the neo4j golang driver no longer uses cgo, we can support cross compilation and officially support neo4j e.g. include neo4j support in our official releases

Depends on: https://github.com/neo4j/neo4j-go-driver/issues/64

**Comment by dhui** [comment]
Neo4j is now supported in master and will available in the next release!

**Comment by dhui** [comment]
This is now available in [v4.9.0](https://github.com/golang-migrate/migrate/releases/tag/v4.9.0)
