### ISSUE TITLE
[Question] How to use migrations with GORM autoMigrate functionality?

### ISSUE THREAD

**Issue by lukasbash** [golang-migrate/migrate#322]
For a new project I have to use the GORM package to implement an API that is connected to a PostgreSQL database.
I am using GORM for the first time. However I already used this package in previous projects to cover database migrations. Worked like a charm.

Now I am using the `gorm.Model` struct to inject fields like `UpdatedAt`.

My question is: What if I have a new Table in my database (i.e. a new migration when using this package) and I want to use the gorm base model struct? Do I have to call the `autoMigrate` method on every model I introduce? Do I have to add the fields from gorm to every migration that I will create via the golang-migrate cli? Or is there a way to automatically mix in those fields into a migration?

It feels like I am missing something ...

Thank you

**Comment by dhui** [comment]
`migrate` has nothing to do with GORM. After a quick search online, you probably want https://gorm.io/docs/migration.html or https://github.com/go-gormigrate/gormigrate
