### ISSUE TITLE
Running migration scripts without a double confirmation is extremely dangerous

### ISSUE THREAD

**Issue by AOHUA** [golang-migrate/migrate#33]
Down migration scripts usually contains operations like drop table, drop index, etc. Which are extremely dangerous.  Please consider to add a double confirmation before apply any queries on the database. Thank you.

**Comment by dhui** [comment]
Migrations should not be run willy nilly, especially in your production environment...
All migrations *can* be dangerous, not just down migrations. Take for example an up SQL-type migration that adds a non nullable column with a default value on a table that has 100 million rows. Such a migration will probably grab a table lock and any reads would fail while the column is being added, which could take on the order of 10s of minutes depending on how large the table is, the DB load, and host performance.
Also, keep in mind that you may drop columns, tables, or indices in an up migration as your DB model changes.
My point is that it's the developer's responsibility to understand the DB(s) they're using and write migrations and plan operations appropriately.

Tools should support developers but need to balance providing appropriate protection without being annoying. I believe that confirmation prompts for every down or up migration is excessive.
