### ISSUE TITLE
[Question] How to check if migration shoule be applied?

### ISSUE THREAD

**Issue by kkocel** [golang-migrate/migrate#331]
I want to use migrate in my tests setup.

I have following code:
```go
	driver, err := postgres.WithInstance(db, &postgres.Config{})
	if err != nil {
		return err
	}
	sqltest.WaitForDB(db)
	m, err := migrate.NewWithDatabaseInstance(
		"file://"+path,
		dbName,
		driver)
	if err != nil  {
		return errors.Wrap(err, "cannot do migration")
	}

	err = m.Up()
	return err
```

The problem is when I apply `m.Up()` I get error -`no change`. How I can check if migration is feasible and then not apply migration?

**Comment by dhui** [comment]
You can check if the returned error is `ErrNoChange`.
For more info, see: https://github.com/golang-migrate/migrate/issues/100#issuecomment-492881033

It's hard to find the duplicate issue for this, but updating this [PR](https://github.com/golang-migrate/migrate/pull/246) should help prevent duplicates from being filed in the future.

**Comment by kkocel** [comment]
Ok, thanks for info, I'll handle it in the same way.
