### ISSUE TITLE
Error opening new connection when my database password has special character .e.g '&'

### ISSUE THREAD

**Issue by StewartJingga** [golang-migrate/migrate#332]
**Describe the Bug**
Error opening new connection when my database password has special character .e.g '&'

**Steps to Reproduce**
1. See error

**Expected Behavior**
It should encode URL when finding scheme and connect to database with different connection string format

**Migrate Version**
v4.7.0

**Loaded Source Drivers**
file

**Loaded Database Drivers**
postgres, postgresql

**Go Version**
go1.13

**Stacktrace**
Error: no scheme

**Comment by dhui** [comment]
Have you read and followed the [docs](https://github.com/golang-migrate/migrate#database-urls)?

**Comment by dhui** [comment]
Closing due to lack of response. Please reopen if there's an issue
