### ISSUE TITLE
Need ability to use my own aws session object when running the S3 bucket migration 

### ISSUE THREAD

**Issue by bishtawi** [golang-migrate/migrate#333]
**Is your feature request related to a problem? Please describe.**
Yes, I would like to pass in my own AWS session object when running migrations from an s3 bucket. Passing in my own AWS session object allows me to overwrite the AWS endpoint which allows me to use [localstack](https://github.com/localstack/localstack) when running my service locally.

```
session.NewSession(&aws.Config{
	Endpoint: &customEndpoint,
}
```

**Describe the solution you'd like**
Need the ability to pass in my own AWS session object (or my own AWS Config object).

**Describe alternatives you've considered**
Not using AWS S3 for holding migration scripts, but unfortunately I cant get away from that for the specific task I am about to implement at work.

Not using localstack when running locally, but that means all our engineers will need access to a real S3 bucket when developing locally which is a no go.

**Additional context**
Localstack provides a local mock AWS environment which is great for testing and local development. To use it, you have to modify the AWS session object to connect to the localstack instance instead of the real AWS infrastructure. As far as I can tell, you cannot override the url via evars.

**Comment by dhui** [comment]
This is now in release [v4.9.0](https://github.com/golang-migrate/migrate/releases/tag/v4.9.0)
