### ISSUE TITLE
Provide win32 release binaries

### ISSUE THREAD

**Issue by martinlindhe** [golang-migrate/migrate#339]
**Is your feature request related to a problem? Please describe.**
I'm looking at packaging migrate for scoop.sh (windows package manager), but would like to provide 32-bit support.

**Describe the solution you'd like**
Release scripts should build a win32 migrate.exe in addition to the x64 exe that is provided today.

**Comment by dhui** [comment]
What specific [GOARCH](https://github.com/golang/go/blob/master/src/go/build/syslist.go) do you need? I'm guessing `386`

Could you open a PR w/ such a change? e.g. add to the Makefile and test locally

**Comment by martinlindhe** [comment]
Sure!

Sent PR in #343

Tested locally with "make build-cli" on my macbook and transferred migrate.windows-386.exe to my Windows box and ran it there.
