### ISSUE TITLE
How to use my source driver in CLI

### ISSUE THREAD

**Issue by yonesko** [golang-migrate/migrate#351]
I have written my custom source driver.

I can't use it from CLI, how to register it?

**Comment by thesoulless** [comment]
CLI reading Databases list from:

`strings.Join(database.List(), ", ")`
Which is implemented in **database/driver.go**. Did you register your driver?

**customdriver.go**:
```golang
func init() {
	database.Register("customdriver", &CustomDriverStruct{})
}
```

**Comment by yonesko** [comment]
But your migrate tool doesn't call `database.Register("customdriver", &CustomDriverStruct{})`.

Should I recompile this repo with my custom driver package?

**Comment by dhui** [comment]
As @thesoulless mentioned, you'll need to register your driver. You'll also need to:
1. Fork the repo
1. Add a `build_*` file under `internal/cli`
    * If you add a build constraint, you'll also need to update the `Makefile` and `Dockerfile` to specify the proper build constraint tag(s)

**Comment by yonesko** [comment]
Thanks!
