### ISSUE TITLE
Is there any support for jackc/pgx connection pools?

### ISSUE THREAD

**Issue by feketegy** [golang-migrate/migrate#355]
**Is your feature request related to a problem? Please describe.**
I'm trying to use https://github.com/jackc/pgx package with migrate, but I can't seem to find a solution to migrate to use the pgxpool connection pools, as pgx doesn't have a standard database/sql interface.

**Comment by dhui** [comment]
There is not. You'll need to implement your own. Also, any such db driver that doesn't implement the Go `database/sql` interface will not be officially support by `migrate`.

Have you tried [pgx/stdlib](https://godoc.org/github.com/jackc/pgx/stdlib)?

**Comment by feketegy** [comment]
I need pgx pool and the interface that it implements. Thanks for your response though
