### ISSUE TITLE
Docs are not complete missing import file requirement

### ISSUE THREAD

**Issue by nichoriverae** [golang-migrate/migrate#362]
**Describe the Bug**
The readme should specify that there is a need to import the source file as `_ "github.com/golang-migrate/migrate/v4/source/file"`

**Comment by dhui** [comment]
There's already an example of that being done [here](https://github.com/golang-migrate/migrate#use-in-your-go-project). Feel free to open a PR to improve the docs. It doesn't hurt to have more examples of this import in other places. e.g. in the source and db READMEs
