### ISSUE TITLE
Why does migrate command put all the output to stderr?

### ISSUE THREAD

**Issue by renta** [golang-migrate/migrate#363]
**Describe the Bug**
I've figured out that migrate cli command put all the output to the STDERR. This leads to problem with tools such like Helm, Gitlab pipelines that somehow treat any output to STDERR as error even if migration ran sucessfully.

**Steps to Reproduce**
1. My migrations look like simple sql files in the migrations directory of the project.
2. I ran migrate with the following options: full command I ran:
`./migrate.linux-amd64 -path migrations -database "mysql://$(grep DB_CONNECTION= .env | cut -d '=' -f2-)" up`
3. See error: there is no error but all the output going to STDERR.

**Expected Behavior**
Errors should go to STDERR, normal output to STDOUT.

**Migrate Version**
4.10.0
Obtained by running: `migrate -version`

**Loaded Source Drivers**
Source drivers: file, s3, github, github-ee, gitlab, go-bindata, godoc-vfs, gcs
Obtained by running: `migrate -help`

**Loaded Database Drivers**
Database drivers: cockroachdb, firebirdsql, mongodb, redshift, cassandra, firebird, mysql, clickhouse, cockroach, postgres, stub, crdb-postgres, postgresql, spanner, sqlserver
Obtained by running: `migrate -help`

**Go Version**
go version go1.14 linux/amd64
Obtained by running: `go version`

**Stacktrace**
No stacktrace

**Additional context**
I've checked the output of the migrate command with this recipes https://superuser.com/questions/453598/determine-if-output-is-stdout-or-stderr

First way:
`{ { ./migrate.linux-amd64 -path migrations -database "mysql://$(grep DB_CONNECTION= .env | cut -d '=' -f2-)" up; } 2>&3 | sed 's/^/STDOUT: /'; } 3>&1 1>&2 | sed 's/^/STDERR: /'`
Output:
STDERR: 20200320104732/u init (23.666878ms)
on second run:
STDERR: no change

Second way:
`./migrate.linux-amd64 -path migrations -database "mysql://$(grep DB_CONNECTION= .env | cut -d '=' -f2-)" up > program.stdout 2> program.stderr`
Output of "ls -lah" (all the output in the program.stderr but migration was successful):
-rw-rw-r--  1 renta renta   35 мар 27 13:09 program.stderr
-rw-rw-r--  1 renta renta    0 мар 27 13:09 program.stdout

**Comment by dhui** [comment]
Ideally, errors would go to stderr and all other output would go to stdout.

However, `migrate`'s [Logger interface](https://godoc.org/github.com/golang-migrate/migrate#Logger) doesn't support log levels. The [current logic](https://github.com/golang-migrate/migrate/blob/master/internal/cli/log.go) is simple an naive. e.g. all output goes to stderr unless verbose was specified.

`migrate`'s logging does need to be overhauled but doing so would be backwards incompatible. I've created a new issue (https://github.com/golang-migrate/migrate/issues/364) to gather requirements for a new Logger interface and track work involved.

**Comment by renta** [comment]
What do you think about using [Zap logger](https://github.com/uber-go/zap)? It's fast, configurable, stable. I believe that it satisfy all the requirements, you wrote in https://github.com/golang-migrate/migrate/issues/364. If you think it's a good idea, I could help with its integration.

**Comment by dhui** [comment]
Any help would be appreciated! Since a new logger interface is backwards incompatible, any such changes wouldn't be released until v5, which may be a while since I'm trying to batch all backwards incompatible changes together.

**Comment by dhui** [comment]
Closing in favor of #364
