### ISSUE TITLE
Httpfs NewWithSourceInstance() gives unknown driver error for postgres

### ISSUE THREAD

**Issue by J7mbo** [golang-migrate/migrate#365]
**Describe the Bug**
Attempting to call `NewWithSourceInstance()` with a postgres URI provides the following error, **### even though the driver is correctly imported and working elsewhere**.

**Steps to Reproduce**

Ensure you have this import:

`import _ "github.com/lib/pq"`

Try a normal connection with the db and ensure it works:

        dbUri := "postgres://user:pass@localhost/dbname?sslmode=require"
	db, err := sql.Open(
		"postgres",
	         dbUri,
	))
        if err != nil {
            panic(err)
        }

Now, use the `NewWithSourceInstance()` with some filesystem you create (doesn't matter):

        migration, err := migrate.NewWithSourceInstance("httpfs", src, dbUri)

Get the following error:

> panic: database driver: unknown driver postgres (forgotten import?)

Important to note, this was *not* the case before adding the `NewWithSourceInstance()` call and the db connection worked fine.

**Expected Behavior**

I expect not to get this error.

**Migrate Version**
v4.10.0

**Loaded Database Drivers**
only lib/pq as shown above

**Go Version**
go version go1.13.7 darwin/amd64

**Additional context**
If relevant, I'm using the following to create a filesystem:
https://github.com/rakyll/statik

```
        statikFS, err := fs.New()
	if err != nil {
		panic(err)
	}

	src, err := httpfs.New(statikFS, "/")
	if err != nil {
		panic(err)
	}

	dbUri := fmt.Sprintf(
		"postgres://%s:%s@localhost/%s?sslmode=require",
		cfg.PostgresUsername, cfg.PostgresPassword, cfg.PostgresDbName,
	)

	migration, err := migrate.NewWithSourceInstance("httpfs", src, dbUri)
```

**Comment by dhui** [comment]
My guess is that you're not importing `github.com/golang-migrate/migrate/v4/database/postgres`.

The DB driver needs to be imported if you're using a db connection string when using the `migrate` library since the driver is registered in `init()`.

**Comment by J7mbo** [comment]
Many thanks @dhui, this was indeed the problem. Funnily enough during debugging I'd seen the `init()`, but it hadn't registered that it wasn't actually running. Many thanks.
