### ISSUE TITLE
hashicorp/go-multierror problem

### ISSUE THREAD

**Issue by somdutt-vmware** [golang-migrate/migrate#369]
**Describe the Bug**
golang-migrate fails with the following:
Loading golang-migrate
# github.com/hashicorp/go-multierror
/go/src/github.com/hashicorp/go-multierror/multierror.go:112:9: undefined: errors.As
/go/src/github.com/hashicorp/go-multierror/multierror.go:117:9: undefined: errors.Is

**Steps to Reproduce**
1. My migrations look like:
migrate -database "postgres://${PGHOST}/${PGDATABASE}?user=${PGUSER}&password=${PGPASSWORD}" -path ./scripts/migrations up 2>&1
**Error**
Loading golang-migrate
# github.com/hashicorp/go-multierror
/go/src/github.com/hashicorp/go-multierror/multierror.go:112:9: undefined: errors.As
/go/src/github.com/hashicorp/go-multierror/multierror.go:117:9: undefined: errors.Is

**Expected Behavior**
golang-migrate shouldn't have issues with multi-error, it has been fixed in v1.1.0 recently (6 days ago)

**Migrate Version**
Must use multierror version v1.1.0 instead of v1.0.0

** Driver**
PostgreSQL

**Go Version**
1.13.9

**Comment by dhui** [comment]
To be clear, `migrate` doesn't have issues with `multierror`.

What versions of `migrate` and `multierror` are you using? My guess is that your code is using `multierror` `v1.1.0` while `migrate` is using `v1.0.0`. It looks like `As()` and `Is()` were added in `multierror` `v1.1.0`. Feel free to open a PR for the fix.

**Comment by jmramos02** [comment]
Hi @dhui ! i submitted a pr for upgrading the multierror. 

Thanks!

**Comment by dhui** [comment]
Thanks for the fix @jmramos02 !
