### ISSUE TITLE
schema_migrations table is assumed to be in the same schema before running migration file and afterwards

### ISSUE THREAD

**Issue by gadumitrachioaiei** [golang-migrate/migrate#37]
For postgres at least, we create the schema_migrations table in whatever current schema we are ( I think we will always be in public schema ), before running migrations.
After we run the migrations we update the table and assume we are in the same schema because we hope  the migration file did not change schema, which can happen. The resulting error is:

`error: pq: relation "schema_migrations" does not exist in line 0: TRUNCATE "schema_migrations"`

**Comment by dhui** [comment]
Have you tried specifying the `search_path`?

### Docs:
* https://github.com/golang-migrate/migrate/tree/master/database/postgres
* https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters
* https://www.postgresql.org/docs/10/static/runtime-config-client.html

**Comment by gadumitrachioaiei** [comment]
I don't understand how this would solve the problem. The migration scripts work with several schemas inside the same database. The library code assumes that after a migration script run, the initial current schema remains the same as before the script was run. To work for me, I just set the search path to be public schema again. But I don't think the code should make such an assumption in the first place.

**Comment by dhui** [comment]
I don't understand the issue you're having. You should be able to work with multiple schemas in your migration files w/o any issue. Are your migrations setting the search_path? The search_path should be specified as an option to migrate.

**Comment by gadumitrachioaiei** [comment]
Yes, they are. One script can do that multiple times, switching between schemas.
If I understand correctly, using search_path as part of dsn, this would mean that all operations would consider that to be the current schema, including everything the migrate library does ?

**Comment by dhui** [comment]
If you're setting the search_path in your migration files, you'll need to "revert"/reset it. migrate cannot track DB state changes made in migrations.

Instead of setting the search_path in your migration files, you could also specify the schema explicitly.

Setting the search_path in the DSN will affect migrate and the migrations it runs. Keep in mind that multiple schemas can be specified in the search_path.

**Comment by gadumitrachioaiei** [comment]
Thanks. I did revert the schema back to public ( initial schema ) in migration script. I just thought that I make an issue in case this is not intended behavior.
