### ISSUE TITLE
Add an option to assume "yes" to all prompts

### ISSUE THREAD

**Issue by soroushj** [golang-migrate/migrate#370]
**Is your feature request related to a problem? Please describe.**
I want to run the `migrate down` command non-interactively in an automation script. But it prompts `Are you sure you want to apply all down migrations? [y/N]` and there's no option to bypass this.

**Describe the solution you'd like**
Add an option to the CLI, e.g. `-yes`, to assume "yes" to all prompts.

**Describe alternatives you've considered**
Running `echo y | migrate down ...`.

**Comment by dhui** [comment]
use `-all`

This brings up a good point though. We should include help for sub-commands.

**Comment by dhui** [comment]
Created a new issue to track this: https://github.com/golang-migrate/migrate/issues/372
