### ISSUE TITLE
Clear explanation why we need `.up.sql` and `.down.sql`

### ISSUE THREAD

**Issue by zak905** [golang-migrate/migrate#371]
Hi, 

This library is interesting and I would like to use it in my project. However, I am not sure I understand why need a `.up.sql` and its `.down.sql` counterpart. There is only few said about this in the docs  https://github.com/golang-migrate/migrate/blob/master/FAQ.md#why-two-separate-files-up-and-down-for-a-migration

Based on my understanding (and my usage of other migration tools like Flyway or liquibase), a migration file (e.g `01_init.sql`) is something irreversible. therefore if you need to reverse a migration file (e.g delete something), you would create a new a migration that does it..etc. Once a migration file is applied, it should never be modified or altered again. Therefore I'd expect the migration to go always in same direction: upwards. In the case of migrate, suppose I have this migration: 
01_init.up.sql
```
CREATE TABLE IF NOT EXISTS users(
   user_id serial PRIMARY KEY,
   username VARCHAR (50) UNIQUE NOT NULL,
   password VARCHAR (50) NOT NULL,
   email VARCHAR (300) UNIQUE NOT NULL
);
```
then if want to delete this same table, I would just create another `02_delete_users.up.sql`

```
DROP TABLE IF EXISTS users;
```
and so on. 

Why would we need to go backwards at any point of time ? How is this useful ? We should be going up all the time, no ?

Cheers,
Zakaria

**Comment by dhui** [comment]
The docs could definitely use some work. For me, the knowledge is spread across different docs and not well organized. If you have some free time, any help would be appreciated!

Does [this](https://github.com/golang-migrate/migrate/blob/master/MIGRATIONS.md#reversibility-of-migrations) answer your question? Also, read about idempotency [here](https://github.com/golang-migrate/migrate/blob/master/GETTING_STARTED.md#create-migrations)

**Comment by zak905** [comment]
Thanks for the explanation. I see the point, kind of. However, one would rarely need to go downwards, and maybe in just edge cases after adding a new `up` migration, if you plan your migration well (adjusting all the code parts..etc). Are the current library users following this pattern or finding it useful ? 

if you need to go down only 1 in 10 times, then adding 10 `down` files could be seen as overengineering or being too conservative.

Also, I am not sure I understand:
> This prevents any non-standard file syntax from being introduced which may result in unintended behavior or errors, depending on what database is processing the file.

I am pretty new to the library, so maybe I am not the right one to write docs for now. Maybe this will change once I introduce it in my project.

**Comment by dhui** [comment]
down/reversible migrations are a [good](https://flywaydb.org/documentation/migrations#undo-migrations) [practice](https://docs.djangoproject.com/en/3.0/topics/migrations/#reversing-migrations). e.g. they're really useful during development
Both up and down migrations should be tested in development before going out to production

> I am pretty new to the library, so maybe I am not the right one to write docs for now.

I believe someone new to the project is more suited to provide feedback for the docs and improve them since they're not as familiar with the project and can more clearly see/identify issues. Also, going through the docs and improving them also a good way to learn more about the project. 😉

**Comment by zak905** [comment]
To sum up: `.down.sql` migrations could be useful if you are using the CLI. In this case, you could  rollback if a migration goes wrong. However, there is another alternative: fixing the `up.sql` failing migration and using force to come back to the previous migration and then using `up` again. 

If you are using migrate from your code, then you should already have code that takes care of that (types of errors, when to run `Down()` in case an `Up()` fails). It would be nicer if migrate would automatically back up from a migration when it fails. Here is a code snippet that assumes no `.down.sql` are present, and attempts to recover from a failing migration:  

```
m, err := migrate.New("file://db", "mysql://test:test@tcp(localhost:3306)/test")
	if err != nil {
		panic(err.Error())
	}
if err = m.Up(); err != nil {
		log.Println(err.Error())
		switch err {
		case migrate.ErrNoChange:
			log.Println("no new changes to apply to the database")
			break
		//handle other errors types if needed
		default:
			dirtyDatabaseError, isDirtyError := err.(migrate.ErrDirty)
			if isDirtyError {
				log.Println("attempting to recover")
                                //migrations should start from 0
				m.Force(dirtyDatabaseError.Version - 1)
				if innerError := m.Up(); innerError != nil {
					panic("could not recover from database error: " + innerError.Error())
				}
				log.Println("sucessfully recovered")
			} else if _, isDatabaseError := err.(db.Error); isDatabaseError {
				panic("migrations have syntax error")
			}
		}
	}
```

I think I am going to go without the `.down.sql` for now.
