### ISSUE TITLE
cli fails with "database driver: unknown driver mysql (forgotten import?)"

### ISSUE THREAD

**Issue by nutmix** [golang-migrate/migrate#38]
Note, we are using the old version, which stays to post issues here.

Built it like this:

```
$ go get -u -d github.com/mattes/migrate/cli github.com/go-sql-driver/mysql
$ go install -tags 'mysql'  github.com/mattes/migrate/cli
```

when I run it like this:

`$ cli -database "mysql://xxx:yyy@/zzz" -source file://go/src/github.com/xxx/xxx.org/db/schema up
`

I get:

`error: database driver: unknown driver mysql (forgotten import?)`

Any ideas?

**Comment by nutmix** [comment]
Using go 1.10.2

Is golang-migrate backward compatible with scripts writting for mattes/migrate?

**Comment by dhui** [comment]
Yes, migrations are not interpreted by `migrate` and are passed straight to the DB

**Comment by nutmix** [comment]
The binary version from the release page you suggested worked.
