### ISSUE TITLE
Support migration for newly added files without deleting all tables

### ISSUE THREAD

**Issue by tanvir-retailai** [golang-migrate/migrate#381]
**Is your feature request related to a problem? Please describe.**
I have 2 migration files as `20200423194823_create_user_table.up.sql` and `20200423194823_create_user_table.down.sql`. I run the migration and it was successful. After that I created 2 more migration files as `20200424032427_create_userprofile_table.up.sql` and `20200424032427_create_userprofile_table.down.sql` and run the migration again and receive following error:
`duplicate migration file: 20200424032427_create_userprofile_table.up.sql`

To avoid the above error I had to remove all my previous tables including `schema_migrations`

**Describe the solution you'd like**
I think it would be nice if the migration run properly with newly added migration files

**Describe alternatives you've considered**
I really wanna use `golang-migrate` library as it's supporting multiple databases (sql and nosql)

**Comment by dhui** [comment]
Are you sure you didn't duplicate versions? That's the [only way migrations are marked as duplicate](https://github.com/golang-migrate/migrate/blob/v4.10.0/source/migration.go#L58).

[Parsing dates](https://github.com/golang-migrate/migrate/blob/v4.10.0/source/parse.go#L27) as versions is [known to work](https://github.com/golang-migrate/migrate/blob/v4.10.0/source/parse_test.go#L54)

**Comment by tanvir-retailai** [comment]
Thanks @dhui. Your reply helps me a lot.
