### ISSUE TITLE
Make CLI work with native postgres URL for cockroachDB

### ISSUE THREAD

**Issue by georgysavva** [golang-migrate/migrate#382]
I want to use the migrate tool for cockroachDB and it supports, it's really cool. But in order to select the right database driver the URL should start with `cockroachdb://` instead of the native `postgres://`. It's a bit weird to have two URLs in the same project for the same database: one for the migrate tool (starts with `cockroachdb://`) and one for actual application to connect to the db (starts with `postgres://`).

Maybe it would be better to add a separate `-driver` argument for the `migrate` CLI, to be able to call it like that:
```
migrate -driver cockroachdb -database "postgres://root@localhost:26257/defaultdb?sslmode=disable" -path "..." up
``` 
This way we can preserve URL with it native schema and specify what database driver to use explicitly.
What do you think?

**Comment by dhui** [comment]
> It's a bit weird to have two URLs in the same project for the same database: one for the migrate tool

It's not weird and quite standard for different tools to use different schemas.

Won't fix since there are too many different URI schemas or connection strings to attempt to be compatible with, making maintenance hard.

**Comment by georgysavva** [comment]
Okay, understood. Thanks for explaining me that!
