### ISSUE TITLE
Unknown driver even though it's registered

### ISSUE THREAD

**Issue by rakyll** [golang-migrate/migrate#385]
The program below outputs:

```
[mysql spanner]
2020/05/08 12:59:55 source driver: unknown driver mysql (forgotten import?)
exit status 1
``` 
Even though database.List() call returns both "mysql" and "spanner" in the main package, when I debug migrate.New and print `database.List()`, I see an empty slice. 

Am I doing something wrong?

```
package main

import (
	"fmt"
	"log"

	"github.com/golang-migrate/migrate/v4"
	"github.com/golang-migrate/migrate/v4/database"

	_ "github.com/golang-migrate/migrate/v4/database/mysql"
	_ "github.com/golang-migrate/migrate/v4/database/spanner"
)

func main() {
	fmt.Println(database.List())
	m, err := migrate.New(
		"mysql://root:@localhost:3306/sys",
		"spanner://projects/computelabs/instances/hello/databases/db")
	if err != nil {
		log.Fatal(err)
	}
	if err := m.Up(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by dhui** [comment]
Looks like you're using mysql as a [source driver](https://github.com/golang-migrate/migrate#migration-sources) which doesn't exist. Bundled source drivers can be found [here](https://github.com/golang-migrate/migrate/tree/master/source).

**Comment by rakyll** [comment]
Ah, gotcha. Sorry, it took me a while to understand the API because types are not represented in the connection strings.
