### ISSUE TITLE
Schema bugfixes through hotfix branches

### ISSUE THREAD

**Issue by nkumar15** [golang-migrate/migrate#387]
**Is your feature request related to a problem? Please describe.**
I am applying sequence based migration in my DB schema using migrate tool. But one of the scenario I also need to manage is to backport schema fixes in already released branch. 
For eg
1.  In release 1, I successfully release v1 schema version in production.
2. Now feature development is happening in feature branch with schema version v2 which is actually incremental update of v1.
3. Now in between production issue arises and it requires to fix/patch schema of v1.

How do we manage v1 bugfixes using migrate? because

Introducing a new sequence in feature branch for this bugfix is incorrect as fix needs to asap and cannot wait for feature to complete.
Introducing a new sequence for v1 branch will require to adjust all sequence numbers which are present in v2 feature branch which is very error prone to manage.

**Describe the solution you'd like**
Is it possible that dbmigrate supports multiple migration tables (schema_migrations and bugfix_migration). Or any other better way to solve this which I am not aware of?

Thank you.

**Comment by dhui** [comment]
Closing in favor of https://github.com/golang-migrate/migrate/issues/278
