### ISSUE TITLE
POSTGRES driver throwing unknown driver error

### ISSUE THREAD

**Issue by aditya1808** [golang-migrate/migrate#388]
Im trying to migrate schema to postgreSQL running in my cluster.

But it throws the below error 
![image](https://user-images.githubusercontent.com/6763803/81833036-d6b5f400-955c-11ea-8f71-b00a71e44cd4.png)

Could someone tell what exactly the issue is. I followed same procedure for mariadb and it works. But for postgresql, its throwing this error

**Comment by oshankkumar** [comment]
can you please check in your code whether you are importing `"github.com/golang-migrate/migrate/database/postgres"` or not .

**Comment by aditya1808** [comment]
@oshankkumar thank you. i was missing import.

**Comment by venkatesan-r-1509** [comment]
I am using the CLI version in Windows. I am getting the same error.

![image](https://user-images.githubusercontent.com/30339945/83771912-68b6a580-a6a0-11ea-8de4-2f305605eadf.png)

Is there anything I am missing?

**Comment by frederikhors** [comment]
@venkatesan-r-1509 same here. Got you fixed?

**Comment by nitaigao** [comment]
Same here when using the Docker image

**Comment by joaowiciuk** [comment]
same here when using CLI under Linux

**Comment by Alireza-Ta** [comment]
I did solve this via using [migrate CLI](https://github.com/golang-migrate/migrate/tree/master/cmd/migrate) in MacOS

**Comment by jgibo** [comment]
This happened to me on v4.5.12. I had accidentally wrapped my database url environment variable in quotes, resulting in literal quotes being part of the value.

After removing the literal quotes from my database url, the issue was resolved.
