### ISSUE TITLE
Incorrect help text?

### ISSUE THREAD

**Issue by intel352** [golang-migrate/migrate#39]
https://github.com/golang-migrate/migrate/blob/faf4307fcc7245d1df1c1000ca94c6c9d2537087/cli/main.go#L117

Specifically the sub-string: `For yyyymmddhhmmss use format of 20060102150405.`
Seems to me this should instead read as: `For 20060102150405 use format of yyyymmddhhmmss.`

**Comment by dhui** [comment]
Go uses a reference time to specify time formats.

To avoid confusion, we could change this to: `Go time format string. Remember, Go uses the reference time (01/02 03:04:05PM '06 -0700) as the formatter. Defaults to unix timestamp`

Feel free to open a PR

**Comment by dhui** [comment]
[v3.3.0](https://github.com/golang-migrate/migrate/releases/tag/v3.3.0) top level help states: `Use -format option to specify a Go time format string.`.
Help for the `create` command, now states: `  -format string
    	The Go time format string to use. If the string "unix" or "unixNano" is specified, then the seconds or nanoseconds since January 1, 1970 UTC respectively will be used. Caution, due to the behavior of time.Time.Format(), invalid format strings will not error (default "20060102150405")`
