### ISSUE TITLE
Url escaping

### ISSUE THREAD

**Issue by Zaazik** [golang-migrate/migrate#396]
**Describe the Bug**
When you has password like `xxxx%tKxxxxx`

**Steps to Reproduce**
I ran migrate with the following options '....'
`@migrate -database "mysql://user:xxxx%tKxxxxx@tcp(host:3306)/root" \
		-path ./db/migrations ${MIGRATE_CMD}`
See error
error: invalid URL escape "%tK"

**Migrate Version**
v4.11.0
Installed by brew

**Loaded Database Drivers**
mysql

**Additional context**
We use its in **CD**  and password we get from credentials.

**Comment by ultimateboy** [comment]
To work around this, simply url-escape the connection string.

**Comment by dhui** [comment]
See: https://github.com/golang-migrate/migrate#database-urls
