### ISSUE TITLE
Add an example for beginners

### ISSUE THREAD

**Issue by mohtamohit** [golang-migrate/migrate#40]
It would be a great help if you could include an example so that beginners can better understand the concept of migrations and how to implement stuff using this tool.

**Comment by dhui** [comment]
A potential starting point for a guide: https://github.com/golang-migrate/migrate/issues/42#issuecomment-393211071

**Comment by mknycha** [comment]
Hey, is someone already working on this, or is it ok to contribute? Just wanted to make sure

**Comment by dhui** [comment]
@mknycha Feel free to take a crack at this and open a PR!

Were you planning on updating the README, godoc, and/or creating a new docs site?
The docs could use some cleanup and reorganization, but any help you're able to provide is appreciated.

**Comment by mknycha** [comment]
My idea was to start with README, we'll see how it goes ;)

**Comment by dhui** [comment]
Fixed in https://github.com/golang-migrate/migrate/pull/258

**Comment by mohtamohit** [comment]
Thank you! :)
