### ISSUE TITLE
schema_migrations table only ever contains a single record for MySQL driver, docker image

### ISSUE THREAD

**Issue by NickOttrando** [golang-migrate/migrate#405]
**Describe the Bug**
The schema migrations table should contain a record for each migration ran, but it only ever contains a single record with the most recent migration version with MySQL.

**Steps to Reproduce**
Create two migration files, first `1_test.up.sql`, run it with the migrate CLI command. Check the `schema_migrations` table, it will have a record for `version=1`. Create a second migration, `2_test.up.sql`, run it with the same CLI command (e.g. `migrate ... up 1`), `select * from schema_migrations` and the record for `version=1` is no longer there, only `version=2`. [Docker image](https://hub.docker.com/layers/migrate/migrate/v4.11.0/images/sha256-f258cc5fa2d03193e1c109ad1c941a7e710318115f509fcf3c89bd6a7e75605a?context=explore) may or may not be a factor in reproducing.

**Expected Behavior**
I expect to see all migrations that have ran in the `schema_migrations` table, not just the most recent. 

**Migrate Version**
v4.11.0 ([docker image](https://hub.docker.com/layers/migrate/migrate/v4.11.0/images/sha256-f258cc5fa2d03193e1c109ad1c941a7e710318115f509fcf3c89bd6a7e75605a?context=explore))

**Loaded Source Drivers**
[docker image](https://hub.docker.com/layers/migrate/migrate/v4.11.0/images/sha256-f258cc5fa2d03193e1c109ad1c941a7e710318115f509fcf3c89bd6a7e75605a?context=explore)

**Loaded Database Drivers**
mysql

**Go Version**
go1.13 linux/amd64

**Comment by dautushenka** [comment]
Looks like it's default behavior. We have the same issue with postgresql. It's relay not convenient with team 2 and more people. Looking for another tool for now(

**Comment by NickOttrando** [comment]
> Looks like it's default behavior. We have the same issue with postgresql. It's relay not convenient with team 2 and more people. Looking for another tool for now(

I thought this was a bug given that no other migration tools behave like this, and there is no documentation whatsoever on the behavior of the `schema_migrations` table that I could find.

**Comment by dhui** [comment]
See also: https://github.com/golang-migrate/migrate/issues/179
