### ISSUE TITLE
make: *** [build-cli] Error 1

### ISSUE THREAD

**Issue by goodforever** [golang-migrate/migrate#408]
**Describe the Bug**
go build github.com/golang-migrate/migrate/v4/database/neo4j: build constraints exclude all Go files in /Users/foo/work/gomod/migrate/database/neo4j
make: *** [build-cli] Error 1

**Steps to Reproduce**
make build-cli

**Expected Behavior**
make build-cli successfully

**Migrate Version**
Migrate Version=4.11.0

go version go1.14 darwin/amd64

**Comment by dhui** [comment]
Try one of the following:
* the master branch
* these instructions: https://github.com/golang-migrate/migrate/tree/v4.11.0/database/neo4j#building
* disabling neo4j in the Makefile and/or Dockerfile

**Comment by goodforever** [comment]
Thanks, I disable neo4j in the Makefile
