### ISSUE TITLE
Add integration tests for spanner

### ISSUE THREAD

**Issue by dhui** [golang-migrate/migrate#410]
**Is your feature request related to a problem? Please describe.**
The spanner db driver should have integration tests to prevent regressions

**Describe the solution you'd like**
Use the [spanner emulator](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator) which is available with pre-built docker images

**Describe alternatives you've considered**
* Use [in-memory emulator written in Go](https://godoc.org/cloud.google.com/go/spanner/spannertest) directly
    * Would probably startup faster than a docker image but not sure about the differences between the emulators

**Additional context**
N/A

**Comment by wyardley** [comment]
I've done some things similar to this in Circle, and I can see where the integration test code is happening.

Looks like I'd use your docker testing framework for this part vs. the way the existing integration test is handled, right?

**Comment by dhui** [comment]
The current spanner tests aren't run in CI since they're tagged as [short](https://golang.org/pkg/testing/#Short). This change would involve using either using docker images or the [in-memory emulator](https://godoc.org/cloud.google.com/go/spanner/spannertest) in the tests. The main advantage of using the docker image is that we can test against different versions of the spanner emulator which in theory, reflect the different versions of spanner.

**Comment by dhui** [comment]
Fixed in master. We're using the in-memory emulator directly.
