### ISSUE TITLE
MySQL migrations with custom TLS Parameters dont function as documented [CLI]

### ISSUE THREAD

**Issue by Chronojam** [golang-migrate/migrate#411]
**Describe the Bug**
When using the CLI version, connecting to mysql with custom tls parameters as described here:
https://github.com/golang-migrate/migrate/tree/master/database/mysql

the CLI exits prematurely with the following error: ```error: invalid value / unknown config name: anything```

**Steps to Reproduce**
```
./migrate -source=file://some_path/ -database=mysql://foo:bar@tcp(localhost:3306)/dbname?tls=anything&x-tls-ca=some_escaped_path up
```

**Expected Behavior**
migrations should execute successfully

**Migrate Version**
v4.10.0

**Loaded Source Drivers**
file, s3, github, github-ee, gitlab, go-bindata, godoc-vfs, gcs

**Loaded Database Drivers**
firebird, postgresql, firebirdsql, spanner, redshift, sqlserver, cassandra, clickhouse, cockroach, cockroachdb, crdb-postgres, mysql, mongodb, postgres, stub

**Go Version**
using standalone CLI tool

**Additional context**
Heres what i think is happening.

1. Call out to the mysql.ParseDSN 
https://github.com/golang-migrate/migrate/blob/4598673138781c47d5762128993fb4ddc123b9a3/database/mysql/mysql.go#L120

2. This errors because mysql.RegisterTLSConfig isnt called until afterwards:
https://github.com/golang-migrate/migrate/blob/4598673138781c47d5762128993fb4ddc123b9a3/database/mysql/mysql.go#L143

3. This line in ParseDSN appears to be catching the not-yet-registered config value
https://github.com/go-sql-driver/mysql/blob/12508c83901b1a418e3dea51850f956f32506f4e/dsn.go#L132

If im correct ( and tbh im not an expert on the driver, so it may be that this isnt the reason at all!)

I think the correct fix is to parse out the x-tls details before calling mysql.ParseDSN

**Comment by dhui** [comment]
Thanks for the detailed report @Chronojam !
