### ISSUE TITLE
Unable to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by pnutmath** [golang-migrate/migrate#416]
**Describe the Bug**
Unable to install on ubuntu 20.04 with steps provided in documentaion

**Steps to Reproduce**
```
$ curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
$ echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
$ apt-get update
$ apt-get install -y migrate
```
Results:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package migrate is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'migrate' has no installation candidate
```

**Expected Behavior**
> I should able to install on ubuntu seamlessly

**Migrate Version**

> Not Applicable

**Loaded Database Drivers**
> postgres

**Go Version**
> `go version go1.14.4 linux/amd64`

**Comment by Yosef0109** [comment]
I have same issue.

**Comment by dhui** [comment]
Thanks for reporting the issue. The next release should be available for in our package cloud apt repos for Ubuntu 20.04.

**Comment by pnutmath** [comment]
What is plan for next release?

**Comment by dhui** [comment]
[v4.12.0](https://github.com/golang-migrate/migrate/releases/tag/v4.12.0) now [available](https://packagecloud.io/app/golang-migrate/migrate/search?dist=ubuntu%2Ffocal) for Ubuntu 20.04

**Comment by kumarprafful** [comment]
Am i the only one who's still facing this problem?
