### ISSUE TITLE
Binary release downloads for v4.12.1

### ISSUE THREAD

**Issue by leakyshoe** [golang-migrate/migrate#422]
Hi, I followed the instructions "https://github.com/golang-migrate/migrate/tree/master/cmd/migrate" to access the binary releases but they are not available for v4.12.1. The last available binary releases are for version v4.11.0. Is there a recommended way of installing v4.12.1? Thanks in advance for any help

**Comment by dhui** [comment]
The is due to: https://github.com/golang-migrate/migrate/issues/420
