### ISSUE TITLE
sql.Rows.Next() not followed by Rows.Err()

### ISSUE THREAD

**Issue by leventov** [golang-migrate/migrate#432]
There are many places in drivers where `sql.Rows.Next()` is called. It can return `false` not only because iteration ended, but also because it failed. `Rows.Err()` is never called in the codebase to distinguish these cases.

**Comment by dhui** [comment]
This seems to affect the `Drop()` method in nearly every db driver:
```shell
$ git grep -l 'Next(' database/
database/clickhouse/clickhouse.go
database/cockroachdb/cockroachdb.go
database/firebird/firebird.go
database/mysql/mysql.go
database/neo4j/neo4j.go
database/postgres/postgres.go
database/ql/ql.go
database/redshift/redshift.go
database/snowflake/snowflake.go
database/spanner/spanner.go
database/sqlite3/sqlite3.go
$
```
