### ISSUE TITLE
There is no access to docker image on docker hub

### ISSUE THREAD

**Issue by burkostya** [golang-migrate/migrate#44]
running 
```sh
docker run -it --rm golang-migrate/migrate --help
```
returns error
```
docker: Error response from daemon: pull access denied for golang-migrate/migrate, repository does not exist or may require 'docker login'.
```

**Comment by dhui** [comment]
This will be fixed in the next release (v3.3.0)

**Comment by dhui** [comment]
Fixed in [v3.3.0](https://github.com/golang-migrate/migrate/releases/tag/v3.3.0)

**Comment by alexanderGalushka** [comment]
@dhui doesn't seem to be fixed though

```
$ docker run -it --rm golang-migrate/migrate --help
```

still error:

```
docker: Error response from daemon: pull access denied for golang-migrate/migrate, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

**Comment by dhui** [comment]
https://hub.docker.com/r/migrate/migrate/

**Comment by alexanderGalushka** [comment]
@dhui the ```latest``` tag is missing though you can only pull if you do ```docker pull migrate/migrate:v3.3.0```

**Comment by dhui** [comment]
I've manually pushed the latest tag to docker hub.

This should be automated with the next release. https://github.com/golang-migrate/migrate/commit/6070aa8281007929a35ff9a54e82ddc319bc92a8 https://github.com/golang-migrate/migrate/commit/236dac0c964c3fe92a0e79931232453e7b0f03af
