### ISSUE TITLE
Seeding capability 

### ISSUE THREAD

**Issue by cymon1997** [golang-migrate/migrate#441]
**Is your feature request related to a problem? Please describe.**
It would be great if you can add seeding feature. Currently, I already try to make different path for migration and seeder files, but it can't be executed because `schema_migrations` table is created in same schema. 

**Describe the solution you'd like**
Implement database seeding feature. 

**Describe alternatives you've considered**
Other solution might be if we can specify custom `schema_migrations` table so we can apply multiple migration in one project.

**Additional context**
Please let me know if you have concern of this suggestion. Thank you for the great library :+1:

**Comment by dhui** [comment]
Why is the `schema_migrations` table causing issues with db seeding?
We could support customizing the `schema_migrations` table's schema if you want to open a PR for this.

**Comment by cymon1997** [comment]
@dhui sorry for late response. 
because seeding will use the same schema_migrations that already used by migration. I think it would be great if we can specify which `schema_migrations` table to be used. Thanks!

**Comment by cymon1997** [comment]
sorry @dhui 
after further reading about the library, I actually can set the p.config.MigrationsTable using `x-migrations-table` in connection string :pray: 
will close this issue, thanks!
