### ISSUE TITLE
Extend cli/cli wrapper.

### ISSUE THREAD

**Issue by any626** [golang-migrate/migrate#443]
I want to use the cli without having to input the url as an option/flag. Is it possible to extend the cli to be included into my own cmd? In my specific case I would use my existing package, configurations, and code that connects to the database and use that to run the cli with all available options.

Current cli tool: `migrate -source file://path/to/migrations -database postgres://localhost:5432/database up 2`

With wrapper: `extendedmigrate up 2` or `extendedmigrate down 1` or etc

Rough idea of cli wrapper api
```
package main

import (
	"database/sql"
	"skatebuilder/internal/config"

	"github.com/golang-migrate/migrate/v4"
	"github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	_ "github.com/lib/pq"
)

func main() {
	// Load configs
	c := config.Config() // fake code

	// Build url
	url := db.BuildUrl(c) // fake code "postgres://localhost:5432/database?sslmode=enable"

	db, err := sql.Open("postgres", url)
	driver, err := postgres.WithInstance(db, &postgres.Config{})
	m, err := migrate.NewWithDatabaseInstance(
		"file:///migrations",
		"postgres", driver)
	migrate.CliWrapper(m)
}
```

**Comment by dhui** [comment]
Wrapping the CLI with a bash script or function may be easier. A more complicated but more flexible option would be to re-implement the CLI and using the `migrate` Go library.

**Comment by any626** [comment]
Thanks for the suggestion.

I went ahead with a bash script

```
#!/bin/bash
# load .env file
export $(grep -v '^#' .env | xargs)

./migrate "$@" -source file://migrations/ -dir file://migrations/ -database postgres://$USERNAME:$PASSWORD@$HOST:$PORT/$DATABASE
```
