### ISSUE TITLE
is sqlx driver supported?

### ISSUE THREAD

**Issue by komalbb** [golang-migrate/migrate#444]
the var db  *sqlx.DB	
db = fix.Database.DB
	driver := db.Driver()
	m, _ := migrate.NewWithDatabaseInstance(
		"dbschema",
		"mysql",
		driver,
	)
../fixtures/setup.go:127:3: cannot use driver (type driver.Driver) as type database.Driver in argument to migrate.NewWithDatabaseInstance:
	driver.Driver does not implement database.Driver (missing Close method)

Is sqlx supported db migrations? If it is, please share an example how to use

**Comment by dhui** [comment]
Seems like an issue w/ your code. You should be able to use the underlying `sql` driver with both `migrate` and `sqlx`.

**Comment by komalbb** [comment]
fixed: instead of passing driver of sqlx.DB, we will pass sqlx.DB.DB(which is from sql). CLosing the issues
