### ISSUE TITLE
Adding the compilation process in the README

### ISSUE THREAD

**Issue by vaibhav-kaushal** [golang-migrate/migrate#451]
It took me a while to notice the **Makefile** and then compile the project. Not all projects follow the `go build ./cmd/something` approach. So while it might be abundantly clear for the regular users, first-timers might need a pointer. 

And for such cases, a basic one liner stating that the use of `make` is recommended to build the `migrate` command can be very helpful. However, a lot of folks actually don't know how to read Makefiles either. So, a few examples would be really great.

**Comment by dhui** [comment]
Like [this](https://github.com/golang-migrate/migrate/tree/master/cmd/migrate#versioned)?

**Comment by dhui** [comment]
Feel free to open any PRs to add docs as you've described

**Comment by dhui** [comment]
Also note, `make` is not the recommended way to build `migrate`. It's just what's used to release cross platform CLI builds.

**Comment by vaibhav-kaushal** [comment]
> Like [this](https://github.com/golang-migrate/migrate/tree/master/cmd/migrate#versioned)?

Yes. There is no link to that document and I did not even know that it existed. 

> Feel free to open any PRs to add docs as you've described

Sure. I will add a link to that document in a PR. 

Thanks for the help.
