### ISSUE TITLE
"error: can't read limit argument N" on "up" command

### ISSUE THREAD

**Issue by vibridi** [golang-migrate/migrate#467]
**Describe the Bug**
Running the command `migrate -source <source> -database <connection_string> up` gives the following error: `error: can't read limit argument N`

**Steps to Reproduce**
1. I ran migrate with the following options: see above
2. See error

**Expected Behavior**
A successful migration

**Migrate Version**
master branch
Obtained by running: `go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate`

**Loaded Database Drivers**
postgres
Obtained by running: see above

**Go Version**
Go 1.15

**Stacktrace**
error: can't read limit argument N

**Additional context**
The bug is likely caused by the recent merge `8a56273`, [which shows](https://github.com/golang-migrate/migrate/blob/master/internal/cli/main.go#L232):
```
		if flag.NArg() > 0 {
			n, err := strconv.ParseUint(flag.Arg(1), 10, 64)
			if err != nil {
				log.fatal("error: can't read limit argument N")
			}
			limit = int(n)
		}
```
when a few lines above:
```
upSet, helpPtr := newFlagSetWithHelp("up")
```
Changing L232 to `if upSet.NArg() > 0` does not produce the error anymore.

**Comment by jalerson** [comment]
I'm having exactly the same issue 👍  thanks for reporting!

**Comment by dhui** [comment]
Thanks for reporting this issue! Just pushed a fix for this. Lemme know if this is still an issue

**Comment by hbakhtiyor** [comment]
@dhui still have the issue

`migrate -database postgres://postgres:1234@localhost:5432/dbname?sslmode=disable  -path ./migrations/ up [step]`

**Comment by stt106** [comment]
is this fixed? I am having this issue now.

> Thanks for reporting this issue! Just pushed a fix for this. Lemme know if this is still an issue
