### ISSUE TITLE
Bug in SQL Server locking code?

### ISSUE THREAD

**Issue by gormv** [golang-migrate/migrate#473]
**Describe the Bug**

SQL Server migration doesn't protect multiple migrations at the same time?

The bug is on [this line](https://github.com/golang-migrate/migrate/blob/master/database/sqlserver/sqlserver.go#L172)

`if _, err = ss.conn.ExecContext(context.Background(), query, aid, &status); err == nil && status > -1 {
`

This looks wrong, shouldn't it be:

`if err = ss.conn.QueryRowContext(context.Background(), query, aid).Scan(&status); err == nil && status > -1 {
`

**Comment by dhui** [comment]
Are you encountering an issue?
`ExecContext` [should be correct](https://github.com/denisenkom/go-mssqldb#return-status)

**Comment by gormv** [comment]
@dhui You are absolutely correct. I just heard this from a team member that there was problems with locking and we thought this was the issue. Sorry for the report and I will investigate further. Thanks!
