### ISSUE TITLE
Better error handling with invalid migrations.

### ISSUE THREAD

**Issue by SJrX** [golang-migrate/migrate#479]
**Is your feature request related to a problem? Please describe.**
We had an error "can't acquire lock" in go-migrate cli. We couldn't figure out what the issue was as the lock was being acquired. We stumbled upon #199  and it gave us a hint that there were problems with the down migrations, which it was.

**Describe the solution you'd like**
Logging that better describes the issue.

**Describe alternatives you've considered**
N/A

**Additional context**
#199

**Comment by dhui** [comment]
@SJrX What was what the issue with the down migrations and what DB and source drivers are you using?

**Comment by SJrX** [comment]
Good question, I was using mongodb. I believe the issue (I'm a messenger), was that we had a drop index for an index that didn't exist in the down issue, but I assumed (based on #199) that it was a larger issue. 

I put this as a place holder issue and will hope to dig into the source code and come up with a reproducable test case and maybe a patch of some kind.

**Comment by SJrX** [comment]
I can't reproduce this issue (I was reporting this second hand), I think we can close this.
