### ISSUE TITLE
Why is the "no change" error used?

### ISSUE THREAD

**Issue by mogi86** [golang-migrate/migrate#485]
Sorry, this is more of a question than a request. Please allow me to ask you a question.

I used [`Up()`](https://github.com/golang-migrate/migrate/blob/a53e6fc425743533d66df19fcd275344cfeea6d5/migrate.go#L267) to run migration.
And I received `no change` error when no migration version update.

I'd like to know why is the error returned when no migration version update.
I thought no error would be returned if there were no updates.
Is there any reason why migration process need to return any error?

Should I avoid error myself if I don't prefer the error?

**Comment by dhui** [comment]
This decision predates my involvement with the project, but my *guess* is that the original author needed/wanted to differentiate between a success with changes applied and a success with no changes applied

**Comment by mogi86** [comment]
Thank you for the reply. I understand the background (could be a guess).

**Comment by tomqwpl** [comment]
Yeah, this is annoying.
If you write the naive go code to perform a migrate in your program, you write something like:
```
err = m.Up()
if err!=nil {
  log.Fatal().Err(err).Msg("Failed to migrate database)
}
```
This doesn't work, you have to filter out the ErrNoChange error first.

**Comment by justinclift** [comment]
Yeah.  This should probably be changed for the next major release (eg "breaking change time"). :wink:
