### ISSUE TITLE
When I execute "make test-short .... DATABASE='postgres'` all database test are executed

### ISSUE THREAD

**Issue by stephane-klein** [golang-migrate/migrate#489]
I try to execute [`/database/postgres/postgres_test.go`](https://github.com/golang-migrate/migrate/blob/master/database/postgres/postgres_test.go) test.

I have executed `make test-short SOURCE='file go_bindata' DATABASE='postgres'` like explained in [`CONTRIBUTING.md`](https://github.com/golang-migrate/migrate/blob/master/CONTRIBUTING.md) and I have this output: https://gist.github.com/stephane-klein/c1be2bb17cd43dc0971ad34dd1ed10ad

I don't understand why all database tests are executed.

Where `DATABASE='postgres'` is used?

Where is my mistake?

Best regards,
Stéphane

**Comment by dhui** [comment]
That's b/c the `test` target in the `Makefile` runs `go test ./...`. To only test the postgres DB driver, run `go test ./database/postgres`

**Comment by stephane-klein** [comment]
Thanks, I can execute this with success:

```
go test ./database/postgres -v --run Test_quoteIdentifier
```
