### ISSUE TITLE
How To Migrate Oracle Database?

### ISSUE THREAD

**Issue by koy0755** [golang-migrate/migrate#498]
Dose it support Oracle? How tomigrate a oracle database?

**Comment by dhui** [comment]
Oracle is not supported since they don't offer a public image to test against. But you could try this open [PR](https://github.com/golang-migrate/migrate/pull/341) to add an Oracle db driver.

**Comment by Scuilion** [comment]
Would the following be acceptable to tests against:
https://hub.docker.com/r/gvenzl/oracle-xe
Seems to be created and maintained by and oracle employee.
https://geraldonit.com/2021/08/15/oracle-xe-docker-images/

**Comment by dhui** [comment]
That looks promising!
It appears that that [project is Apache 2](https://github.com/gvenzl/oci-oracle-xe/blob/main/LICENSE). Do you know if all of its upstream dependencies are also permissive?

**Comment by gvenzl** [comment]
Hi @dhui, my project is indeed Apache V2.

Furthermore, Oracle does provide a fully free Oracle Database edition called *[Oracle Database Express Edition](https://oracle.com/xe)*, which is what you find in these images. This database edition comes under the Oracle Free Use Terms and Conditions license, which is documented in the [Oracle Database Licensing Guide](https://docs.oracle.com/en/database/oracle/oracle-database/21/dblic/Licensing-Information.html#GUID-AB354617-6614-487E-A022-7FC9A5A08472). The license text itself is available under https://www.oracle.com/downloads/licenses/oracle-free-license.html and also ships with Oracle Database Express Edition.

You will find it to be a very short license that gives you the following rights:

> Oracle grants to You, as a recipient of this Program, a nonexclusive, nontransferable, limited license to, subject to the conditions stated herein, **(a) internally use the unmodified Programs for the purposes of developing, testing, prototyping and demonstrating your applications, and running the Programs for your own internal business operations; and (b) redistribute unmodified Programs and Programs Documentation, under the terms of this License, provided that You do not charge Your end users any additional fees for the use of the Programs. You may make copies of the Programs to the extent reasonably necessary for exercising the license rights granted herein and for backup purposes.** You are granted the right to use the Programs to provide third party training in the use of the Programs and associated Separately Licensed Technology only if there is express authorization of such use by Oracle on the Program's download page or in the Program Documentation.

What it basically means is that you are free to use and distribute Oracle Database XE as long as you don't change (as in disassemble and/or hack the binaries provided) or charge for the Oracle Database software.
So regardless of whether or not you would like to use my Docker images, you can also just download, install and run Oracle Database directly on your machine as well, if you like, or containerize it yourself.

There is also a fully open-source Go driver for Oracle Database as well: https://github.com/godror/godror (Apache V2 and UPL 1)

**Comment by dhui** [comment]
Thanks for the response @gvenzl !

This should unblock Oracle support.
