### ISSUE TITLE
sqlite3: Unable to open database file if directory contains whitespace

### ISSUE THREAD

**Issue by ganboonhong** [golang-migrate/migrate#499]
**Describe the Bug**
Unable to open sqlite database file if directory contains whitespace. An error was returned while trying to open a sqlite file located under `$HOME/Library/Application Support/` (which is returned by  https://pkg.go.dev/os#UserConfigDir).

**Steps to Reproduce**
Try running this unit test by replacing `sqlite3-driver-test` with `sqlite3 driver test`:
https://github.com/golang-migrate/migrate/blob/550193e3e0b3d8f4858a625ed9b468751cdeb620/database/sqlite3/sqlite3_test.go#L20

you will see the following error:

```
--- FAIL: Test (0.00s)
    sqlite3_test.go:29: DB path : /var/folders/65/j4_h7qkd5xl9qmxlxzbnjj4r0000gn/T/sqlite3 driver test573028882/sqlite3.db
    sqlite3_test.go:34: unable to open database file
FAIL
exit status 1
FAIL	github.com/golang-migrate/migrate/v4/database/sqlite3	0.322s
```

**Expected Behavior**
Expect no error.

**Migrate Version**
v4.14.1

**Loaded Source Drivers**
github

**Loaded Database Drivers**
sqlite3

**Go Version**
go version go1.15.6 darwin/amd64

**Comment by EarlWare** [comment]
So this issue is closed, but only the test case was added?   

Im still running into this same issue, and it appears the source in the actual sqlite3.go file still contains produces this issue( .String() on a net/URL returns escaped paths, so spaces get replaced with `%20` causing things to fail)
