### ISSUE TITLE
Replace the original repo in go-awesome

### ISSUE THREAD

**Issue by dcormier** [golang-migrate/migrate#5]
As the original repo has been abandoned (mattes/migrate#311), this fork should replace the original repo in [go-awesome](/avelino/awesome-go#database).

**Comment by mattes** [comment]
this is great. Let me update the readme. also, maybe someone can add me as a contributor?

**Comment by dcormier** [comment]
Sure would be nice to have more than one contributor.

**Comment by dhui** [comment]
@mattes I've added you as a collaborator to both the org and the repo

**Comment by mattes** [comment]
I'll update the README in migrate. Is there any way to transfer the issues as well?

**Comment by dhui** [comment]
It doesn't look like there's a way to transfer issues between github repos: https://github.com/holman/ama/issues/413

But there's an open source tool that uses the Github API to move issues: https://github.com/google/github-issue-mover

It may be easier to give others admin access to the original repo, coveralls, and package cloud. Then we could close fork after merging/back-porting the changes.

**Comment by dhui** [comment]
Looks like this was done: https://github.com/avelino/awesome-go/pull/1930
