### ISSUE TITLE
Add support for vgo (go.mod file)

### ISSUE THREAD

**Issue by maxekman** [golang-migrate/migrate#50]
Will make it easier for other projects to use this with vgo.

It should be simple as there is already a Gopkg.lock file: `vgo install ./...`

**Comment by dhui** [comment]
My understanding is that vgo is still in flux and isn't production ready yet.
Since people are using migrate in production, I'd hold off on supporting vgo in migrate until vgo has been adopted into the official go toolchain.

https://github.com/golang/go/wiki/vgo#current-state

**Comment by dhui** [comment]
If vgo changes their file format in a backwards incompatible way, then migrate would also need to make a backwards incompatible release, which I'd like to avoid unless absolutely necessary. Namely, if the go.mod file format changes or is replaced with another format (seems unlikely given this issue: https://github.com/golang/go/issues/23966), then existing projects using vgo and migrate may be blocked by a new migrate release. I'd like to avoid this issue all together by not officially supporting vgo until it's production ready.

In the meanwhile, feel free to fork the package to support vgo and open a PR once vgo has been finalized.

**Comment by maxekman** [comment]
Ok, reson enough!

**Comment by dhui** [comment]
Done in https://github.com/golang-migrate/migrate/commit/16f2b1736e65c1145829718d453d99d9f0f32b8d
