### ISSUE TITLE
Improvement to Schema Migrations Tracking

### ISSUE THREAD

**Issue by Rheisen** [golang-migrate/migrate#502]
### Feature request
The schema_migrations table only keeps track of the "latest" migration file that has been run. It doesn't appear to keep track of whether it has seen a migration before or not, and so it has the potential to skip migrations.

Scenario (underscores and ellipses used for clarity/brevity): 

1. Production schema_migrations table has 2021_01_25... as the schema version of the database.
2. Developer 1 creates a migration at 2021_01_26_... on feature/jira-101_add-user-table
3. Developer 2 creates a migration at 2021_01_27_... on feature/jira-101_add-messages_table
4. Developer 2 finishes their feature and merges into develop
5. Develop has a release branch cut and migrations are run in production.
6. schema_migrations table in production now has 2021_01_27... as the schema version of the database.
7. Developer 1 finishes their feature and merges into develop
8. Develop has a release branch cut, but the migration is not run in production since 2021_01_26... < 2021_01_27...

Potential Solution:
- Create records for each migration file encountered in the schema_migrations table.
- When running migrations, run a migration file if there is no matching record in the schema_migrations table.

**Comment by dhui** [comment]
Would this [design](https://github.com/golang-migrate/migrate/issues/470) fit your needs? Please provide feedback in that issue.
Closing as a duplicate issue
