### ISSUE TITLE
Generate Migrations with Consistent Timezone

### ISSUE THREAD

**Issue by Rheisen** [golang-migrate/migrate#503]
### Feature request

It appears that `migrate create` generates timestamps in the timezone that the user is working in. When working across different timezones, this can be problematic (esp. when considering the behavior in [Issue 502](https://github.com/golang-migrate/migrate/issues/502)).

Potential solution:
1. Generate all timestamps in UTC

Alternate solution:
1. Provide a flag option to specify the timezone (e.g. `migrate create -dir db/migrations -tz utc -ext sql <migration-name>`)

**Comment by dhui** [comment]
Related old PR: https://github.com/golang-migrate/migrate/pull/241#pullrequestreview-257072983

**Comment by nronas** [comment]
@dhui should we close this one in favor of https://github.com/golang-migrate/migrate/pull/509 ?

**Comment by dhui** [comment]
Yep, thanks for finding this @nronas !
