### ISSUE TITLE
Change Engine=TinyLog to Engine=MergeTree for MigrationsTable

### ISSUE THREAD

**Issue by MrVongay** [golang-migrate/migrate#505]
Hi,
really thanks for this helpful tool. We use it in our project.
Unfortunately we faced with broken process of migrations during backup/restore via https://github.com/AlexAkulov/clickhouse-backup. Please let me elaborate on this: sometimes it is needed to create backup of clickhouse before testing on out stage env and restore it for imitation of "clean" migration. The clickhouse-backup tool creates backup only tables with Engine=MergeTree, but not with Engine=TinyLog like it is here: https://github.com/golang-migrate/migrate/blob/master/database/clickhouse/clickhouse.go#L223. In this case we are loosing table MigrationsTable and all the data which was filled before during previous migrations, but database has migrates state because it was restored from backup via clickhouse-backup tool.

Can you please make the change from "Engine=TinyLog" to "Engine=MergeTree" for MigrationsTable in line 223 here: https://github.com/golang-migrate/migrate/blob/master/database/clickhouse/clickhouse.go#L223 ?

Thanks for any advice. Regards.

**Comment by dhui** [comment]
Thanks for reporting the issue and providing context!

Instead of change the [engine](https://clickhouse.tech/docs/en/engines/table-engines/), let's make it configurable and default to `TinyLog` for backwards compatibility. I don't have time to write the PR myself, but can review any PRs you open.

**Comment by WesleyBatista** [comment]
Having the same issue here. Unfortunately, not so good at golang :/
