### ISSUE TITLE
Go build fails in docker with error "no buildable Go source files"

### ISSUE THREAD

**Issue by namratachaudhary** [golang-migrate/migrate#51]
At the point in dockerfile where the command is 

```bash
RUN go get -v -t  .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/app
``` 

The build fails with error 

```bash
go build github.com/golang-migrate/migrate/database/postgres: no buildable Go source files in /go/src/github.com/golang-migrate/migrate/database/postgres
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/app' returned a non-zero code: 1
```

In main.go, I'm using this , like 

```go
import (
         "github.com/golang-migrate/migrate"
	 "github.com/golang-migrate/migrate/database/postgres"
)

func main() {
         // conn is a local variable, initalized in `init()`
	driver, err := postgres.WithInstance(conn.DB(), &postgres.Config{})
	m, err := migrate.NewWithDatabaseInstance(
		"file://migrations",
		"postgres",
		driver,
	)

        if err = m.Up(); err != nil && err.Error() != "no change" {
		m.Down()
		panic(err)
	}
}
```

**Comment by dhui** [comment]
It looks like you're using your own Dockerfile, not the one in `migrate` since that one uses `go get -v ./...`

The master branch of `migrate` now uses `dep`, so I'd use that instead. e.g. `dep ensure -vendor-only` If you need to pin to a released version of `migrate`, you'll need to wait for the next version which will officially support `dep` (and provide a docker image for the CLI).

**Comment by namratachaudhary** [comment]
Hey @dhui 
I'm trying to use it as a package, and not cli, in which case `go get -v` should work, right? I even tried using dep by enforcing master in Gopkg.toml

```
[[constraint]]
  branch = "master"
  name = "github.com/golang-migrate/migrate"
```

But the go build still fails. Is there any other way around this?

**Comment by dhui** [comment]
`go get` and `dep` should work. Do you have any errors running `go get` or `dep ensure`?

Do you have more info for your build/compile errors? My guess is that the build issues are internal to your project/code as `migrate` is building fine in TravisCI.

**Comment by namratachaudhary** [comment]
I changed the dep installation to via-curl , and it worked. 
No idea what changed, but this seems to be working fine.
Maybe I'll debug more and post findings. 

Thanks a lot 😄

**Comment by dmmulroy** [comment]
@namratachaudhary did you ever figure out what was happening?  I'm having this same issue on our jenkins server but not locally.
