### ISSUE TITLE
I'm not getting to install golang-migration in my container

### ISSUE THREAD

**Issue by baucosta** [golang-migrate/migrate#511]
Hi guys!!! I'm updating my docker image with the new golang version: 1.16.0. I'm using the following image:

FROM golang:1.16.0-alpine3.13

My development environment is being running with docker-compose. When I build my new image, it is showing the following error:

go get: module github.com/golang-migrate/migrate@upgrade found (v3.5.4+incompatible), but does not contain package github.com/golang-migrate/migrate/cmd/migrate

I've added to my Dockerfile the following commands:

RUN go get -u -d github.com/golang-migrate/migrate/cmd/migrate
RUN cd go/src/github.com/golang-migrate/migrate/cmd/migrate \
    && git checkout v4.14.1\
    go install -tags 'mysql' -o /go/bin/migrate github.com/golang-migrate/migrate/v4/cmd/migrate@v4.14.1

I took as a base the following steps:

https://github.com/golang-migrate/migrate/tree/master/cmd/migrate#with-go-toolchain

I've replaced the first line for this:

RUN go get -u -d github.com/golang-migrate/migrate/v4/cmd/migrate

It did not work either, but showed the following error:

/bin/sh: cd: line 1: can't cd to /go/src/github.com/golang-migrate/migrate/cmd/migrate: No such file or directory

Best regards

**Comment by dhui** [comment]
You might have some issue with your path or other setup/config. This worked for me:
```shell
$ docker run -it --rm golang:1.16.0-alpine3.13
/go # apk add git
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/6) Installing brotli-libs (1.0.9-r3)
(2/6) Installing nghttp2-libs (1.42.0-r1)
(3/6) Installing libcurl (7.74.0-r0)
(4/6) Installing expat (2.2.10-r1)
(5/6) Installing pcre2 (10.36-r0)
(6/6) Installing git (2.30.1-r0)
Executing busybox-1.32.1-r3.trigger
OK: 19 MiB in 21 packages
/go # go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
go: downloading github.com/golang-migrate/migrate v1.3.2
go: downloading github.com/golang-migrate/migrate/v4 v4.14.1
go: downloading github.com/golang-migrate/migrate v3.5.4+incompatible
go: downloading github.com/hashicorp/go-multierror v1.1.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/hashicorp/errwrap v1.0.0
/go # which migrate
/go/bin/migrate
/go # migrate -version
dev
/go # migrate
Usage: migrate OPTIONS COMMAND [arg...]
       migrate [ -version | -help ]

Options:
  -source          Location of the migrations (driver://url)
  -path            Shorthand for -source=file://path
  -database        Run migrations against this database (driver://url)
  -prefetch N      Number of migrations to load in advance before executing (default 10)
  -lock-timeout N  Allow N seconds to acquire database lock (default 15)
  -verbose         Print verbose logging
  -version         Print version
  -help            Print usage

Commands:
  create [-ext E] [-dir D] [-seq] [-digits N] [-format] NAME
	   Create a set of timestamped up/down migrations titled NAME, in directory D with extension E.
	   Use -seq option to generate sequential up/down migrations with N digits.
	   Use -format option to specify a Go time format string. Note: migrations with the same time cause "duplicate migration version" error. 

  goto V       Migrate to version V
  up [N]       Apply all or N up migrations
  down [N]     Apply all or N down migrations
  drop [-f] [-all]    Drop everything inside database
	Use -f to bypass confirmation
	Use -all to apply all down migrations
  force V      Set version V but don't run migration (ignores dirty state)
  version      Print current migration version

Source drivers: file
Database drivers: mysql, stub
/go # exit
$
```

**Comment by baucosta** [comment]
Hi there!!! You're right. It worked for me as well. However, that way has been written this section:

https://github.com/golang-migrate/migrate/tree/master/cmd/migrate#unversioned

That's perfect! But, when I try with Go toolchain, it did not work for me. I wanted let you know. Before, I was working with the following image: golang:1.15.8-alpine3.13. That was working. When I've updated my Dockerfile to  golang:1.16.0-alpine3.13, with Go toolchain did not work. Anyway, I appreciate your attention.

**Comment by dhui** [comment]
With `go install`, there's no need to fetch via `git` yourself. But if you want to checkout the code via `git`, then `go build` should work.

**Comment by baucosta** [comment]
Great!!!! Thanks.
