### ISSUE TITLE
Replace lib/pq with pgx/stdlib as postgres driver

### ISSUE THREAD

**Issue by dzbee** [golang-migrate/migrate#512]
**Is your feature request related to a problem? Please describe.**

The current postgres driver used by `migrate` is `lib/pq`, which is [currently in maintenance mode](https://github.com/lib/pq#status). The maintainers of `lib/pq` encourage users to change over to `pgx`. Beside the fact that `lib/pq` will eventually be disfavored relative to `pgx` in the community (if it's not already), dependence on the `lib/pq` driver has blocked our org from upgrading to Go 1.15 (see outstanding [`lib/pq` branch](https://github.com/lib/pq/tree/go1.15)), and we'd like to remove the `lib/pq` dependency while continuing to use `migrate`.

**Describe the solution you'd like**

I propose that `pgx/stdlib` replace the `lib/pq` driver for providing postgres support for `migrate`, [in the spirit of the outlook outlined in the FAQ](https://github.com/golang-migrate/migrate/blob/master/FAQ.md#can-i-maintain-my-driver-in-my-own-repository).

**Describe alternatives you've considered**

Our current solution in our org is to perform the database migration with `migrate` and open a separate long-lived database connection for app support with the `pgx/stdlib` driver to limit the impact of the `lib/pq` dependency. But in the long term, the community undoubtedly will have to move away from `lib/pq` entirely.

**Comment by dhui** [comment]
Thanks for raising this issue!

Is `pgx/stdlib` a drop-in replacement for `lib/pg`?
Do you know if `lib/pq` and `pgx/stdlib` support the same [DSN](https://pkg.go.dev/github.com/lib/pq#hdr-Connection_String_Parameters)?

I see these `pgx` swapping issues, which gives me pause to switch:
* https://github.com/lib/pq/issues/1022
* https://github.com/lib/pq/issues/1010
* https://github.com/lib/pq/issues/971#issuecomment-636612748 (increased binary size due to `pgx` dependencies)

@dzbee Have you tried switching out the driver and running tests?

Does anyone want to stay on `lib/pq`?
I'm hesitant to switch until we gather more data.

**Comment by dzbee** [comment]
Replacing the driver itself is as simple as swapping the package and changing the string identifier for the driver in `sql.Open`; `pgx/stdlib` supports standard DSN and has replacement functions for `lib/pq`:
https://pkg.go.dev/gopkg.in/jackc/pgx.v3#ParseDSN
https://pkg.go.dev/gopkg.in/jackc/pgx.v3#ParseConnectionString
https://pkg.go.dev/gopkg.in/jackc/pgx.v3#ParseURI
https://pkg.go.dev/gopkg.in/jackc/pgx.v3#ParseEnvLibpq

There are a few other places where `lib/pq` is used in the postgres driver for `migrate` related to error handling and query building, but I don't believe those changes are very complicated either. You can view a diff of a speculative branch I made here: https://github.com/golang-migrate/migrate/compare/master...nicheinc:feature/pgx-support. That branch is untested at the moment, but I believe it illustrates the (limited) extent of the changes required. I'll report back again once I've had a chance to test and fix any bugs.

I wanted to respond to some of the issues you linked in the meantime:

1. https://github.com/lib/pq/issues/1022 -- I'm not sure what this commentor is talking about with regards to lack of float64 support; reading through the linked issues, the `pgx` maintainers don't acknowledge that "PGX can't handle float64" as the commentor claims ([as another commentor explained](https://github.com/jackc/pgx/issues/905#issuecomment-758692958), the proper scanner type for float64 is `pgtype.Float8`), but rather `pgx` is seemingly more strict about enforcing type agreement than `lib/pq` is. The [types defined in `pgtype`](https://godoc.org/github.com/jackc/pgtype) are also easily extensible, seeing as how the scanner interface is fairly simple. As for the connection pool issue the commentor raises, [it appears the issue was resolved in 2019](https://github.com/jackc/pgx/issues/494).
2. https://github.com/lib/pq/issues/1010 -- I don't think this issue has significant implications for `migrate` since it sounds like timezones are handled by the client, not the database, so there as far as I can tell there should be no implication for schema migrations. The issue raised about reconnects should be handled in `pgx/stdlib` at least: https://github.com/jackc/pgx/issues/672#issuecomment-738503003
3. https://github.com/lib/pq/issues/971#issuecomment-636612748 -- In my speculative branch, it appears that only two additional dependencies, `gofrs/uuid` and `jackc/fake`, are introduced besides the direct `pgx` imports. Unless I messed something up, when I built the binary there was no appreciable change in size. Also from my reading of the linked issue, it appears the complaint about increased binary size is not due to `pgx` dependencies, but rather because of Kerberos support added to `lib/pq`, and the commentor was merely drawing a distinction between dependencies in `lib/pq` and `pgx`, not saying that `pgx` caused their binaries to grow

**Comment by dzbee** [comment]
I've confirmed that the happy path is working for our use case of using a file source for migrating a postgres database in app using https://github.com/nicheinc/migrate/tree/feature/pgx-support, and with minor updates to the expected error reporting in testing (in particular to include the SQL error code), that branch is also passing testing. I've opened up a PR: https://github.com/golang-migrate/migrate/pull/517
