### ISSUE TITLE
Using Go 1.16 io/fs as a source for DB migrations

### ISSUE THREAD

**Issue by fasmat** [golang-migrate/migrate#514]
With golang 1.16 the io/fs package was introduced that among other things allows the use of embedded files in go programs.

Is it already possible to embed migrations into a binary and execute them with golang-migrate?

I'm not yet using golang-migrate but I'm looking for a library that can potentially do this. I've seen that golang-migrate has this interface https://pkg.go.dev/github.com/golang-migrate/migrate/v4/source#Driver. I assume one would need to write a driver implementing the interface and mapping onto https://golang.org/pkg/io/fs/#FS to use golang 1.16 embedded files?

**Comment by nekinie** [comment]
Posting this just in-case it helps someone, I'm using embed but you could in theory use any file system.

```
package cassandra

import (
	"embed"
	"fmt"
	"net/http"

	"github.com/gocql/gocql"
	"github.com/golang-migrate/migrate/v4"
	"github.com/golang-migrate/migrate/v4/database/cassandra"
	"github.com/golang-migrate/migrate/v4/source"
	"github.com/golang-migrate/migrate/v4/source/httpfs"
)

//go:embed migrations
var static embed.FS

func init() {
	source.Register("embed", &driver{})
}

type driver struct {
	httpfs.PartialDriver
}

func (d *driver) Open(rawURL string) (source.Driver, error) {
	err := d.PartialDriver.Init(http.FS(static), "migrations")
	if err != nil {
		return nil, err
	}

	return d, nil
}
```

and

```
driver, err := cassandra.WithInstance(session, config)
if err != nil {
	return err
}

migrator, err := migrate.NewWithDatabaseInstance("embed://", "cassandra", driver)
if err != nil {
	return err
}
```

**Comment by dhui** [comment]
Looks like you've discovered the [httpfs source driver](https://pkg.go.dev/github.com/golang-migrate/migrate/v4/source/httpfs).
Also, if you want to track `io/fs` integration progress, see: https://github.com/golang-migrate/migrate/issues/471
