### ISSUE TITLE
Question: Race Condition Safety with Postgres

### ISSUE THREAD

**Issue by ivanduka** [golang-migrate/migrate#519]
It's not a feature request, but a question.
As I understand, the algorithm for migrations are the following when going from version 1 to 2 for example:
1. Mark the database as version 2 and set dirty to true in `schema_migrations`
2. If the migration fails, leave the `schema_migrations` as is (v2 + dirty == true)
3. If the migration succeeds, change dirty to false

The question is: if I run several concurrent deployments, is it safe for all of them to initiate the same migration?
Is it possible for a data race to occur where the flag is set to dirty, but right before that another deployment also starts a migration?
I would imagine there is some kind of a table lock acquired before setting the version to dirty?

**Comment by dhui** [comment]
This depends on the DB driver's implementation of [`Lock()`](https://pkg.go.dev/github.com/golang-migrate/migrate/v4@v4.14.1/database#Driver). Some will lock on the DB, some will only lock in the migrate process (not useful if running on multiple machines), and some won't lock at all.

Postgres will [use](https://github.com/golang-migrate/migrate/blob/v4.14.1/database/postgres/postgres.go#L169) an advisory lock and is safe to use with multiple machines.

**Comment by ivanduka** [comment]
Thank you, all clear now :)
