### ISSUE TITLE
godror support

### ISSUE THREAD

**Issue by vtolstov** [golang-migrate/migrate#531]
**Is your feature request related to a problem? Please describe.**
I'm really need godror (oracle) support

**Describe the solution you'd like**
add godror support like sqlite3/postgresql

**Describe alternatives you've considered**
??

**Comment by dhui** [comment]
Official support won't be provided until there's an available docker image to test against. You're welcome to try this [PR](https://github.com/golang-migrate/migrate/pull/341) on your own.
