### ISSUE TITLE
ClickHouse insert statement error

### ISSUE THREAD

**Issue by NAlexandrov** [golang-migrate/migrate#534]
**Describe the Bug**
I've got an error: insert statement supported only in the batch mode (use begin/commit)
But ClickHouse doesn't support transaction

**Steps to Reproduce**
1. My migrations look like:

```sql
CREATE TABLE extensions
(
	key String,
	extension String,
	description Nullable(String)
) ENGINE MergeTree()
ORDER BY key
SETTINGS index_granularity = 8192;

INSERT INTO extensions (key, extension, description) VALUES
('.!bt', '.!bt', 'BitTorrent Partially Downloaded File (Bram Cohen; now maintained by BitTorrent, Inc.)'),
('.!c', '.!c', 'Graphics Converter Pro');
```

2. I ran migrate:

```
docker run --rm -v $(pwd)/migrations:/migrations --network host migrate/migrate -path=/migrations -database "clickhouse://localhost:9000?x-multi-statement=true" "-verbose" "up"
```

3. See error in stacktrace

**Expected Behavior**
Migration will be successful

**Migrate Version**
v4.14.1

**Loaded Source Drivers**
s3, github-ee, godoc-vfs, gcs, file, bitbucket, github, gitlab, go-bindata

**Loaded Database Drivers**
cockroach, cockroachdb, firebirdsql, mongodb, mysql, crdb-postgres, firebird, stub, neo4j, redshift, spanner, sqlserver, cassandra, clickhouse, mongodb+srv, postgres, postgresql

**Stacktrace**
```
2021/03/29 17:16:18 Start buffering 1/u extensions
2021/03/29 17:16:18 Read and execute 1/u extensions
2021/03/29 17:16:18 error: migration failed in line 0: 

INSERT INTO extensions (key, extension, description) VALUES
('.!bt', '.!bt', 'BitTorrent Partially Downloaded File (Bram Cohen; (details: insert statement supported only in the batch mode (use begin/commit))
```

**Comment by dhui** [comment]
The multistmt parsing is naive. It simply tokenizes on `;` and you have a `;` in your query: `(Bram Cohen;`

**Comment by zhaoyanpu** [comment]
The root cause of this problem is that the ClickHouse Client must be placed in a TX when executing INSERT statements.

see https://github.com/ClickHouse/clickhouse-go/blob/master/clickhouse.go
