### ISSUE TITLE
sqlite3: wrong driver in test

### ISSUE THREAD

**Issue by kewde** [golang-migrate/migrate#54]
https://github.com/golang-migrate/migrate/blob/master/database/sqlite3/sqlite3_test.go#L52

The sqlite3 test is  loading the `ql`, I believe that should be sqlite3`?

I'm also getting the error on sqlite3 (using the library API).
```
2018/06/13 20:23:22 source driver: unknown driver file (forgotten import?)
```

Importing the sqlite3 driver didn't help either.

**Comment by dhui** [comment]
Thanks for opening a new issue!

As mentioned in the [docs](https://github.com/golang-migrate/migrate#use-in-your-go-project), have you tried importing the sqlite3 DB driver? e.g. `import _ "github.com/golang-migrate/migrate/database/sqlite3"`

**Comment by kewde** [comment]
I solved the error on my end.
I was using the GitHub import, instead of the file import.

```
_ "github.com/golang-migrate/migrate/source/file"
```
instead of source/github did the trick!
