### ISSUE TITLE
migrate CLI inside docker

### ISSUE THREAD

**Issue by taosx** [golang-migrate/migrate#544]
**Is your feature request related to a problem? Please describe.**
I enjoy being able to pack my CLIs as docker containers that you can run and create the necessary files but this requires some user permission modifications inside the docker container. 

**Describe the solution you'd like**
An example would be generating the migration files like this but with the right permission so you don't need to run chown afterwards (assos is my current user on host):

```
❯ docker run --rm -v `pwd`:/home/default/migrations && \
        migrate/migrate create -ext sql -dir /home/default/migrations/user_service -seq initial_setup
❯ tree
.
├── user_service
│   ├── 000001_initial_setup.down.sql
│   └── 000001_initial_setup.up.sql
❯ ls -Al user_service
total 0
-rw-r--r-- 1 assos assos 0 Apr 14 16:53 000001_initial_setup.down.sql
-rw-r--r-- 1 assos assos 0 Apr 14 16:53 000001_initial_setup.up.sql
```

**Describe alternatives you've considered**
The alternative would be to `sudo chown -R assos:assos ./user_service` after generating the files

**Additional context**
This is how I currently modified the Dockerfile in order to do what I want it:
<details>
<summary>Dockerfile</summary>
<br>

```dockerfile
FROM golang:1.16-alpine3.13 AS builder

ARG VERSION

ARG USER=default
ENV HOME /home/$USER

ARG USER_ID
ARG GROUP_ID

RUN addgroup -g ${GROUP_ID} -S ${USER} && \
    adduser -u ${USER_ID} -S ${USER} -G ${USER} && \
    chown -R ${USER}:${USER} ${HOME} && \
    apk add --update --no-cache git gcc musl-dev make sudo

USER ${USER}

RUN mkdir ${HOME}/migrate
WORKDIR ${HOME}/migrate

ENV GO111MODULE=on

COPY --chown=${USER}:${USER} go.mod go.sum ./

RUN go mod download

COPY --chown=${USER}:${USER} . ./

RUN mkdir ./build && make build-docker

## Second step

FROM alpine:3.13

ARG USER=default
ENV HOME /home/$USER

ARG USER_ID
ARG GROUP_ID

RUN addgroup -g ${GROUP_ID} -S ${USER} && \
    adduser -u ${USER_ID} -S ${USER} -G ${USER} && \
    chown -R ${USER}:${USER} ${HOME} && \
    apk add --update --no-cache ca-certificates sudo

USER ${USER}

COPY --chown=${USER}:${USER} --from=builder ${HOME}/migrate/build/migrate.linux-386 /usr/local/bin/migrate
RUN ln -s /usr/local/bin/migrate ${HOME}

ENTRYPOINT ["migrate"]
CMD ["--help"]

```

</details>

This is how I run it from inside a Makefile:
```
.PHONY: new-migration
new-migration:
	@docker run --rm -v `pwd`:/home/default/migrations migrate create -ext sql -dir /home/default/migrations/user_service -seq $(name)
---
❯ make name=initial_setup new-migration
```

Demo: 
```docker run --rm -v `pwd`:/home/default/migrations ghcr.io/taosx/migrate:4.14.1 create -ext sql -dir /home/default/migrations/user_service -seq initial_setup```

**Comment by dhui** [comment]
I don't think `ARG` in the Dockerfile will help since that's only used at build time, not runtime, so the images on docker hub will use whatever user and groups are specified at build time.

**Comment by taosx** [comment]
You're right, that's the easiest solution that came to mind, I'll look into it again, do you think it's worth the effort?

**Comment by dhui** [comment]
Probably not worth the effort. It's easier to either:
1. wrap your usage of the migrate CLI (via docker) in a shell script and run chown or chmod
2. install the migrate cli via another method
