### ISSUE TITLE
Why do the adapters (postgres, pgx) ignore the config?

### ISSUE THREAD

**Issue by FAQinghere** [golang-migrate/migrate#547]
https://github.com/golang-migrate/migrate/blob/3d5d577b61933c0b7a28cad41058d42dc0c87abb/database/pgx/pgx.go#L452

The config actually has the schema name (potentially already explicitly set), but here it is being ignored unless an orthogonal parameter happens to have some particular value).

**Comment by dhui** [comment]
Good catch! It looks like the `SchemaName` and `MigrationsTableQuoted` config values don't play nicely with each other...
We should default to the config `SchemaName` and overwrite that if the quoted migration table name also specifies a schema. This should be fixed on both the pgx and postgres drivers.

**Comment by dhui** [comment]
@stephane-klein do you have time/bandwidth to address this issue?
[Adding](https://github.com/golang-migrate/migrate/pull/533) the `MigrationsTableQuoted` config broke how the `SchemaName` config is used.

**Comment by FAQinghere** [comment]
To be fair, I believe that config value was never respected consistently in the Postgres driver, going back years. The issue was not introduced by the latest changes. I’m pretty sure that a couple of years ago on some project I simply made it use that config value and suddenly it all worked fine (no need for the quoted table name handling, etc.).

**Comment by stephane-klein** [comment]
Some notes:

- Currently (and before this [commit](https://github.com/golang-migrate/migrate/commit/3d5d577b61933c0b7a28cad41058d42dc0c87abb)), the [`Config.SchemaName`](https://github.com/golang-migrate/migrate/blob/master/database/pgx/pgx.go#L48) is only used by [`Lock()`](https://github.com/golang-migrate/migrate/blob/3d5d577b61933c0b7a28cad41058d42dc0c87abb/database/pgx/pgx.go#L207) and [`Unlock()`](https://github.com/golang-migrate/migrate/blob/3d5d577b61933c0b7a28cad41058d42dc0c87abb/database/pgx/pgx.go#L207) functions.
- The `Config.SchemaName` was introduced in this [commit](https://github.com/golang-migrate/migrate/commit/16d63e3a760ede4e216f53105fce0df0f14037e8).

**Comment by jeffwidman** [comment]
Was this issue fixed by #550?

**Comment by dhui** [comment]
@jeffwidman yep, this is fixed by #550
