### ISSUE TITLE
pgx as a driver scheme (pgx:// instead of postgres://) 

### ISSUE THREAD

**Issue by FAQinghere** [golang-migrate/migrate#548]
This requires a user to munge the connection string before passing it on to the library, which then just munges it back (or parses it into it's components and sets the scheme). 

So a canonical connection string, required by pgx, would start with "postgres[ql]", which the user would then have to change to "pgx" to use the migrate lib, which the migrate lib would then just change back to "postgres". 

Also, since we're explicitly registering the driver with a package level global (via the _ import), what's the point of not just using the same scheme? The driver itself is also passed in upon registration, so should it pretty much "just work"? (I know... famous last words :) )

**Comment by dhui** [comment]
Driver schemes need to be unique to work with the pre-built CLI

**Comment by FAQinghere** [comment]
I see. It’s too bad because the double-munging is not great.
