### ISSUE TITLE
duplicate key value violates unique constraint "pg_type_typname_nsp_index"

### ISSUE THREAD

**Issue by dotchev** [golang-migrate/migrate#55]
We hit an error in our tests similar to #235 
```
pq: duplicate key value violates unique constraint "pg_type_typname_nsp_index" in line 0: CREATE TABLE "schema_migrations" (version bigint not null primary key, dirty boolean not null)
```
What bothers me is that this is not `ErrLocked`. So it seems like the lock does not work as expected.
Or do I get it wrong?
We use Postgres and we call it like this
```go
func updateSchema(db *sqlx.DB) error {
	driver, err := migratepg.WithInstance(db.DB, &migratepg.Config{})
	if err != nil {
		return err
	}
	m, err := migrate.NewWithDatabaseInstance("file://storage/postgres/migrations", "postgres", driver)
	if err != nil {
		return err
	}
	err = m.Up()
	if err == migrate.ErrNoChange {
		logrus.Debug("Database schema already up to date")
		err = nil
	}
	return err
}
```
We use migrate ver 3.2.0
We use [pq](https://github.com/lib/pq) driver

**Comment by dhui** [comment]
Are you able to reproduce the issue using the master branch?

There's an fix to the postgres db driver that'll be in the next release: https://github.com/golang-migrate/migrate/pull/13

**Comment by dotchev** [comment]
We still use the old code. We will try to reproduce with the latest master.

**Comment by dhui** [comment]
FYI, the postgres db driver fix I mentioned above is now in the latest release ([v3.3.0](https://github.com/golang-migrate/migrate/releases/tag/v3.3.0))

**Comment by dhui** [comment]
@dotchev Is this still an issue w/ the latest release?

**Comment by nareshov** [comment]
@dhui i'm facing the same issue also when using the latest code (with `go get -u -d github.com/golang-migrate/migrate/cli`).

when invoked as follows:
```
% migrate -path /go/src/github.com/XYZ/abc/platform/tools/migrations/pgsql/platform/guardian -database 'postgres://u:p@localhost:5432/platform_test?sslmode=disable' down
```

**Comment by dhui** [comment]
Does anyone have steps to reproduce this?

Was there an old `migrate` process/connection that didn't support Postgres advisory locks?
Also, there's a bugfix in the latest release the correctly closes dangling DB connections in Postgres that might help.

**Comment by tsenart** [comment]
Hello!

Here's a [reproducible test command](https://github.com/sourcegraph/sourcegraph/pull/1809) that runs into this. We're [using v4.1.0](https://github.com/sourcegraph/sourcegraph/blob/master/go.mod#L45).

**Comment by tsenart** [comment]
The problem seems to be that `func (*Postgres) ensureVersionTable() error` isn't atomic.

**Comment by tsenart** [comment]
This commit doesn't seem to fix it unfortunately: https://github.com/tsenart/migrate/commit/f6caf3e3329e66171a4a913fd78a1169dbfed277

Nor wrapping it all in a transaction.

**Comment by dhui** [comment]
Fix is in master. I'll cut at new release with this fix in ~1 week.
