### ISSUE TITLE
Migration with mysql transaction fails

### ISSUE THREAD

**Issue by fabioDMFerreira** [golang-migrate/migrate#553]
**Describe the Bug**
A migration with a transaction fails to run in MySQL. 

**Steps to run**

1. Add migration with multiple statements like:
```
START TRANSACTION;
UPDATE table_name SET status=0
UPDATE table_name SET status=1 where condition1
UPDATE table_name SET status=2 where condition2
COMMIT;
```

2. Run up migrations in a go program
```
...
	m, err := migrate.NewWithDatabaseInstance(
		"file://database/migrations",
		"mysql",
		driver,
	)
	if err != nil {
		log.Panicf("failed creating migration instance: %s", err)
	}

	err = m.Up()
	if err != nil && !errors.Is(err, migrate.ErrNoChange) {
		log.Panicf("failed migrating: %s", err)
	}
...
```

3. Program panics with the error
```
failed migrating: migration failed in line 0: START TRANSACTION;
...
COMMIT;
 (details: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '...'
```

**Expected Behavior**
The script with transaction being executed with success.

**Migrate Version**
v4.14.1

**Loaded Source Drivers**
file

**Loaded Database Drivers**
mysql

**Go Version**
go1.16.3 linux/amd64

**Stacktrace**
```
failed migrating: migration failed in line 0: START TRANSACTION;
...
COMMIT;
 (details: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '...'
```

**Additional context**
I have tried to run the same script directly on the database and it runs successfully. I think `go-migrate` is expecting just one instruction.

**Comment by dhui** [comment]
Check the [docs](https://github.com/golang-migrate/migrate/tree/master/database/mysql): use `multiStatements=true`
