### ISSUE TITLE
Query on use of ./migrate force

### ISSUE THREAD

**Issue by garycarr** [golang-migrate/migrate#559]
Running migrate force asks me to input a url which I am not expecting with a cassandra force

```
# get fresh
 wget -qO-  https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
./migrate.linux-amd64

./migrate.linux-amd64 -version
4.14.1

# run force command against cassandra and get the error url cannot be empty
./migrate.linux-amd64 -database cassandra://hostname:9042/dbname force 5
error: URL cannot be empty
```

I get the same issue with cockroach

```
# migrate can do a migration okay against cockroach
./migrate.linux-amd64 -database cockroach://gcarr:test@hostname:26257/dname -path cockroach_migrations up
no change

# but cannot do a force

./migrate.linux-amd64 -database cockroach://gcarr:test@hostname:26257/dname force 5
error: URL cannot be empty
```

I'm not sure what extra info I can provide.  Thanks for your time.

Sorry for the edit, I made a mistake in my original post

**Comment by dhui** [comment]
Try specifying `-path` when using `force`

**Comment by ip75** [comment]
> Try specifying `-path` when using `force`

`the same error: URL cannot be empty`

**Comment by dhui** [comment]
@ip75 Please provide the full command you're using.
Are you specifying both `-path` and `-database`?

**Comment by garycarr** [comment]
Sorry for the long overdue reply.  path does work.

```
./migrate.linux-amd64 -database "cassandra://host:port/keyspace" -path cql_migrations/ force 5
```

**Comment by Suenynis** [comment]
have you solved the problem

**Comment by jamesnicolas** [comment]
I had the same issue. I had to make sure I specify both `-path` and `-database` before `version`.

**Comment by dexterp** [comment]
I'm Running `v4.17.1` with Sqlite, I get the same problem. I downloaded the Binary from GitHub for MacOS Arm64.
Its running with `make` which uses different variables to bash.

```
migrate -path='db/v$(MAJOR_VERSION)' -database="sqlite://tmp/track-$(MAJOR_VERSION).db" -verbose force
error: URL cannot be empty
```
