### ISSUE TITLE
Syntax error returned when running migrations, but no syntax error occurs when I run the migrations manually. 

### ISSUE THREAD

**Issue by caquillo07** [golang-migrate/migrate#573]
### Describe the Bug
Hello! 👋🏼 

Running into a peculiar issue that I have not seen before. I've been using this tool for years now, thank you so much for the hard work! I have used it with CockroachDB and PostgreSQL in the past, and never ran into this issue before, I am using it with MySQL this time. 

I have the follow migration in one file (simplified version):
```sql
create table if not exists features (
  id int unsigned primary key auto_increment,
  display_name text not null
) default charset=utf8 collate=utf8_unicode_ci;

create table if not exists plan_feature (
  feature_id int unsigned
) default charset=utf8 collate=utf8_unicode_ci;
```
When I run my migration command (in code, not the CLI) I get the following error
```sh
migration failed in line 0: create table if not exists features (\n  id int unsigned primary key auto_increment,\n  display_name text not null\n) default charset=utf8 collate=utf8_unicode_ci;\n\ncreate table if not exists plan_feature (\n  feature_id int unsigned\n) default charset=utf8 collate=utf8_unicode_ci;\n (details: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create table if not exists plan_feature (\n  feature_id int unsigned\n) default ch' at line 6)
```

The weird thing is, if I run this migrations manually I get no errors: 
```sql
mysql> START TRANSACTION;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE TABLE IF NOT EXISTS features (
  ->   id int unsigned primary key auto_increment,
  ->   display_name text not null,
  -> ) default charset=utf8 collate=utf8_unicode_ci;
Query OK, 0 rows affected, 2 warnings (0.11 sec)

mysql> 
mysql> CREATE TABLE IF NOT EXISTS `plan_feature` (
  ->   feature_id int unsigned,
  -> ) default charset=utf8 collate=utf8_unicode_ci;
Query OK, 0 rows affected, 2 warnings (0.05 sec)

mysql> COMMIT;
Query OK, 0 rows affected (0.00 sec)

mysql> show tables;
+----------------------------+
| Tables_in_test_db          |
+----------------------------+
| features                   |
| plan_feature               |
| schema_migrations          |
+----------------------------+
3 rows in set (0.00 sec)
```

I noticed that if I split both create calls into separate migrations, it runs without issues. At first I thought it was a transaction issue, but I did run them manually in one transaction and that worked fine. 

I am running MySQL 5.7.31 (I know old, but company is working on updating still); is this an issue with the database itself? or is this a bug in the migration tool? or perhaps I'm the one making a silly mistake am not seeing. 

It is not the end of the world to have multiple files for migrations, but I would like to keep this migrations scoped to an individual change as I used to with other DB, and not a file per table if possible.

### Steps to Reproduce
1. My migrations look like '...' - see above
2. I ran migrate with the following options 
```go
	m, err := gomigrate.NewWithDatabaseInstance(
		"file://migrations", // make customizable?
		"mysql",
		driver,
	)
	if err != nil {
		return errors.Wrap(err, "failed to create migration runner")
	}
	return m.Up()
```
3. See above for error

### Expected Behavior
I expected to be able to run multiple SQL commands per migration file. 

### Migrate Version
e.g. v4.14.1
Obtained from go.mod `github.com/golang-migrate/migrate/v4 v4.14.1`

### Loaded Source Drivers
e.g. file

### Loaded Database Drivers
e.g. mysql

### Go Version
e.g. go version go1.16.2 darwin/amd64
Obtained by running: `go version`

### Stacktrace
N/A

### Additional context
N/A

**Comment by dhui** [comment]
What options are you specifying to the mysql db driver? Did you enable `multiStatements`?

**Comment by caquillo07** [comment]
Hi @dhui, thanks for getting back! We are using gorm for the DB management, here is the initialization code. 

```go
db, err := gorm.Open(mysql.Open(config.DSN.String()), &gorm.Config{
		Logger: newDBLogger(config.LogLevel, ll),
	})
	if err != nil {
		return nil, errors.Wrap(err, "failed to open database")
	}

	d, err := db.DB()
	if err != nil {
		return nil, errors.Wrap(err, "failed to grab raw DB connection")
	}
```

is the `multiStatments` flag required? if so, sounds like we may have to create the driver first and then init gorm with it

**Comment by dhui** [comment]
I'm not familiar with GORM, but if your migration runs multiple statements, it needs to have the multi-statement flag/config enabled.

Out of curiosity, if you're using GORM, why not use the [built-in migration tools](https://gorm.io/docs/migration.html)?

**Comment by caquillo07** [comment]
ahh silly me, you are correct, the `multiStatments`. Thank you! I haven't use mysql much till now, this is not a thing on psql (from what I recall at least).

and not a fan of gorm's migration, the hting I like about golang-migrate is the flexibility. We also own multiple services that all run using this migration too, and only one of those services runs gorm :)

thanks for the hard work, we can close this!
