### ISSUE TITLE
module github.com/golang-migrate/migrate/v4@upgrade found (v4.14.1), but does not contain package github.com/golang-migrate/migrate/v4/source/iofs

### ISSUE THREAD

**Issue by frederikhors** [golang-migrate/migrate#597]
**Describe the Bug**
I'm trying to use the new `go:embed` feature but when I'm trying to

`go get github.com/golang-migrate/migrate/v4/source/iofs`

it throws with:

`go get: module github.com/golang-migrate/migrate/v4@upgrade found (v4.14.1), but does not contain package github.com/golang-migrate/migrate/v4/source/iofs`

**Why?**

**Go Version**
go version go1.16.6 windows/amd64

**Comment by dhui** [comment]
Releases are [blocked](https://github.com/golang-migrate/migrate/issues/546), so use the master branch if you want to use the `iofs` source driver.
