### ISSUE TITLE
Sign up for packagecloud.io

### ISSUE THREAD

**Issue by jeffreylo** [golang-migrate/migrate#6]
Installing via `apt-get` does not currently work as `golang-migrate` doesn’t currently have an account on packagecloud.io.

**Comment by dhui** [comment]
Thanks @jeffreylo for bringing this to my attention!
I'm working with package cloud to convert the account to the open source plan. I guess signups defaulted to the medium plan.

**Comment by jeffreylo** [comment]
Might be worth considering getting a patreon or something set up so that the community / companies can contribute too!

**Comment by dhui** [comment]
I'd rather have code contributions over monetary contributions.

Also, the great folks at packagecloud have moved us over to the open source plan so you should be able to start using the packagecloud repo now!
