### ISSUE TITLE
Entrypoint issue on latest

### ISSUE THREAD

**Issue by bartwrobel** [golang-migrate/migrate#607]
**Describe the Bug**
Getting `Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/migrate": stat /migrate: no such file or directory: unknown`

**Steps to Reproduce**
1. My migrations look like 'not related'
2. I ran migrate with the following options
`  migration:
    image: "migrate/migrate"
    depends_on:
      - postgres
    volumes:
      - ./migration:/migration
    env_file:
      - _env
    entrypoint: ["/migrate", "-path", "/migration", "-database", "postgres://dbuser:dbpass@postgres:5432/test?sslmode=disable", "-verbose"]
    command: up`
3. See error
`Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/migrate": stat /migrate: no such file or directory: unknown`

**Expected Behavior**
Migrations should be executed.
**Migrate Version**
latest

**Go Version**
go version go1.15.5 darwin/amd64

**Stacktrace**
`Pulling migration (migrate/migrate:)...
latest: Pulling from migrate/migrate
540db60ca938: Pull complete
61a2117da40b: Pull complete
32fa9a378efd: Pull complete
Digest: sha256:f348f98babe047ba7ab3890ccbf5ead7623e51ee3596cc4c440ecae01766cbd7
Status: Downloaded newer image for migrate/migrate:latest
Creating my_service_migration_run ... done
Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/migrate": stat /migrate: no such file or directory: unknown`

**Additional context**
Works with `migrate/migrate:v4.14.1`

**Comment by Fontinalis** [comment]
Thank you for reporting the issue! We just changed the building process for the releases and the issue is in the Dockerfile we use for the build, it's not creating a link for `/migrate` which the previous one did. We're going to fix it shortly and make a new release with the fix.
