### ISSUE TITLE
error: database driver: unknown driver clickhouse (forgotten import?)

### ISSUE THREAD

**Issue by ip75** [golang-migrate/migrate#611]
```
git:(master) ✗ migrate -path internal/storage/migrations -database "clickhouse://localhost:9000?database=my_database&username=default" up 5
error: database driver: unknown driver clickhouse (forgotten import?)
```
questions: 
* how to import?
* where import to?

**Comment by dhui** [comment]
Not sure how you installed the CLI, but you'll need to specify the correct build tag. See the instructions and notes [here](https://github.com/golang-migrate/migrate/tree/master/cmd/migrate#with-go-toolchain)

**Comment by ip75** [comment]
instructions you mentioned are obsolete............

https://github.com/golang-migrate/migrate/pull/257#issuecomment-526949205
