### ISSUE TITLE
error: database driver: unknown driver clickhouse (forgotten import?)

### ISSUE THREAD

**Issue by ip75** [golang-migrate/migrate#612]
**Describe the Bug**
```
git:(master) ✗ migrate -path internal/storage/migrations -database "clickhouse://localhost:9000?database=my_database&username=default" up 5
error: database driver: unknown driver clickhouse (forgotten import?)
```
questions: 
* how to import?
* where import to? 

**Steps to Reproduce**
1. My migrations look like sql script
2. I ran migrate with the following options  `migrate -path internal/storage/migrations -database "clickhouse://localhost:9000?database=my_database&username=default" up 5`
3. See error  `error: database driver: unknown driver clickhouse (forgotten import?)`

**Expected Behavior**
error: database driver: unknown driver clickhouse (forgotten import?)
see description how to import driver by following link `https://how/to/import/driver/in/migrate`

**Migrate Version**
e.g. v3.4.0
Obtained by running: `migrate -version`
```
➜  go git:(mod) ✗ migrate --version
dev
➜  go git:(mod) ✗ which migrate
/usr/local/go/bin/migrate
```

**Loaded Source Drivers**
e.g. s3, github, go-bindata, gcs, file
Obtained by running: `migrate -help`

**Loaded Database Drivers**
```
.....................
Source drivers: file
Database drivers: stub
```

**Go Version**
```
➜  go git:(mod) ✗ go version  
go version go1.16.7 linux/amd64
```

**Comment by nuraliyevsherhonbek** [comment]
if your db is postgresql , you use this command 'go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest' to add driver
