### ISSUE TITLE
Issue with installing migrate on go1.17 / linux

### ISSUE THREAD

**Issue by wr125** [golang-migrate/migrate#619]
**Is your feature request related to a problem? Please describe.**
attempted to follow instructions to down load migrations by using "go get" command and received the following;
go get -u -d github.com/golang-migrate/migrate/cmd/migrate
go: downloading github.com/golang-migrate/migrate v3.5.4+incompatible
go get: module github.com/golang-migrate/migrate@upgrade found (v3.5.4+incompatible), but does not contain package github.com/golang-migrate/migrate/cmd/migrate.

Tied locating the the download but can't find it anywhere. 

**Describe the solution you'd like**
How do I upgrade, as a command? Where can I find this on my system?

**Describe alternatives you've considered**
I've tried downloading the folder from github and cd github.com/golang-migrate/migrate and attempting to use .git but no git in this root folder. Tried migrate -version but system does not recognise this command because the cli is not installed.

**Additional context**

Update
managed to find this line of code; go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate. However, I have missing drivers on the cli. In fact i have no recognised drivers (stab) which I need postgresql as the following is the issue; migrate -path db/migration -database "postgresql://root:secrete@localhost:5434/testdb?sslmode=disable" -verbose up
2021/09/15 19:21:17 error: database driver: unknown driver postgresql (forgotten import?). How to I find drivers i.e, import?

**Comment by dhui** [comment]
Check the [docs](https://github.com/golang-migrate/migrate/tree/master/cmd/migrate#with-go-toolchain). e.g. try specifying `v4`.

**Comment by wr125** [comment]
Would you know what the issue is here?
make migrateupmigrate -path db/migration -database "postgresql://root:secret@localhost:5434/simple_project?sslmode=disable" -verbose up
2021/09/16 12:12:35 error: read tcp 127.0.0.1:49916->127.0.0.1:5434: read: connection reset by peer
Makefile:20: recipe for target 'migrateup' failed
make: *** [migrateup] Error 1

**Comment by rjustin861** [comment]
I encountered this issue as well. Anyone knows what might cause this?

`./migrate -path scripts/migrations_v2 -database "postgres://root:secret@127.0.0.1:5432/someproject?sslmode=disable" up` 

error: read tcp 127.0.0.1:54238->127.0.0.1:5432: read: connection reset by peer

**Comment by petelah** [comment]
Encountered this error as well when running migrations in our pipelines via the CLI. The problem was installing via `go install`. After downloading the release binary migrations worked perfect.
