### ISSUE TITLE
Package Installation 

### ISSUE THREAD

**Issue by elbek** [golang-migrate/migrate#621]
Hi Folks, 
How one would install this so it can be used from cli. Should `go get` do the job? I tried and I cannot find the binaries in `go/bin` folder. 
I have run `go get github.com/golang-migrate/migrate/cmd/migrate`, I see it under pkg, but not under go/bin folder. 

Also would be great to add installation instruction to the readme. I asked other folks, they have used `cURL` to download the binaries which seems not right. 

Thanks,
Elbek.

**Comment by dhui** [comment]
[Use](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies) `go install`

CLI install instructions are [here](https://github.com/golang-migrate/migrate/tree/master/cmd/migrate). You can install pre-built binaries or build them yourself.
