### ISSUE TITLE
Undocumented breaking change in migrate/migrate Docker image

### ISSUE THREAD

**Issue by hairyhenderson** [golang-migrate/migrate#625]
**Describe the Bug**

Starting with v4.15.0, the `migrate` binary is no longer present at `/usr/local/bin/migrate`, but has moved to `/usr/bin/migrate`.

**Steps to Reproduce**
1. List the original location in the v4.14.1 image:
    ```console
    $ docker run -it --rm --entrypoint '' migrate/migrate:v4.14.1 which migrate
    /usr/local/bin/migrate
    ```
2. List the new location in the v4.15.0 image:
    ```console
    $ docker run -it --rm --entrypoint '' migrate/migrate:v4.15.0 which migrate
    /usr/bin/migrate
    ``` 

**Expected Behavior**

Expected the binary to remain in `/usr/local/bin/migrate` since this was a minor version bump and compatibility was expected, since no mention was made of this change in the release notes.

**Migrate Version**

v4.15.0

**Additional context**

I bundle the `migrate` binary into another image like this:

```docker
FROM migrate/migrate:v4.15.0 AS migrate
FROM alpine:3.14.2

COPY --from=migrate /usr/local/bin/migrate /usr/local/bin/migrate
[...]
```

Of course, if the path changes, the image build breaks as well.

To be clear, _this is a minor issue_, and I'm totally OK with tweaking my `Dockerfile` to adjust, however this was a surprise, and not listed in the [release notes](https://github.com/golang-migrate/migrate/releases/tag/v4.15.0).

**Comment by Fontinalis** [comment]
Nice catch, thank you for reporting! I'm thinking about a quick fix for this in `v4.15.1` as this probably causes an issue for many people.
