### ISSUE TITLE
Installing v4.15 fails due to missing dependency tag

### ISSUE THREAD

**Issue by obitech** [golang-migrate/migrate#637]
**Describe the Bug**
Running `go get` without the standard `$GOPROXY` `proxy.golang.org` fails due to a missing dependency tag (see https://github.com/snowflakedb/gosnowflake/issues/481). Maybe we can bump the dependency here?

**Steps to Reproduce**
```
± go get github.com/golang-migrate/migrate/v4
go get: github.com/golang-migrate/migrate/v4@v4.15.0 requires
        github.com/snowflakedb/gosnowflake@v1.4.3: reading https://goproxy.xxx.net/github.com/snowflakedb/gosnowflake/@v/v1.4.3.mod: 404 Not Found
```

**Expected Behavior**
migrat v4.15.0 should be installed without any issues.

**Migrate Version**
v4.15.0

**Go Version**
`go version go1.17.2 darwin/amd64`

**Comment by dhui** [comment]
Can you confirm that using gosnowflake v1.6.3 fixes the issue? e.g. test with `go get github.com/golang-migrate/migrate/v4@master`
