### ISSUE TITLE
Failed to migrate: Dirty database version 30. Fix and force version.

### ISSUE THREAD

**Issue by liuchaowhu** [golang-migrate/migrate#678]
I have a harbor-core pod restart, and then throw this error

Failed to migrate: Dirty database version 30. Fix and force version.

Can i fixed by manually ?

**Comment by rokf** [comment]
This means that the 30th migration couldn't be executed. There was an error. You'll have to fix the 30th migration file, then you'll have to reset the dirty flag from the schema table and set the version in the schema table to 29. After you've done all that you'll be able to continue with the migration process.

**Comment by liuchaowhu** [comment]
i upgrade harbor from 1.10.9 to 2.2.3  ,the most important step is  
docker  run -v  /:/hostfs  goharbor/prepare:v2.2.3  migrate --input  /usr/local/src/harbor-1.10.9/harbor.yml   --output  /usr/local/src/harbor-2.2.3/harbor.yml

**Comment by dhui** [comment]
Closing as it seems that the issue has been resolved. Thanks for the help @rokf !
