### ISSUE TITLE
Getting error - "no buildable Go source files" in golang-migrate/migrate/database/postgres

### ISSUE THREAD

**Issue by aayush2610** [golang-migrate/migrate#68]
I have included "github.com/golang-migrate/migrate" in Gopkg.toml but strangely getting this error on build.

**Comment by aebie** [comment]
I opened a similar issue today and it was caused by my go version of 1.8. the postgres.go file required go 1.9

**Comment by dhui** [comment]
@aayush2610 how are you building your project or the CLI?

For reference, here's @aebie's issue: https://github.com/golang-migrate/migrate/issues/67

**Comment by aayush2610** [comment]
Thanks @aebie and @dhui this helps!!
