### ISSUE TITLE
Bump library version for SQLite to have new features for ALTER TABLE

### ISSUE THREAD

**Issue by cdamoc90poe** [golang-migrate/migrate#683]
The current version of sqlite library `github.com/mattn/go-sqlite3 v1.14.6` does not have support for ALTER TABLE DROP COLUMN, which in SQLite was introduced with version 3.35.0, which is already available in `github.com/mattn/go-sqlite3 v1.14.10` which uses SQLite version 3.37.0

**Solution**:
Update the library version in go.mod file to `github.com/mattn/go-sqlite3 v1.14.10`

**Comment by pankona** [comment]
Hi, maintainer

This is my first contribution to this project. If there's something wrong with my submit, please don't hesitate to say anything to me. Thanks in advance! 💪

**Comment by cdamoc90poe** [comment]
@dhui Can we have a new release which includes this bump ?
