### ISSUE TITLE
Hash check failed

### ISSUE THREAD

**Issue by mkarpeles** [golang-migrate/migrate#688]
When trying to install golang-migrate on Windows 10, command line shows:

Checking hash of migrate.windows-amd64.zip ... ERROR Hash check failed!
App:         main/migrate
URL:         https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.windows-amd64.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    cd073cfb5fb5668839cb8933e02aa6bd53533dd534c0a8674e06ad878f1d96e3
Actual:      d5bde0c172ff31031244343f93c4bcc6c133233af33d3d1d86e4c6e0b3aa1373

Please try again or create a new issue by using the following link and paste your console output:

**Comment by dhui** [comment]
I think you have a corruption issue or are checking with another file (or version of migrate), the checksum matched for me:
```
$ curl -sSLO https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.windows-amd64.zip
$ echo "cd073cfb5fb5668839cb8933e02aa6bd53533dd534c0a8674e06ad878f1d96e3  migrate.windows-amd64.zip" | shasum -a 256 -c
migrate.windows-amd64.zip: OK
```
