### ISSUE TITLE
Migrate command not creating tables if sql file name is same but new tables are added to it

### ISSUE THREAD

**Issue by varundunga** [golang-migrate/migrate#709]
**Describe the Bug**
Migrations is saying no change when the content in sql files is changed but file names remain same
**Steps to Reproduce**
1. I have a migrations folder containing initialize_up.sql (has one create statement) and intialize_down.sql (has one drop statement)
2. I ran migrate and it created the tables
3. now i changed the initialize_up.sql by adding one more table to it and ran the migrate command
4. However the new table is not created and i can see no change getting printed on to the console

**Expected Behavior**
Both the tables should have been created

**Migrate Version**
e.g. v4.8.0
Obtained by running: `migrate -version`

**database driver**
postgres

**Comment by domino14** [comment]
this isn't a bug; sql files should be considered immutable. You should create a new migration.
