### ISSUE TITLE
Syntax error if multiple queries in a sql file

### ISSUE THREAD

**Issue by nsatvik** [golang-migrate/migrate#72]
I've these queries in my migration file. 
`CREATE TABLE users (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name varchar(48),
  email varchar(24),
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT  NOW(),
  created_by varchar(64) NOT NULL,
  updated_by varchar(64) NOT NULL
);
CREATE INDEX user_email_indx ON users(email);`
When I  run `Up()` it complains that there is an error near the beginning of `CREATE INDEX`.
Am I missing something?

**Comment by dhui** [comment]
Try running your SQL statements directly in a sql client

**Comment by nsatvik** [comment]
There is no error in the sql statements. They work just fine on the MySQL console.

**Comment by dhui** [comment]
I don't see any obvious issues in your SQL statements.
I'd wrap your migrations in `BEGIN/COMMIT` as mentioned here: https://github.com/golang-migrate/migrate/tree/master/database/mysql#upgrading-from-v1

Also, try putting your `CREATE TABLE` and `CREATE INDEX` statements on their own lines.
What's the full error message that you're seeing?

**Comment by nsatvik** [comment]
Adding this `multiStatements=true` to the database connection url  fixes the issue. 
Thanks!
