### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by adam-banked** [golang-migrate/migrate#722]
Hi, could you please cut a new release at some point? Our project requires some bug fixes for Spanner that went in a few months back so we cannot use the last release from October. It would be awesome if we could download the release in our CI pipeline rather than building from master.

Thanks for all your great work!

**Comment by loginakhil** [comment]
Hello @dhui ,

Could you please release the latest version 🙏

**Comment by pankona** [comment]
@dhui 
I'm also waiting for new release. If you are interested in an additional maintainer, especially who helps to ship new releases, I think I may be able to support something. I'm happy if you consider it. Thanks!

**Comment by Fontinalis** [comment]
Hey everyone, 

We're sorry for the late response. We just released [v4.15.2](https://github.com/golang-migrate/migrate/releases/tag/v4.15.2) with the current changes in master and we'll do our best to resolve the currently open pull requests and merge them, so we can release the next version as well (probably `v4.16.0`).

Thanks for your patience and for your contributions!

**Comment by dhui** [comment]
@pankona thanks for offering to be a co-maintainer! ❤️ 

@Fontinalis and I would love to take you up on that offer but would like to see a larger contribution to the project (e.g. a larger PR) before doing so. I've [started a discussion](https://github.com/golang-migrate/migrate/discussions/740) about this so we can agree on what contribution makes sense.
