### ISSUE TITLE
homebrew package name required

### ISSUE THREAD

**Issue by ahxxm** [golang-migrate/migrate#73]
I tried to add cli tool to homebrew(a package management tool for macos), one reviewer [says](https://github.com/Homebrew/homebrew-core/pull/30032#discussion_r202346081) that name `migrate` conflicts with existing tool `sqlalchemy-migrate`.

Although `sqlalchemy-migrate` does not write anything to $PATH, it's good we have a prefix, how about `golang-migrate`?

**Comment by ilovezfs** [comment]
Ref: https://repology.org/metapackage/migrate/versions

**Comment by dhui** [comment]
Thanks for taking the initiative on this @ahxxm!
Using the name `golang-migrate` as the binary in homebrew is fine w/ me. It'll be a bit confusing since that will deviate from the name from the other installation methods, but docs should help.

**Comment by ilovezfs** [comment]
@dhui the issue is the package name not the binary name, which can be `migrate` (not a problem). But should users

```
brew install migrate
```

```
brew install gomigrate
```

```
brew install go-migrate
```

```
brew install golang-migrate
```

or something else?

The most problematic is `brew install migrate` as `migrate` is a brew command and a commonly used package name in other package managers for a different project.

**Comment by dhui** [comment]
@ilovezfs Ahhh, I've been using the package name`golang-migrate` if `migrate` is not available. So `brew install golang-migrate` sounds good

**Comment by ilovezfs** [comment]
Cool, we'll do that then. It is your organization name after all!
