### ISSUE TITLE
Migrations from gitlab source empty ref

### ISSUE THREAD

**Issue by grum261** [golang-migrate/migrate#735]
**Describe the Bug**
In ```source/gitlab/gitlab.go``` function Open, that fetches json from gitlab api, uses struct ListTreeOptions with Ref field that have omitempty tag, when Open parses url on first line of function, in parsed url we have u.Fragment with value of empty string (```""```), which means that pointer to u.Fragment is not nil and request URL looks like: https://gitlab.com/api/v4/projects/278964/repository/tree?path=db&ref=, because of that api responses with ```{"message":"404 Tree Not Found"}```, but if i remove ref= it works like expected.

**Steps to Reproduce**
You can try on any repository
```
m, err := migrate.NewWithDatabaseInstance(
	"gitlab://username:pass@gitlab.com/278964/db",
	"sqlserver", driver,
)
if err != nil {
	log.Fatal(err)
}
```
returning error: `GET https://gitlab.com/api/v4/projects/278964/repository/tree: 404 {message: 404 Tree Not Found}`

**Expected Behavior**
Create migration

**Migrate Version**
github.com/golang-migrate/migrate/v4 v4.15.1
Obtained from `go.mod`

**Loaded Source Drivers**
file, gitlab
Obtained from `go.mod`

**Loaded Database Drivers**
sqlserver
Obtained from `go.mod`

**Go Version**
go version go1.17.7 linux/amd64
Obtained by running: `go version`

**Comment by grum261** [comment]
I figure it out, you have to set ref to migrate, unfortunately, I did not immediately understand this from the returned errors

**Comment by Quantum12k** [comment]
In case anyone wondering, adding branch (for example #main) to the url helps.
