### ISSUE TITLE
Support for "multistatements" on sqlserver using GO statement delimiter

### ISSUE THREAD

**Issue by tomqwpl** [golang-migrate/migrate#756]
**Is your feature request related to a problem? Please describe.**
SQLServer is annoying. 
There are various things that you can't do "in one go" as it were. Various things require you to use multiple statement batches, separated by the GO statement. 
There is no support for GO here. Instead it is necessary to put each part in a separate migrate file, which can be annoying and lead to an unnaturally long collection of files.

**Describe the solution you'd like**
I can see that Postgres for example supports splitting the migrate statement at ; and running each statement separately.
I can imagine doing exactly the same for SQLServer with GO.

For comparison, flyway always splits the migrate script on GO, or ; or other equivalent database specific separator.

**Describe alternatives you've considered**
Putting the parts into separate .sql files can be done, but it's annoying and leads to unnatural splitting of the migrate steps.

**Additional context**

**Comment by tomqwpl** [comment]
OK, this is more complex than I hoped.
What I hadn't considered is that GO can exist with an identifier, so splitting has to look for GO surrounded by whitespace.
It looks like flyway takes a slightly more complex approach to parsing the expressions than just splitting on semicolon (which would be necessary to cope with a semicolon within a quoted string for example)

**Comment by dhui** [comment]
See #666
