### ISSUE TITLE
Other linux distros

### ISSUE THREAD

**Issue by Bergmann5** [golang-migrate/migrate#762]
**Describe the Bug**
The linux installation is meant for ubuntu, it can't install on 
other debian distros
**Steps to Reproduce**
1. I try to echo
2. 
3. See error
4. echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
bash: /etc/apt/sources.list.d/migrate.list: Permission denied

**Comment by domssilva** [comment]
this is an issue with privileges, what solved this issue for me was this solution https://askubuntu.com/a/185273

run:
```bash
sudo echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/migrate.list
```

**Comment by dhui** [comment]
Closing as @domssilva's solution looks correct
