### ISSUE TITLE
Programmatic Use in Multiple Container Environment like AWS ECS

### ISSUE THREAD

**Issue by sachinwalia2k8** [golang-migrate/migrate#80]
Hi,
I am interested in using golang-migrate in my project with postgres. What I'd like to do is during my service startup call the API and initiate migration. My question is since I use container service (AWS ECS) which launches multiple containers simultaneously so how does golang-migrate behave. Does it acquire any database locks so that only one instance is running migration. Or is it meant for only single container environment?

**Comment by dhui** [comment]
The postgres driver uses [advisory locks](https://www.postgresql.org/docs/10/static/explicit-locking.html#ADVISORY-LOCKS), so you can run [migrate.Up()](https://godoc.org/github.com/golang-migrate/migrate#Migrate.Up) on all of your app servers/containers. The code is [here](https://github.com/golang-migrate/migrate/blob/master/database/postgres/postgres.go#L123).
