### ISSUE TITLE
convert to standalone repository

### ISSUE THREAD

**Issue by explodingcamera** [golang-migrate/migrate#81]
Hi, first of all I want to say I really like this project and appreciate all the afford you guys have put into this!
When I tried to search for something in the code on github, It wasn't possible because searching is disabled in forks.
To convert a fork to a standalone project, can have to contact github support:
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork
I've done this before without any issues and got a quick response.
This would also remove the confusing `This branch is 128 commits ahead` at the top.

**Comment by dhui** [comment]
Thanks for the tip! I've put in the request.
