### ISSUE TITLE
https://packagecloud.io/golang-migrate/migrate/ doesn't seem to support ubuntu/jammy (ubuntu-22.04)

### ISSUE THREAD

**Issue by makotoshimazu** [golang-migrate/migrate#818]
**Describe the Bug**

I have a CI job using `migrate` command installed by these commands:

```sh
curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | sudo apt-key add -
sudo sh -c 'echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list'
sudo apt update
sudo apt install -y migrate
```

but `apt update` failed with error as follows:

```
E: The repository 'https://packagecloud.io/golang-migrate/migrate/ubuntu jammy Release' does not have a Release file.
```

**Steps to Reproduce**
- Run the commands above on Ubuntu-22.04 (I'm using `cimg/go:1.19` docker image)

**Expected Behavior**
- No error happens during installation

**Comment by wavemoran** [comment]
As a workaround, we moved to installing from the release files directly.

```sh
wget http://github.com/golang-migrate/migrate/releases/latest/download/migrate.linux-amd64.deb
sudo dpkg -i migrate.linux-amd64.deb
```

**Comment by mouyong** [comment]
#818

**Comment by dhui** [comment]
Support for Ubuntu Jammy Jellyfish was added in [v4.16.1](https://github.com/golang-migrate/migrate/releases/tag/v4.16.1)
