### ISSUE TITLE
Error: no schema SQLite3

### ISSUE THREAD

**Issue by yosa12978** [golang-migrate/migrate#837]
When i type `migrate -path "./migrations" -database "./database.db" up 1` it returns `error: no schema`. 
But i have an up and down migrations in migrations folder. What should i do to make a migration?

**Comment by CaioTeixeira95** [comment]
I believe you forgot to specify the driver.

Look here:

https://github.com/golang-migrate/migrate/blob/31791adbc0e4f45e0cb13fbc3d13095b78709dc6/internal/url/url.go#L12-L25

You should do:

```sh
migrate -path "./migrations" -database "sqlite3:file:database.db" up 1
```

**Comment by neilyoung** [comment]
I'm running this with a brew installed migrate. Does this support sqlite at all?

```
migrate -path "./" -database "sqlite://test.db"  up 1
error: failed to open database, "sqlite://test.db": database driver: unknown driver sqlite (forgotten import?)
```
