### ISSUE TITLE
file does not exist for timestamp migration

### ISSUE THREAD

**Issue by zkrzyzanowski** [golang-migrate/migrate#838]
**Describe the Bug**
Running migrations with default timestamp prefix fails with the following error:
```
error: no migration found for version 1: read down for version 1 .: file does not existerror: no migration found for version 1: read down for version 1 .: file does not exist
```

running with `-seq` flags results in successful migration

**Steps to Reproduce**
```
migrate create -ext sql -dir migrations some_migration_name
migrate -source file://migrations -database "postgres://username:password@localhost:5432/dbname?sslmode=disable" up
```

**Expected Behavior**
migration is run and changes are reflected in target db.

**Migrate Version**
v4.15.1

**Loaded Source Drivers**
file

**Loaded Database Drivers**
clickhouse, mongodb, neo4j, firebirdsql, redshift, spanner, stub, cockroach, cockroachdb, firebird, postgresql, sqlserver, cassandra, crdb-postgres, mongodb+srv, mysql, pgx, postgres

**Go Version**
go version go1.19.1 darwin/amd64

**Stacktrace**
```
error: no migration found for version 1: read down for version 1 .: file does not existerror: no migration found for version 1: read down for version 1 .: file does not exist
```

**Additional context**
running with `-seq` flag creates a migration and can be run successfully.

**Comment by Genialngash** [comment]
facing this issue too
