### ISSUE TITLE
source driver: unknown driver file (forgotten import?)

### ISSUE THREAD

**Issue by kerak19** [golang-migrate/migrate#86]
I have problem with running migrations inside of my app.

code running migrations:
```
package main

import (
	"context"
	"database/sql"
	"errors"
	"flag"
	"net"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/coreos/go-systemd/activation"
	_ "github.com/golang-migrate/migrate/source/file"
	"github.com/kerak19/template/internal/config"
	"github.com/kerak19/template/internal/controller"
	"github.com/kerak19/template/internal/flags"
	_ "github.com/lib/pq"
	"github.com/mattes/migrate"
	"github.com/mattes/migrate/database/postgres"
	"github.com/onrik/logrus/filename"
	"github.com/sirupsen/logrus"
)

...

func runMigrations(migrationsPath string, db *sql.DB) error {
	if migrationsPath == "" {
		return errors.New("missing migrations path")
	}
	driver, err := postgres.WithInstance(db, &postgres.Config{})
	if err != nil {
		return err
	}
	m, err := migrate.NewWithDatabaseInstance("file://"+migrationsPath,
		"postgres", driver)
	if err != nil {
		return err
	}
	err = m.Up()
	if err != nil && err != migrate.ErrNoChange {
		return err
	}
	return nil
}
```

This piece of code returns `source driver: unknown driver file (forgotten import?)` error

**Comment by kerak19** [comment]
All right, i think i've found the issue and it's ugly.
The import of `github.com/mattes/migrate/source/file` cannot be made before `github.com/mattes/migrate` and `github.com/mattes/migrate/database/postgres` or it won't work, which looks like some kind of race.

**Comment by dhui** [comment]
The import order shouldn't matter.
However, you do need to import `github.com/mattes/migrate/source/file` before using the file source as the source drivers are registered in the package `init()` function.

**Comment by SealinGp** [comment]
however. i still got the same error after import _ 'github.com/golang-migrate/migrate/source/file', is there anyone help me ? 
`package orm

import (
	"context"
	"fmt"
	"io"
	"log"
	"path/filepath"
	"time"

	"github.com/SealinGp/independ-store/pkg/impl"
	"github.com/golang-migrate/migrate/source"
	"github.com/golang-migrate/migrate/v4"
	migrate_mysql "github.com/golang-migrate/migrate/v4/database/mysql"
	"xorm.io/xorm"
	xlog "xorm.io/xorm/log"

	_ "github.com/go-sql-driver/mysql"
	_ "github.com/golang-migrate/migrate/source/file"
)

//https://pkg.go.dev/github.com/golang-migrate/migrate#section-readme

var _ (impl.Migrator) = (*Mysql)(nil)

type Mysql struct {
	engine *xorm.Engine
	mig    *migrate.Migrate

	db             string
	dsn            string
	migrationsPath string
	logWriter      io.Writer
}

type MysqlOption struct {
	Host string
	Port int
	User string
	Pass string
	DB   string

	MigrationsPath string
	LogWriter      io.Writer
}

func NewMysql(opt *MysqlOption) *Mysql {
	dsn := fmt.Sprintf("%v:%v@tcp(%v:%v)/%v?charset=utf8", opt.User, opt.Pass, opt.Host, opt.Port, opt.DB)
	if opt.LogWriter == nil {
		opt.LogWriter = log.Writer()
	}

	m := &Mysql{
		db:  opt.DB,
		dsn: dsn,

		migrationsPath: opt.MigrationsPath,
		logWriter:      opt.LogWriter,
	}
	return m
}

func (m *Mysql) Start() error {
	e, err := xorm.NewEngine("mysql", m.GetDsn())
	if err != nil {
		log.Printf("[E] new xorm engine failed. dsn:%v", m.GetDsn())
		return err
	}
	e.SetLogger(xlog.NewLoggerAdapter(xlog.NewSimpleLogger(m.logWriter)))
	e.SetLogLevel(xlog.LOG_DEBUG)

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*10)
	defer cancel()
	err = e.PingContext(ctx)
	if err != nil {
		return err
	}

	instanceCfg := &migrate_mysql.Config{
		MigrationsTable: "schema_migrations",
		DatabaseName:    m.db,
	}
	instance, err := migrate_mysql.WithInstance(e.DB().DB, instanceCfg)
	if err != nil {
		return err
	}

	absPath, err := filepath.Abs(m.migrationsPath)
	if err != nil {
		log.Printf("[E] abs migrations path failed. err:%v", err)
		return err
	}

	log.Printf("[I] drivers:%v", source.List())

	source := fmt.Sprintf("file://%v", absPath)
	mig, err := migrate.NewWithDatabaseInstance(
		source,
		e.DriverName(),
		instance,
	)
	if err != nil {
		log.Printf("[E] new migrate failed. source:%v, err:%v", source, err)
		return err
	}

	m.engine = e
	m.mig = mig
	return m.MigrateData()
}

func (m *Mysql) MigrateData() error {
	return m.mig.Up()
}

func (m *Mysql) Close() error {
	if m.engine != nil {
		m.engine.Close()
	}
	if m.mig != nil {
		m.mig.Close()
	}
	return nil
}

//[scheme://][user[:[password]]@]tcp(host[:port])[/schema][?attribute1=value1&attribute2=value2...
func (m *Mysql) GetDsn() string {
	return m.dsn
}
`

**Comment by dhui** [comment]
@SealinGp I suspect there's an issue with `github.com/SealinGp/independ-store/pkg/impl` using file sources before they're imported

**Comment by dhiemaz** [comment]
I facing the same issue and solved.

here is the import in my code
`import (
	"github.com/dhiemaz/web-go/config"
	_ "github.com/go-sql-driver/mysql"
	"github.com/golang-migrate/migrate/v4"
	"github.com/golang-migrate/migrate/v4/database/mysql"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	_ "github.com/mattes/migrate/source/file"
	"log"
)
`

**Comment by muhammadqazi** [comment]
> I am also facing the same issue and solved it.
> 
> here is the import in my code
> 
> ```
> import (
> 	"github.com/dhiemaz/web-go/config"
> 	_ "github.com/go-sql-driver/mysql"
> 	"github.com/golang-migrate/migrate/v4"
> 	"github.com/golang-migrate/migrate/v4/database/mysql"
> 	_ "github.com/golang-migrate/migrate/v4/source/file"
> 	_ "github.com/mattes/migrate/source/file"
> 	"log"
> )
> ```

worked for me
