### ISSUE TITLE
Multiple sql statements cannot be executed when the migration is running

### ISSUE THREAD

**Issue by OldSmokeGun** [golang-migrate/migrate#883]
Multiple sql statements cannot be executed when the migration is running

**Migrate Version**
v4

**Loaded Source Drivers**
file

**Loaded Database Drivers**
mysql

**Go Version**
1.20

**this is my migration file content:**

```sql
create table user
(
    id         bigint unsigned auto_increment
        primary key,
    name       varchar(64)     default '' not null comment 'name',
    age        tinyint         default 0  not null comment 'age',
    phone      varchar(11)     default '' not null comment 'phone',
    created_at bigint                     not null,
    updated_at bigint          default 0  not null,
    deleted_at bigint unsigned default 0  not null
)
    comment 'users';

create index idx_user_deleted_at
    on user (deleted_at);
```

**this is error:**

```
Migrated error: migration failed in line 0: create table user
(
    id         bigint unsigned auto_increment
        primary key,
    name       varchar(64)     default '' not null comment 'name',
    age        tinyint         default 0  not null comment 'age',
    phone      varchar(11)     default '' not null comment 'phone',
    created_at bigint                     not null,
    updated_at bigint          default 0  not null,
    deleted_at bigint unsigned default 0  not null
)
    comment 'users';

create index idx_user_deleted_at
    on user (deleted_at); (details: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create index idx_user_deleted_at
    on user (deleted_at)' at line 14)
```

I do the migration by calling the up method in the program！

**Comment by PietvanderMeulen** [comment]
I'm facing the same issue.

**Comment by PietvanderMeulen** [comment]
I found the solution [here](https://stackoverflow.com/questions/28548559/does-a-go-mysql-driver-exist-that-supports-multiple-statements-within-a-single-s)
You have to set the `MultiStatements` flag of the mysql config for the driver to `true`.
Something like:
```go
cfg := mysql.NewConfig()
cfg.MultiStatements = true
// [...] more config

c, err := sql.Open(driverName, cfg.FormatDSN())
```

**Comment by OldSmokeGun** [comment]
> [我在这里](https://stackoverflow.com/questions/28548559/does-a-go-mysql-driver-exist-that-supports-multiple-statements-within-a-single-s)找到了解决方案 您必须将`MultiStatements`驱动程序的 mysql 配置标志设置为`true`. 就像是：
> 
> ```go
> cfg := mysql.NewConfig()
> cfg.MultiStatements = true
> // [...] more config
> 
> c, err := sql.Open(driverName, cfg.FormatDSN())
> ```

Thanks, it's useful
