### ISSUE TITLE
Support Multiple folders in CLI

### ISSUE THREAD

**Issue by Spazzy757** [golang-migrate/migrate#898]
**Is your feature request related to a problem? Please describe.**

I have an issue where in some instances we want to run our migrations to setup our database but in order to make development workflows easier we have another directory that has additional files (seed files), it would be great to use migrate to run both directories. The current state means we can only run one. 

**Describe the solution you'd like**
Allowing to pass multiple sources or paths to the CLI:
```bash
migrate -database $URL -source file://migrations/ -source file://seeds/ up
```

**Describe alternatives you've considered**
Previously I have used Knex to handle these kinds of situations but I wouldn't say I like adding Javascript on top of SQL. I'm not sure of any other way of handling this with go-migrate.

**Additional context**
I fully appreciate that this might be a niche use case but I have seen teams using this kind of functionality previously so thought I would log an issue and see if there is possibly another way to acheive this

**Comment by dhui** [comment]
Duplicates the following issues:
* https://github.com/golang-migrate/migrate/issues/177
* https://github.com/golang-migrate/migrate/issues/441
* https://github.com/golang-migrate/migrate/issues/562
* https://github.com/golang-migrate/migrate/issues/689
