### ISSUE TITLE
Error "unknown driver sqlite" while trying to migrate SQLite database

### ISSUE THREAD

**Issue by joeljuca** [golang-migrate/migrate#899]
**Describe the Bug**

I'm trying to use `migrate` with an SQLite database, but the SQLite driver doesn't seem to be available.

`migrate --help` outputs the following text (there's no `sqlite` driver):

```
$ migrate --help
Usage: migrate OPTIONS COMMAND [arg...]
       migrate [ -version | -help ]

Options:
  -source          Location of the migrations (driver://url)
  -path            Shorthand for -source=file://path
  -database        Run migrations against this database (driver://url)
  -prefetch N      Number of migrations to load in advance before executing (default 10)
  -lock-timeout N  Allow N seconds to acquire database lock (default 15)
  -verbose         Print verbose logging
  -version         Print version
  -help            Print usage

Commands:
  create [-ext E] [-dir D] [-seq] [-digits N] [-format] [-tz] NAME
           Create a set of timestamped up/down migrations titled NAME, in directory D with extension E.
           Use -seq option to generate sequential up/down migrations with N digits.
           Use -format option to specify a Go time format string. Note: migrations with the same time cause "duplicate migration version" error.
           Use -tz option to specify the timezone that will be used when generating non-sequential migrations (defaults: UTC).

  goto V       Migrate to version V
  up [N]       Apply all or N up migrations
  down [N] [-all]    Apply all or N down migrations
        Use -all to apply all down migrations
  drop [-f]    Drop everything inside database
        Use -f to bypass confirmation
  force V      Set version V but don't run migration (ignores dirty state)
  version      Print current migration version

Source drivers: bitbucket, github-ee, godoc-vfs, gcs, file, s3, github, gitlab, go-bindata
Database drivers: cassandra, firebird, mongodb+srv, pgx, stub, cockroach, cockroachdb, postgresql, redshift, spanner, neo4j, postgres, sqlserver, clickhouse, crdb-postgres, firebirdsql, mongodb, mysql
```

I'm using:

- migrate 4.15.2
- SQLite 3.41.1
- ZSH 5.9 (arm-apple-darwin20.6.0)
- Go 1.19.5 darwin/arm64
- macOS Ventura 13.1
- MacBook Pro M1

**Steps to Reproduce**

1. Create an SQLite database (`sqlite3 db.sqlite "create table vars (name, value)"`)
1. Create a migration directory (`mkdir migrations`)
1. Create a migration (`migrate create -ext sql -dir ./migrations create_logs`)
1. Put some SQL into the migration (`echo "create table logs (date, log) > *_create_logs.up.sql"`)
1. See the error `error: database driver: unknown driver sqlite`

**Expected Behavior**

The SQLite database should be migrated.

**Migrate Version**

```
$ migrate --version
v4.15.2
```

**Stacktrace**

There's none (at least not visibly from STDOUT).

**Comment by dhui** [comment]
How did you install the CLI?
SQLite isn't built by [default](https://github.com/golang-migrate/migrate/blob/master/Makefile#L2).
For SQLite CLI support, you'll need to [install the CLI via the Go toolchain](https://github.com/golang-migrate/migrate/tree/master/cmd/migrate#with-go-toolchain)

Duplicates: https://github.com/golang-migrate/migrate/issues/670
