### ISSUE TITLE
Github enterprise support

### ISSUE THREAD

**Issue by dgonzalez** [golang-migrate/migrate#92]
I can't seem to find the way to make it work in github enterprse. I think the current driver can be parametrized to point to a private github enterprise. Am I correct?

**Comment by dhui** [comment]
Are you referring to a migration source hosted on github?
If so, did you confirm that your credentials are correct?
What error are you getting?

**Comment by dhui** [comment]
Closing due to lack of response. Please reopen if this is still an issue

**Comment by kasparasg** [comment]
@dhui I see this has been closed a while back. I'd like to be able to use Github Enterprise repositories as the migrations source. Hopefully, this wouldn't be complex to add and I actually have some capacity to help with it.

I'd expect something like this to work 🤔 

```sh
migrate -source github://username:token@enterprise.github.com/Owner/Repo/path#ref -database postgres://postgres:postgres@localhost:54321/db up
```

Thoughts?

**Comment by dhui** [comment]
@kasparasg Thanks for tackling this issue and not creating a new issue!

Re-opening if we need to have discussions outside of the PR: #234

**Comment by dhui** [comment]
The master branch now supports [Github Enterprise](https://github.com/golang-migrate/migrate/tree/master/source/github_ee) thanks to @kasparasg 

Github EE file sources will be supported in the next release, after they've been in master for at least a week.
