### ISSUE TITLE
 Unable to install on Ubuntu 20.04 #416 

### ISSUE THREAD

**Issue by yaGatito** [golang-migrate/migrate#928]
failed to install after command $ sudo apt-get install migrate
logs:
[sudo] password for gato: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package migrate is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'migrate' has no installation candidate

**Comment by huzaifamk** [comment]
Same issue here, using Ubuntu 22.04!

**Comment by codegode23** [comment]
I tried this in my project folder's terminal and it worked: go get -u -d github.com/golang-migrate/migrate/v4

**Comment by huzaifamk** [comment]
These commands worked for me on Ubuntu 22.04 Jammy Jellyfish:

wget http://github.com/golang-migrate/migrate/releases/latest/download/migrate.linux-amd64.deb

sudo dpkg -i migrate.linux-amd64.deb

Reference taken from the below issue:
https://github.com/golang-migrate/migrate/issues/818

**Comment by codegode23** [comment]
Amazing huzaifamk, thank you

**Comment by dhui** [comment]
See the [CLI install instructions](https://github.com/golang-migrate/migrate/tree/master/cmd/migrate)
