### ISSUE TITLE
rubenv/sql-migrate -> golang-migrate tool

### ISSUE THREAD

**Issue by musinit** [golang-migrate/migrate#940]
**Is your feature request related to a problem? Please describe.**
We use sql-migrate (https://github.com/rubenv/sql-migrate) in our projects and we want to migrate to golang-migrate. We have a lot of migration files that we need to re-create for go-migrate format (with .up.sql, .down.sql postfix)

**Describe the solution you'd like**
Lib utils that would
 - rewrite migrations -> migrations-legacy
  - create a new migrations folder and re-create old migration files in a new format for go-migrate

**Describe alternatives you've considered**
Write this tiny util manually

**Additional context**
I am sure that would help a lot of teams to move from other migration tools to this one and make this library more popular.
We can implement migration tool for other libraries as well.

**Comment by musinit** [comment]
Ok, I will do it.

**Comment by musinit** [comment]
@dhui I did It:)
https://github.com/musinit/migradaptor
I think I can improve this one and add more sources for golang-migrate

**Comment by musinit** [comment]
Just added more sources: [db](https://github.com/amacneil/dbmate) and [goose](https://github.com/pressly/goose)

**Comment by dhui** [comment]
[Updated](https://github.com/golang-migrate/migrate/commit/bad30b549d4674e16755f5fdc1ce1a2028a1b49e) the README to mention migradaptor
