### ISSUE TITLE
doesn't work in my code

### ISSUE THREAD

**Issue by zzwl0219** [golang-migrate/migrate#944]
**Describe the Bug**
my code:
------------------------------------------
imgport(
        _ "github.com/go-sql-driver/mysql"
	"github.com/golang-migrate/migrate/v4"
	"github.com/golang-migrate/migrate/v4/database/mysql"
	_ "github.com/golang-migrate/migrate/v4/source/file"
)
func loadMigrate() (*migrate.Migrate, error) {
	p := configparser.Default()
	options, err := console.Configure(p)
	if err != nil {
		return nil, err
	}
	mysqlConf := options.MySQL[global.AMCDBName]
	db, err := sql.Open("mysql", fmt.Sprintf("%s:%s@tcp(%s:%s)/%s", mysqlConf.Username, mysqlConf.Password, mysqlConf.Path, mysqlConf.Port, mysqlConf.Dbname))
	if err != nil {
		return nil, err
	}
	driver, err := mysql.WithInstance(db, &mysql.Config{})
	if err != nil {
		return nil, err
	}
	return migrate.NewWithDatabaseInstance(
		"file://./docs/migrations",
		"mysql", driver)
}
func(cmd *cobra.Command, args []string) error {
			m, err := loadMigrate()
			if err != nil {
				return err
			}
			return m.Up()
		}

returns:
--------------------------------
023/06/19 15:52:57.292429 main.go:51: [Fatal] migration failed in line 0: BEGIN;
CREATE TABLE `task`
(
    `id`              bigint(10) unsigned NOT NULL AUTO_INCREMENT,
    `workspace_id`    bigint(10) unsigned NOT NULL,
    `is_deleted`      tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除:1已删除 0未删除',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

alter table task ADD COLUMN `check_count`  int(11) NOT NULL DEFAULT '0' COMMENT '检查总次数';
COMMIT;

 (details: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `task`
(
    `id`              bigint(10) unsigned NOT NULL AUTO_IN' at line 2)
exit status 1

But I have no error when using binary code：
---------------------------
migrate -database "mysql://root:admin@tcp(127.0.0.1:3306)/drc_console" -path docs/migrations/ up
202305181745/u v2_init (53.135004ms)

**Steps to Reproduce**
1. My migrations look like '...'
2. I ran migrate with the following options '....'
3. See error

**Expected Behavior**

**Migrate Version**
e.g. 4.16
Obtained by running: `migrate -version`

**Comment by zzwl0219** [comment]
my code bug

**Comment by HwHgoo** [comment]
I have the same problem and I can't see what's the bug in your code. Can you help me out?
